const ACTS=[

{n:0,t:"리눅스 첫걸음",s:"터미널을 한 번도 안 열어봤어도 괜찮다. 여기서 시작한다.",days:[

{d:1,t:"터미널을 연다",g:"검은 화면이 무엇인지 알고, 무서워하지 않게 된다.",
c:"<p>보안 일을 하려면 <b>터미널</b>을 씁니다. 영화에 나오는 검은 화면이 그것인데, 사실 별거 아닙니다. <b>마우스로 클릭하는 대신 글자로 명령하는 창</b>일 뿐입니다.</p><p>용어 세 개만 구분하면 됩니다.<br><b>터미널</b> — 글자를 주고받는 <em>창</em> 자체.<br><b>셸(shell)</b> — 그 창 안에서 내 명령을 해석해 실행해주는 <em>프로그램</em>. 리눅스는 보통 <code>bash</code> 나 <code>zsh</code> 를 씁니다.<br><b>프롬프트</b> — 명령을 기다리며 깜빡이는 <em>줄</em>. <code>hong@server:~$</code> 처럼 생겼습니다.</p><p>프롬프트를 읽는 법:<br><code>hong</code> 내 계정 이름 · <code>@server</code> 접속한 컴퓨터 이름 · <code>~</code> 지금 있는 위치(물결표는 내 홈 폴더) · <code>$</code> 여기부터 입력하라는 표시입니다. <b><code>$</code> 가 <code>#</code> 로 바뀌면 관리자(root)</b>라는 뜻이라, 그때는 조심해야 합니다.</p><p>명령을 치고 <b>Enter</b> 를 누르면 실행됩니다. 아무 반응 없이 다음 프롬프트가 뜨면 <b>성공한 겁니다.</b> 리눅스는 잘 되면 조용합니다.</p>",
term:"hong@server:~$ whoami\nhong\nhong@server:~$ date\nThu Aug 27 21:30:12 KST 2026\nhong@server:~$ <b>█</b>",
lab:["리눅스를 쓸 환경을 하나 준비한다 (윈도우면 PowerShell 관리자로 <code>wsl --install -d Ubuntu</code>)","터미널을 열고 프롬프트가 뜨는 것을 확인한다","<code>whoami</code> 를 치고 Enter — 내 계정 이름이 나온다","<code>date</code> 를 쳐서 현재 시각을 본다","<code>uname -a</code> 로 어떤 리눅스인지 확인한다","일부러 <code>asdf</code> 같은 없는 명령을 쳐보고 오류 메시지를 읽어본다","위쪽 화살표(↑)를 눌러 방금 친 명령이 다시 나오는지 확인한다"],
q:[{t:"프롬프트가 <code>root@server:/#</code> 로 보인다면 가장 중요한 사실은?",o:["홈 폴더에 있다","관리자(root) 권한으로 로그인한 상태라 실수하면 시스템이 망가질 수 있다","네트워크가 끊겼다","셸이 bash 가 아니다"],a:1,
  e:"<b><code>#</code> 은 root</b>, <code>$</code> 는 일반 사용자입니다. root 로는 <code>rm</code> 하나에 시스템이 날아갈 수 있어, 평소에는 일반 계정으로 쓰고 필요할 때만 <code>sudo</code> 를 붙이는 것이 원칙입니다."},
   {t:"명령을 실행했는데 아무것도 출력되지 않고 다음 프롬프트가 떴다. 무슨 뜻인가?",o:["실패했다","대부분 정상적으로 성공한 것이다","명령이 아직 실행 중이다","권한이 없다"],a:1,
    e:"유닉스 철학입니다 — <b>성공하면 조용하고, 문제가 있을 때만 말한다.</b> 처음에는 불안하지만 익숙해지면 오히려 편합니다."},
   {k:"cmd",t:"현재 로그인한 사용자 이름을 확인하는 명령을 입력하세요.",ph:"...",a:["whoami"],re:["^whoami$"],
    hint:"영어로 '나는 누구인가' 를 붙여 쓴 것입니다.",
    e:"<code>whoami</code> — 침해 조사에서 <b>공격자가 가장 먼저 치는 명령</b>이기도 합니다. 남의 서버에 들어왔으면 자기가 누구인지부터 확인해야 하니까요."}]},

{d:2,t:"지금 어디에 있는가",g:"폴더 사이를 이동하고 내용을 볼 수 있게 된다.",
c:"<p>터미널에는 항상 <b>'지금 있는 위치'</b>가 있습니다. 탐색기에서 폴더를 열어둔 것과 같습니다.</p><p><b><code>pwd</code></b> — print working directory. 지금 어디인지 알려줍니다.<br><b><code>ls</code></b> — list. 여기 뭐가 있는지 보여줍니다.<br><b><code>cd</code></b> — change directory. 다른 곳으로 이동합니다.</p><p><code>ls</code> 는 옵션과 같이 쓸 때 진짜 쓸모가 생깁니다.<br><code>ls -l</code> 자세히(권한·크기·날짜) · <code>ls -a</code> 숨김 파일까지 · <code>ls -h</code> 크기를 읽기 쉽게 · <code>ls -t</code> 최신순.<br>실무에서는 <b><code>ls -lah</code></b> 를 거의 한 단어처럼 씁니다.</p><p><b>리눅스에서 <code>.</code> 으로 시작하는 파일은 숨김 파일입니다.</b> <code>.bashrc</code>, <code>.ssh</code> 같은 것들인데, <b>공격자가 흔적을 숨기기 좋은 자리</b>라 조사할 때 <code>-a</code> 를 빼먹으면 안 됩니다.</p><p>이동 요령: <code>cd ..</code> 한 단계 위로 · <code>cd ~</code> 내 홈으로 · <code>cd -</code> 직전 위치로 · <code>cd</code> 만 쳐도 홈으로 갑니다.</p>",
term:"hong@server:~$ pwd\n/home/hong\nhong@server:~$ ls -lah\ndrwxr-xr-x 3 hong hong 4.0K Aug 27 21:30 .\n-rw-r--r-- 1 hong hong  220 Aug 27 21:30 <b>.bashrc</b>\ndrwx------ 2 hong hong 4.0K Aug 27 21:30 <b>.ssh</b>",
lab:["<code>pwd</code> 로 현재 위치를 확인한다","<code>ls</code> 와 <code>ls -lah</code> 를 각각 실행해 차이를 눈으로 본다","<code>ls -a</code> 로 숨김 파일이 몇 개나 있는지 센다","<code>cd /</code> 로 최상위로 갔다가 <code>ls</code> 로 폴더 목록을 본다","<code>cd ~</code> 로 홈에 돌아온다","<code>cd ..</code> 를 두 번 연속 실행하고 <code>pwd</code> 로 어디인지 확인한다","<b>Tab 키</b>로 자동완성을 써본다 — <code>cd /ho</code> 까지 치고 Tab","<code>ls -lt</code> 로 최근 수정된 파일이 위에 오게 정렬해본다"],
q:[{t:"침해 조사에서 <code>ls</code> 대신 <code>ls -a</code> 를 써야 하는 이유는?",o:["더 빠르다","<code>.</code> 으로 시작하는 숨김 파일이 보이지 않으면 공격자가 숨겨둔 것을 놓치기 때문","정렬이 된다","권한이 보인다"],a:1,
  e:"<code>.ssh/authorized_keys</code>, <code>.bash_history</code> 같은 <b>조사의 핵심 파일이 전부 숨김</b>입니다. <code>-a</code> 없이 보면 아무것도 없는 것처럼 보입니다."},
   {k:"cmd",t:"현재 폴더의 내용을 <b>숨김 파일까지, 자세히, 크기를 읽기 쉽게</b> 보는 명령을 입력하세요.",ph:"ls ...",a:["ls -lah"],re:["^ls\\s+-[lah]{3}$"],
    hint:"세 옵션을 붙여 씁니다. long · all · human-readable",
    e:"<code>ls -lah</code> — 옵션 순서는 상관없습니다(<code>-alh</code> 등도 동일). 리눅스를 쓰는 내내 가장 많이 치게 될 명령입니다."},
   {t:"<code>cd -</code> 는 어디로 이동하나?",o:["홈 디렉터리","한 단계 위","직전에 있던 위치","최상위 디렉터리"],a:2,
    e:"<b>직전 위치</b>로 돌아갑니다. 먼 두 폴더를 오갈 때 아주 편합니다."}]},

{d:3,t:"리눅스 폴더 지도",g:"어느 폴더에 무엇이 있는지 감을 잡는다. 로그 위치를 찾기 위한 준비.",
c:"<p>리눅스는 폴더 구조가 <b>정해져 있습니다.</b> 이걸 알면 '그 파일 어디 있지?' 로 헤매지 않습니다.</p><p><b><code>/</code></b> — 최상위(루트). 윈도우의 <code>C:\\</code> 자리입니다. 리눅스는 드라이브 문자가 없고 전부 <code>/</code> 아래에 붙습니다.</p><p>꼭 알아야 할 것들:<br><b><code>/home</code></b> 사용자별 개인 폴더. 내 것은 <code>/home/내계정</code><br><b><code>/etc</code></b> <b>설정 파일</b>이 모이는 곳. 사용자 목록·서비스 설정이 여기 있습니다<br><b><code>/var</code></b> 변하는 데이터. 그 안의 <b><code>/var/log</code> 가 로그 폴더</b>입니다<br><b><code>/tmp</code></b> 임시 파일. 누구나 쓸 수 있어 <b>공격자가 도구를 떨궈두는 단골 장소</b>입니다<br><b><code>/usr/bin</code>, <code>/bin</code></b> 명령어 프로그램들이 사는 곳<br><b><code>/root</code></b> 관리자 계정의 홈 (일반 사용자는 못 들어감)<br><b><code>/proc</code></b> 실제 파일이 아니라 <b>실행 중인 상태를 파일처럼 보여주는</b> 가상 폴더</p><p><b>이 코스의 나머지가 전부 <code>/var/log</code> 이야기입니다.</b> 오늘 그 위치를 몸에 익히면 다음이 훨씬 쉬워집니다.</p>",
term:"hong@server:~$ ls /\nbin  boot  dev  <b>etc</b>  home  lib  opt  proc  root  tmp  usr  <b>var</b>\n\nhong@server:~$ ls /var/log | head -5\nauth.log\nsyslog\ndpkg.log",
lab:["<code>ls /</code> 로 최상위 폴더 목록을 본다","<code>ls /etc | head -30</code> 으로 설정 파일들을 훑는다","<code>ls /var/log</code> 로 <b>로그 폴더</b>를 열어본다 (권한 오류가 나면 <code>sudo ls /var/log</code>)","<code>ls /home</code> 으로 이 서버의 사용자들을 본다","<code>ls -ld /tmp</code> 로 /tmp 의 권한을 확인한다 (끝이 <code>t</code> 로 끝남)","<code>ls /proc | head</code> 로 숫자 폴더들이 있는 것을 확인한다 (프로세스 ID)","각 폴더의 역할을 자기 말로 한 줄씩 적어 정리한다"],
q:[{t:"보안 로그가 모여 있는 폴더는?",o:["/etc","/var/log","/tmp","/usr/bin"],a:1,
  e:"<b>/var/log</b> 입니다. 이 코스 전체가 여기서 시작합니다. <code>/var</code> 는 '변하는 데이터', 그중 로그가 <code>/var/log</code> 입니다."},
   {t:"공격자가 다운로드한 도구를 떨궈두는 장소로 가장 흔한 곳은?",o:["/etc","/tmp","/boot","/root"],a:1,
    e:"<b>/tmp</b> 입니다. <b>누구나 쓸 수 있고</b> 재부팅하면 지워져 흔적도 덜 남습니다. 그래서 조사할 때 <code>ls -la /tmp</code> 는 기본 점검 항목입니다."},
   {k:"cmd",t:"로그 폴더의 내용을 자세히 보는 명령을 입력하세요. (권한이 필요할 수 있습니다)",ph:"...",a:["ls -l /var/log"],
    re:["^ls\\s+-l[ah]*\\s+/var/log/?$"],
    hint:"목록 명령에 자세히 옵션을 주고 경로를 지정합니다.",
    e:"<code>ls -l /var/log</code> — 권한 오류가 나면 앞에 <code>sudo</code> 를 붙입니다. 여기서 보이는 파일 이름들이 앞으로 계속 나옵니다."}]},

{d:4,t:"파일 들여다보기",g:"파일 내용을 보는 네 가지 방법을 상황에 맞게 골라 쓴다.",
c:"<p>로그는 결국 <b>텍스트 파일</b>입니다. 여는 방법이 네 가지 있는데, 상황에 따라 골라 써야 합니다.</p><p><b><code>cat 파일</code></b> — 전체를 한 번에 쏟아냅니다. <b>짧은 파일에만</b> 쓰세요. 10만 줄짜리 로그에 쓰면 화면이 몇 분간 흘러갑니다.</p><p><b><code>less 파일</code></b> — <b>스크롤하며 봅니다.</b> 긴 파일은 이걸 쓰세요.<br>안에서: <code>↑↓</code> 이동 · <code>Space</code> 다음 쪽 · <code>/단어</code> 검색 · <code>n</code> 다음 결과 · <code>G</code> 맨 끝 · <code>g</code> 맨 앞 · <b><code>q</code> 종료</b>.<br><b><code>q</code> 를 모르면 못 빠져나옵니다.</b> 이것만은 꼭 외우세요.</p><p><b><code>head -20 파일</code></b> — 앞 20줄. 파일 형식을 확인할 때.<br><b><code>tail -20 파일</code></b> — 뒤 20줄. <b>로그는 최신이 뒤에 붙으므로 tail 을 훨씬 자주 씁니다.</b></p><p><b><code>tail -f 파일</code></b> — 실시간 추적. 새 줄이 붙는 대로 화면에 나옵니다. 로그를 보면서 다른 창에서 뭔가 해볼 때 씁니다. <b><code>Ctrl+C</code> 로 중단</b>합니다.</p>",
term:"hong@server:~$ tail -3 /var/log/auth.log\nAug 27 21:30:01 srv CRON[1234]: pam_unix(cron:session): session opened\nAug 27 21:31:14 srv sshd[9901]: <b>Failed password for admin from 45.13.x.x</b>\nAug 27 21:31:16 srv sshd[9903]: Failed password for admin from 45.13.x.x",
lab:["<code>cat /etc/hostname</code> 으로 짧은 파일을 통째로 본다","<code>less /etc/services</code> 로 긴 파일을 열고, <code>/ssh</code> 로 검색한 뒤 <code>q</code> 로 나온다","<code>head -5 /etc/passwd</code> 와 <code>tail -5 /etc/passwd</code> 를 비교한다","<code>sudo tail -20 /var/log/auth.log</code> 로 최근 인증 기록을 본다","<code>sudo tail -f /var/log/syslog</code> 를 켜두고 다른 창에서 아무 명령이나 실행해본다 (<code>Ctrl+C</code> 로 중단)","<code>wc -l /etc/services</code> 로 그 파일이 몇 줄인지 센다","<code>cat</code> 으로 긴 파일을 열었을 때 어떻게 되는지 한 번 겪어본다 (<code>Ctrl+C</code> 로 중단)"],
q:[{t:"<code>less</code> 로 파일을 열었다. 빠져나오는 키는?",o:["Ctrl+C","Esc","q","Ctrl+Z"],a:2,
  e:"<b><code>q</code></b> 입니다(quit). 리눅스 입문자가 가장 많이 당황하는 순간이고, <code>man</code> 페이지도 같은 방식으로 나옵니다."},
   {t:"수십만 줄짜리 로그에서 <b>가장 최근 기록</b>을 보려면?",o:["cat 파일","head 파일","tail 파일","less 파일"],a:2,
    e:"<b><code>tail</code></b> 입니다. 로그는 <b>새 줄이 뒤에 붙기</b> 때문에 최신이 항상 끝에 있습니다."},
   {k:"cmd",t:"<code>/var/log/auth.log</code> 를 <b>실시간으로 추적</b>하는 명령을 입력하세요.",ph:"tail ...",a:["tail -f /var/log/auth.log"],
    re:["^tail\\s+-f\\s+/var/log/auth\\.log$"],
    hint:"follow 옵션 한 글자입니다.",
    e:"<code>tail -f</code> — 로그를 보면서 실제로 뭔가를 해볼 때 씁니다. 예를 들어 이걸 켜두고 다른 창에서 SSH 로그인을 실패해보면 <b>그 순간 로그가 찍히는 것</b>을 직접 볼 수 있습니다."}]},

{d:5,t:"만들고 옮기고 지우기",g:"파일과 폴더를 다루되, 위험한 명령을 조심하는 법을 배운다.",
c:"<p>이제 파일을 직접 다뤄봅니다.</p><p><b><code>touch 파일</code></b> — 빈 파일 만들기 (이미 있으면 수정 시각만 갱신)<br><b><code>mkdir 폴더</code></b> — 폴더 만들기. <code>mkdir -p a/b/c</code> 는 중간 폴더까지 한 번에<br><b><code>cp 원본 사본</code></b> — 복사. 폴더는 <code>cp -r</code><br><b><code>mv 원본 대상</code></b> — 이동. <b>이름 바꾸기도 <code>mv</code> 로 합니다</b><br><b><code>rm 파일</code></b> — 삭제. 폴더는 <code>rm -r</code></p><p><b>여기서 정말 중요한 경고입니다.</b></p><p><b>리눅스에 휴지통은 없습니다.</b> <code>rm</code> 으로 지우면 <b>즉시 영구 삭제</b>됩니다. 되돌릴 수 없습니다.</p><p>특히 <b><code>rm -rf</code></b> 는 '묻지도 따지지도 않고 폴더째 삭제' 입니다. 여기에 <code>sudo</code> 까지 붙으면 시스템을 통째로 날릴 수 있습니다. 인터넷에서 본 명령을 <b>이해하지 못한 채 복사해 붙여넣지 마세요.</b></p><p>안전 습관: 지우기 전에 <b>같은 경로로 <code>ls</code> 를 먼저 해보세요.</b> <code>rm -rf /tmp/test/*</code> 를 칠 거라면 <code>ls /tmp/test/*</code> 를 먼저 쳐서 무엇이 지워질지 눈으로 확인하는 겁니다. 그리고 <code>rm -i</code> 는 하나하나 물어봅니다.</p>",
term:"hong@server:~$ mkdir -p lab/day5 && cd lab/day5\nhong@server:~/lab/day5$ touch test.txt && ls\ntest.txt\nhong@server:~/lab/day5$ <b>ls</b> *.txt      <b># 지우기 전에 먼저 확인</b>\ntest.txt\nhong@server:~/lab/day5$ rm *.txt",
lab:["홈에 <code>mkdir -p lab/basic</code> 으로 연습 폴더를 만든다","<code>cd lab/basic</code> 으로 들어간다","<code>touch a.txt b.txt c.log</code> 로 파일 세 개를 만든다","<code>cp a.txt a-backup.txt</code> 로 복사하고 <code>ls</code> 로 확인한다","<code>mv b.txt renamed.txt</code> 로 이름을 바꿔본다","<code>ls *.log</code> 를 먼저 실행해 무엇이 지워질지 확인한 뒤 <code>rm *.log</code> 를 실행한다","<code>rm -i a.txt</code> 로 확인을 묻는 삭제를 경험해본다","연습 폴더를 정리한다 (<code>cd ~ && rm -r lab</code>)"],
q:[{t:"리눅스에서 <code>rm</code> 으로 파일을 지웠다. 되돌릴 수 있나?",o:["휴지통에서 복구할 수 있다","즉시 영구 삭제되어 일반적인 방법으로는 복구할 수 없다","24시간 안에는 복구된다","sudo 로 복구할 수 있다"],a:1,
  e:"<b>휴지통이 없습니다.</b> 포렌식 도구로 디스크에서 조각을 찾는 것은 가능하지만, 일상적으로는 <b>지우면 끝</b>이라고 생각해야 합니다."},
   {t:"인터넷에서 본 <code>sudo rm -rf /</code> 같은 명령을 실행하면?",o:["아무 일도 없다","시스템 전체가 삭제되어 복구 불가능해진다","권한 오류가 난다","휴지통으로 이동한다"],a:1,
    e:"<b>시스템이 파괴됩니다.</b> 요즘 배포판은 <code>/</code> 에 대해 한 번 막아주지만 변형은 통합니다. <b>이해하지 못한 명령은 절대 붙여넣지 마세요</b> — 이게 오늘의 핵심입니다."},
   {k:"cmd",t:"<code>report</code> 폴더 안에 <code>2026/08</code> 까지 <b>한 번에</b> 만드는 명령을 입력하세요.",ph:"mkdir ...",a:["mkdir -p report/2026/08"],
    re:["^mkdir\\s+-p\\s+report/2026/08/?$"],
    hint:"부모 폴더까지 만들어주는 옵션이 있습니다.",
    e:"<code>mkdir -p</code> — <code>-p</code> 없이 하면 '중간 폴더가 없다' 며 실패합니다. 스크립트에서 특히 유용합니다."}]},

{d:6,t:"경로 읽고 쓰기",g:"절대경로와 상대경로를 구분해 원하는 곳을 정확히 가리킨다.",
c:"<p>파일을 가리키는 방법이 두 가지입니다. 이걸 헷갈리면 계속 '그런 파일 없다' 는 오류를 봅니다.</p><p><b>절대경로</b> — <code>/</code> 로 시작합니다. <code>/var/log/auth.log</code>. <b>지금 어디 있든 항상 같은 곳</b>을 가리킵니다.</p><p><b>상대경로</b> — <code>/</code> 로 시작하지 않습니다. <code>log/auth.log</code>. <b>지금 위치를 기준</b>으로 찾습니다.</p><p>기호 네 개:<br><b><code>.</code></b> 현재 폴더 · <b><code>..</code></b> 상위 폴더 · <b><code>~</code></b> 내 홈 폴더 · <b><code>/</code></b> 최상위</p><p><code>~/lab</code> 은 <code>/home/hong/lab</code> 과 같고, <code>../config</code> 는 한 단계 위의 config 입니다.</p><p><b>실무 감각:</b> 문서나 스크립트에는 <b>절대경로</b>를 쓰세요. 상대경로는 실행 위치가 바뀌면 깨집니다. cron 같은 곳에서 스크립트가 갑자기 안 도는 원인 1순위가 이것입니다.</p><p><b>Tab 키를 쓰세요.</b> 경로를 절반쯤 치고 Tab 을 누르면 자동완성됩니다. 오타도 막고 훨씬 빠릅니다. 후보가 여러 개면 Tab 을 두 번 눌러 목록을 봅니다.</p>",
term:"hong@server:~$ cd /var/log      <b># 절대경로 — 어디서든 동일</b>\nhong@server:/var/log$ cd ..      <b># 상대경로 — 한 단계 위</b>\nhong@server:/var$ cd ~/lab       <b># ~ 는 내 홈</b>\nhong@server:~/lab$ pwd\n/home/hong/lab",
lab:["<code>cd /var/log</code> 후 <code>pwd</code> 로 절대경로 이동을 확인한다","<code>cd ..</code> 로 한 단계 올라가 <code>pwd</code> 확인","홈으로 돌아와 <code>ls ../</code> 를 실행해 상위 폴더를 본다","<code>cat ~/.bashrc | head -5</code> 로 <code>~</code> 기호를 써본다","<code>echo ~</code> 를 실행해 물결표가 무엇으로 바뀌는지 확인한다","<code>cd /va</code> 까지 치고 <b>Tab</b> 을 눌러 자동완성을 경험한다","<code>ls /e</code> 까지 치고 Tab 을 두 번 눌러 후보 목록을 본다","같은 파일을 절대경로와 상대경로 두 방식으로 각각 <code>cat</code> 해본다"],
q:[{t:"cron 에 등록한 스크립트가 손으로 실행할 때는 되는데 자동 실행에서만 실패한다. 가장 흔한 원인은?",o:["권한 문제","스크립트 안에서 상대경로를 써서 실행 위치가 달라지면 파일을 못 찾기 때문","네트워크 문제","메모리 부족"],a:1,
  e:"cron 은 <b>다른 위치·다른 환경</b>에서 실행합니다. 그래서 스크립트에는 <b>절대경로</b>를 쓰는 것이 원칙입니다."},
   {t:"<code>~</code> 기호가 의미하는 것은?",o:["최상위 디렉터리","현재 사용자의 홈 디렉터리","이전 디렉터리","임시 디렉터리"],a:1,
    e:"<b>홈 디렉터리</b>입니다. <code>hong</code> 이라면 <code>/home/hong</code>. root 라면 <code>/root</code> 입니다."}]},

{d:7,t:"모르면 물어본다",g:"명령어 사용법을 스스로 찾아내는 힘을 기른다.",
c:"<p>명령어와 옵션을 전부 외울 필요 없습니다. <b>찾는 법만 알면</b> 됩니다. 실무자들도 매일 찾아봅니다.</p><p><b><code>명령 --help</code></b> — 가장 빠릅니다. 옵션 목록이 짧게 나옵니다.<br><b><code>man 명령</code></b> — 정식 설명서(manual). 자세하지만 깁니다. <code>less</code> 처럼 <b><code>q</code> 로 나오고 <code>/단어</code> 로 검색</b>합니다.<br><b><code>type 명령</code></b> / <b><code>which 명령</code></b> — 그 명령이 어디 있는 프로그램인지.<br><b><code>apropos 키워드</code></b> — 뭘 써야 할지 모를 때 키워드로 검색.</p><p><b>man 페이지 읽는 요령.</b> 처음부터 읽지 마세요. <b>맨 아래 <code>EXAMPLES</code> 를 먼저 보고</b>(<code>G</code> 로 끝으로 이동), 필요한 옵션만 <code>/</code> 로 검색하는 것이 실전입니다.</p><p>더 친절한 대안으로 <b><code>tldr</code></b> 이 있습니다. man 이 사전이라면 tldr 은 <b>예제 모음</b>입니다. <code>tldr tar</code> 하면 자주 쓰는 사용법 다섯 줄이 바로 나옵니다.</p><p><b>오류 메시지도 정보입니다.</b> <code>Permission denied</code> 는 권한, <code>No such file or directory</code> 는 경로 오타, <code>command not found</code> 는 설치 안 됨. 세 개만 구분해도 대부분 스스로 해결됩니다.</p>",
term:"hong@server:~$ ls --help | head -6\nUsage: ls [OPTION]... [FILE]...\n  -a, --all       do not ignore entries starting with .\n  -l              use a long listing format\nhong@server:~$ type ls\nls is aliased to `ls --color=auto'",
lab:["<code>ls --help</code> 를 실행해 옵션 목록을 훑는다","<code>man ls</code> 를 열고 <code>G</code> 로 맨 끝까지 간 뒤 <code>q</code> 로 나온다","<code>man grep</code> 을 열고 <code>/-c</code> 로 검색해 <code>-c</code> 옵션 설명을 찾는다","<code>type cd</code> 와 <code>type ls</code> 를 비교한다 (하나는 셸 내장)","<code>which python3</code> 로 실행 파일 경로를 확인한다","<code>apropos log</code> 로 로그 관련 명령을 검색해본다","<code>tldr</code> 을 설치해본다 (<code>sudo apt install tldr</code> 후 <code>tldr tar</code>)","<code>cat /없는파일</code> 을 실행해 오류 메시지를 읽어본다"],
q:[{t:"<code>Permission denied</code> 오류가 났다. 가장 먼저 시도할 것은?",o:["재부팅","경로를 다시 확인","권한이 필요한 작업인지 확인하고 필요하면 <code>sudo</code> 를 붙인다","패키지를 재설치"],a:2,
  e:"권한 문제입니다. 다만 <b>무조건 sudo 를 붙이는 습관은 위험합니다.</b> 정말 관리자 권한이 필요한 작업인지 먼저 생각하세요."},
   {t:"<code>man</code> 페이지를 실전에서 읽는 요령으로 가장 적절한 것은?",o:["처음부터 끝까지 정독한다","맨 아래 EXAMPLES 를 먼저 보고 필요한 옵션만 검색한다","제목만 본다","건너뛰고 검색엔진을 쓴다"],a:1,
    e:"man 은 <b>사전</b>이지 교과서가 아닙니다. <code>G</code> 로 끝의 예제를 보고 <code>/옵션</code> 으로 필요한 것만 찾는 게 실전입니다."},
   {k:"cmd",t:"<code>tar</code> 명령의 정식 설명서를 여는 명령을 입력하세요.",ph:"...",a:["man tar"],re:["^man\\s+tar$"],
    hint:"manual 의 앞 세 글자입니다.",
    e:"<code>man tar</code> — 나오는 방법은 <code>q</code> 입니다. tar 는 옵션이 악명 높게 많아서 <code>tldr tar</code> 가 오히려 실용적입니다."}]},

{d:8,t:"권한 읽기",g:"<code>-rw-r--r--</code> 같은 기호를 보고 누가 무엇을 할 수 있는지 읽어낸다.",
c:"<p><code>ls -l</code> 을 하면 맨 앞에 <code>-rw-r--r--</code> 같은 것이 나옵니다. 처음엔 암호 같지만 <b>규칙은 아주 단순</b>합니다.</p><p>10칸을 <b>1 + 3 + 3 + 3</b> 으로 끊어 읽습니다.</p><p><code>-</code> <code>rw-</code> <code>r--</code> <code>r--</code><br>① <b>종류</b> — <code>-</code> 일반 파일, <code>d</code> 폴더, <code>l</code> 링크<br>② <b>소유자</b> 권한<br>③ <b>그룹</b> 권한<br>④ <b>나머지 모두</b> 의 권한</p><p>각 3칸은 <b>r</b>(읽기) <b>w</b>(쓰기) <b>x</b>(실행) 순서이고, 없으면 <code>-</code> 입니다.</p><p>그래서 <code>-rw-r--r--</code> 는 <b>'일반 파일, 주인은 읽고 쓰기, 그룹과 나머지는 읽기만'</b> 입니다.</p><p><b>숫자 표기</b>도 같이 씁니다. r=4, w=2, x=1 을 더합니다.<br><code>rw-</code> = 4+2 = <b>6</b> · <code>r--</code> = <b>4</b> · <code>rwx</code> = 4+2+1 = <b>7</b><br>그래서 <code>-rw-r--r--</code> 는 <b>644</b>, <code>-rwxr-xr-x</code> 는 <b>755</b> 입니다.</p><p><b>보안 관점:</b> <code>777</code>(누구나 모든 권한)은 거의 항상 잘못된 설정입니다. 그리고 폴더의 <code>x</code> 는 '실행' 이 아니라 <b>'들어갈 수 있음'</b> 을 뜻합니다.</p>",
term:"hong@server:~$ ls -l\n<b>-rw-r--r--</b> 1 hong hong  1024 Aug 27 note.txt    <b>644</b>\n<b>-rwxr-xr-x</b> 1 hong hong  8192 Aug 27 run.sh      <b>755</b>\n<b>drwx------</b> 2 hong hong  4096 Aug 27 .ssh        <b>700</b>",
lab:["<code>ls -l ~</code> 로 내 홈의 파일 권한을 본다","<code>ls -ld ~/.ssh</code> 로 SSH 폴더 권한을 확인한다 (<code>700</code> 이어야 정상)","<code>ls -l /etc/passwd</code> 와 <code>ls -l /etc/shadow</code> 의 권한을 비교한다","왜 shadow 만 권한이 좁은지 생각해보고 한 줄로 적는다","<code>-rw-rw-r--</code> 를 숫자로 바꿔본다","<code>ls -l /usr/bin/passwd</code> 를 실행해 <code>s</code> 가 보이는지 확인한다","권한 표기 읽는 법을 카드로 만들어 정리한다"],
q:[{t:"<code>-rwxr-xr-x</code> 를 숫자로 표기하면?",o:["644","755","777","700"],a:1,
  e:"<b>755</b> 입니다. rwx=7, r-x=5, r-x=5. 실행 파일의 표준 권한입니다."},
   {t:"<code>/etc/shadow</code> 의 권한이 <code>/etc/passwd</code> 보다 훨씬 좁은 이유는?",o:["파일이 커서","비밀번호 해시가 들어 있어 아무나 읽으면 크래킹 대상이 되기 때문","자주 바뀌어서","시스템 파일이라서"],a:1,
    e:"<code>passwd</code> 는 사용자 조회를 위해 <b>모두 읽기</b>가 필요하지만, 해시는 root 만 봐야 합니다. 그래서 둘을 분리한 것입니다."},
   {t:"폴더에 <code>x</code> 권한이 없으면 어떻게 되나?",o:["파일을 실행할 수 없다","그 폴더 안으로 들어갈 수 없다","폴더를 지울 수 없다","아무 영향 없다"],a:1,
    e:"폴더에서 <code>x</code> 는 <b>'통과·진입'</b> 을 뜻합니다. <code>r</code> 만 있으면 이름 목록은 보이지만 <code>cd</code> 로 들어가지는 못합니다."}]},

{d:9,t:"권한 바꾸기와 sudo",g:"권한을 조정하고, 관리자 권한을 안전하게 쓴다.",
c:"<p>어제 읽었으니 오늘은 바꿉니다.</p><p><b><code>chmod</code></b> — 권한 변경. 두 방식이 있습니다.<br>숫자: <code>chmod 755 run.sh</code><br>기호: <code>chmod +x run.sh</code>(실행 권한 추가), <code>chmod o-r file</code>(others 의 읽기 제거)</p><p><b><code>chown</code></b> — 소유자 변경. <code>sudo chown hong:hong file</code></p><p><b><code>sudo</code></b> — '이 명령만 관리자 권한으로'. 처음 쓸 때 <b>자기 비밀번호</b>를 묻습니다(root 비밀번호가 아닙니다). 한 번 입력하면 몇 분간 다시 묻지 않습니다.</p><p><b>sudo 를 쓰는 태도가 중요합니다.</b><br>① <b>안 되면 일단 sudo 를 붙이는 습관은 위험합니다.</b> 권한 오류에는 이유가 있습니다.<br>② <code>sudo</code> 로 실행한 명령은 <b>전부 로그에 남습니다</b>(<code>/var/log/auth.log</code>). 이건 감시가 아니라 <b>사고가 났을 때 무슨 일이 있었는지 알기 위한 것</b>이고, 이 코스 ACT 1 의 핵심 재료이기도 합니다.<br>③ <code>sudo -l</code> 로 내가 뭘 할 수 있는지 확인할 수 있습니다.</p><p><b>보안 관점:</b> <code>chmod 777</code> 은 '누구나 읽고 쓰고 실행' 이라 거의 항상 잘못입니다. 문제가 안 풀린다고 777 을 주는 건 <b>문 자체를 떼어내는 것</b>과 같습니다.</p>",
term:"hong@server:~$ echo 'echo hello' > run.sh\nhong@server:~$ ./run.sh\nbash: ./run.sh: <b>Permission denied</b>\nhong@server:~$ chmod +x run.sh\nhong@server:~$ ./run.sh\nhello",
lab:["<code>echo 'echo hello' > run.sh</code> 로 간단한 스크립트를 만든다","<code>./run.sh</code> 를 실행해보고 오류를 확인한다","<code>chmod +x run.sh</code> 후 다시 실행해 성공하는 것을 본다","<code>ls -l run.sh</code> 로 권한이 어떻게 바뀌었는지 확인한다","<code>chmod 644 run.sh</code> 로 되돌리고 다시 실행해본다","<code>sudo -l</code> 로 내가 실행 가능한 sudo 명령을 확인한다","<code>sudo whoami</code> 를 실행해 <code>root</code> 가 나오는 것을 본다","<code>sudo grep sudo /var/log/auth.log | tail -5</code> 로 방금 쓴 sudo 가 로그에 남았는지 확인한다"],
q:[{t:"<code>sudo</code> 를 처음 실행할 때 묻는 비밀번호는 누구의 것인가?",o:["root 의 비밀번호","현재 로그인한 내 계정의 비밀번호","시스템 마스터 비밀번호","비밀번호가 필요 없다"],a:1,
  e:"<b>내 비밀번호</b>입니다. sudo 는 '이 사람이 본인이 맞는지' 를 확인할 뿐, root 비밀번호를 아는지 묻는 게 아닙니다. 그래서 root 비밀번호를 아무도 몰라도 운영이 됩니다."},
   {t:"문제가 안 풀려서 <code>chmod 777</code> 을 주는 것이 위험한 이유는?",o:["명령이 느려서","누구나 읽고 쓰고 실행할 수 있게 되어 그 파일이 공격 경로가 되기 때문","되돌릴 수 없어서","로그가 남아서"],a:1,
    e:"777 은 <b>보안 통제를 없애는 것</b>입니다. 웹 서버 폴더가 777 이면 업로드된 파일이 그대로 실행될 수 있습니다. <b>필요한 최소 권한만</b> 주세요."},
   {k:"cmd",t:"<code>backup.sh</code> 파일에 <b>실행 권한을 추가</b>하는 명령을 입력하세요. (기호 방식)",ph:"chmod ...",a:["chmod +x backup.sh"],
    re:["^chmod\\s+(\\+x|u\\+x|a\\+x)\\s+\\S*backup\\.sh$"],
    hint:"실행을 뜻하는 글자를 더합니다.",
    e:"<code>chmod +x backup.sh</code> — 스크립트를 만들면 항상 필요한 단계입니다. <code>chmod 755</code> 로도 됩니다."}]},

{d:10,t:"출력을 파일로 보내기",g:"화면에 나오는 것을 파일에 저장하고, 오류만 따로 담는다.",
c:"<p>명령의 결과를 <b>화면 대신 파일로</b> 보낼 수 있습니다. 조사 결과를 남길 때 필수입니다.</p><p><b><code>&gt;</code></b> — 파일에 저장. <b>기존 내용을 덮어씁니다.</b><br><code>ls -l &gt; list.txt</code></p><p><b><code>&gt;&gt;</code></b> — 파일 끝에 <b>덧붙입니다.</b><br><code>date &gt;&gt; log.txt</code></p><p><b>이 둘의 차이를 꼭 기억하세요.</b> <code>&gt;</code> 를 <code>&gt;&gt;</code> 대신 쓰면 그동안 모은 내용이 한순간에 날아갑니다.</p><p><b>출력에는 두 종류가 있습니다.</b><br><b>표준출력(stdout, 1번)</b> — 정상 결과<br><b>표준오류(stderr, 2번)</b> — 오류 메시지</p><p>둘은 <b>따로 흐릅니다.</b> 그래서 <code>ls /없는폴더 &gt; out.txt</code> 를 해도 오류는 화면에 그대로 뜹니다. 오류까지 담으려면:<br><code>명령 &gt; out.txt 2&gt;&amp;1</code> — 둘 다 한 파일로<br><code>명령 2&gt; err.txt</code> — 오류만 따로<br><b><code>명령 2&gt;/dev/null</code></b> — <b>오류를 버립니다</b></p><p><code>/dev/null</code> 은 <b>넣으면 사라지는 특수 장치</b>입니다. 이 코스에서 <code>find / ... 2&gt;/dev/null</code> 같은 명령이 자주 나오는데, 권한 없는 폴더에서 나는 오류를 지워 결과를 깨끗하게 보려는 것입니다.</p>",
term:"hong@server:~$ ls /nope > out.txt\nls: cannot access '/nope': No such file or directory   <b># 오류는 화면에</b>\nhong@server:~$ ls /nope > out.txt <b>2>&1</b>\nhong@server:~$ cat out.txt\nls: cannot access '/nope': No such file or directory",
lab:["<code>ls -l &gt; list.txt</code> 후 <code>cat list.txt</code> 로 확인한다","<code>date &gt;&gt; list.txt</code> 를 두 번 실행하고 <code>cat</code> 으로 내용이 쌓이는 것을 본다","<code>date &gt; list.txt</code> 를 실행한 뒤 <code>cat</code> 으로 <b>덮어써진 것</b>을 확인한다","<code>ls /없는폴더 &gt; out.txt</code> 를 실행하고 오류가 어디로 가는지 관찰한다","<code>ls /없는폴더 &gt; out.txt 2&gt;&amp;1</code> 로 오류까지 담아본다","<code>ls /없는폴더 2&gt;/dev/null</code> 로 오류를 버려본다","<code>find /etc -name '*.conf' 2&gt;/dev/null | head</code> 를 실행해 깔끔한 결과를 본다"],
q:[{t:"<code>&gt;</code> 와 <code>&gt;&gt;</code> 의 차이는?",o:["차이 없다","<code>&gt;</code> 는 덮어쓰고 <code>&gt;&gt;</code> 는 뒤에 덧붙인다","<code>&gt;&gt;</code> 가 더 빠르다","<code>&gt;&gt;</code> 는 오류만 저장한다"],a:1,
  e:"<b><code>&gt;</code> 는 덮어쓰기</b>입니다. 로그를 모으는 파일에 실수로 <code>&gt;</code> 를 쓰면 그동안의 내용이 사라집니다."},
   {t:"<code>2&gt;/dev/null</code> 이 하는 일은?",o:["결과를 파일로 저장","오류 메시지를 버려서 화면에 안 보이게 함","권한을 무시","명령을 백그라운드로 실행"],a:1,
    e:"<code>2</code> 는 표준오류, <code>/dev/null</code> 은 넣으면 사라지는 곳입니다. <b>권한 없는 폴더의 오류를 걷어내</b> 결과를 읽기 쉽게 만듭니다."},
   {k:"cmd",t:"<code>ls -lah</code> 의 결과를 <code>files.txt</code> 에 <b>덧붙여</b> 저장하는 명령을 입력하세요.",ph:"ls ...",a:["ls -lah >> files.txt"],
    re:["^ls\\s+-[lah]{3}\\s*>>\\s*\\S*files\\.txt$"],
    hint:"덧붙이기 기호는 두 개입니다.",
    e:"<code>ls -lah &gt;&gt; files.txt</code> — 기호가 하나면 덮어씁니다. 조사 기록을 모을 때는 항상 <code>&gt;&gt;</code> 를 쓰세요."}]},

{d:11,t:"파이프 — 명령을 잇는다",g:"이 코스 전체를 관통하는 핵심 개념을 손에 익힌다.",
c:"<p><b>오늘이 ACT 0 에서 가장 중요한 날입니다.</b> 파이프를 이해하면 앞으로 나올 로그 분석이 전부 이해됩니다.</p><p><b>파이프 <code>|</code></b> 는 <b>앞 명령의 결과를 뒤 명령의 입력으로 넘깁니다.</b> 물이 관을 타고 흐르듯 데이터가 흘러갑니다.</p><p><code>cat auth.log | grep 'Failed' | head -5</code></p><p>읽는 법: 파일을 쏟아내고 → 그중 'Failed' 가 있는 줄만 고르고 → 앞 5줄만 본다.</p><p><b>왜 이게 강력한가.</b> 리눅스 명령은 하나하나가 <b>아주 단순한 일 하나만</b> 합니다. 대신 <b>조합이 무한합니다.</b> 도구 20개를 알면 조합은 수천 가지가 됩니다. 이게 유닉스 철학이고, 로그 분석의 전부입니다.</p><p>자주 쓰는 조합 상대:<br><code>| head -20</code> 앞 20줄 · <code>| tail -20</code> 뒤 20줄 · <code>| wc -l</code> 줄 수 세기 · <code>| sort</code> 정렬 · <code>| grep 단어</code> 걸러내기 · <code>| less</code> 스크롤하며 보기</p><p><b>조립 요령 — 한 단계씩 붙이며 확인하세요.</b> 처음부터 5단계를 쓰면 어디서 틀렸는지 못 찾습니다. 실무자들도 <code>| head</code> 를 붙여 중간 결과를 보면서 하나씩 쌓아 올립니다.</p>",
term:"hong@server:~$ cat /etc/passwd | wc -l\n42\nhong@server:~$ cat /etc/passwd | grep bash | head -3\nroot:x:0:0:root:/root:<b>/bin/bash</b>\nhong:x:1000:1000::/home/hong:<b>/bin/bash</b>",
lab:["<code>cat /etc/passwd | wc -l</code> 로 사용자가 몇 명인지 센다","<code>cat /etc/passwd | grep bash</code> 로 bash 를 쓰는 계정만 본다","<code>ls /etc | wc -l</code> 로 설정 파일 개수를 센다","<code>ls /etc | head -20</code> 과 <code>ls /etc | tail -20</code> 을 비교한다","<code>ls /usr/bin | grep python</code> 으로 python 관련 명령을 찾는다","<code>sudo cat /var/log/auth.log | grep 'Failed' | wc -l</code> 로 실패 횟수를 센다","<b>한 단계씩</b> 붙이며 3단계 파이프라인을 직접 만들어본다","<code>ls /etc | sort | head -5</code> 와 <code>ls /etc | head -5 | sort</code> 의 결과 차이를 확인한다"],
q:[{t:"<code>|</code>(파이프)가 하는 일은?",o:["명령을 동시에 실행한다","앞 명령의 출력을 뒤 명령의 입력으로 넘긴다","결과를 파일로 저장한다","오류를 무시한다"],a:1,
  e:"<b>출력 → 입력</b>으로 이어줍니다. 단순한 명령들을 조합해 복잡한 일을 하는 것이 유닉스 방식이고, 로그 분석의 전부입니다."},
   {t:"복잡한 파이프라인을 만들 때 권장되는 방법은?",o:["한 번에 완성해서 실행한다","한 단계씩 붙이면서 중간 결과를 매번 확인한다","항상 sort 를 맨 앞에 둔다","파일로 저장하며 진행한다"],a:1,
    e:"파이프라인은 <b>중간이 안 보입니다.</b> 다 만들고 나면 어디가 틀렸는지 알 수 없으니, <code>| head</code> 를 붙여 확인하며 쌓아 올리세요."},
   {k:"cmd",t:"<code>/etc/passwd</code> 에서 <code>bash</code> 가 포함된 줄이 <b>몇 줄인지</b> 세는 파이프라인을 입력하세요.",
    ph:"cat ... | ... | ...",a:["cat /etc/passwd | grep bash | wc -l"],
    re:["^cat\\s+/etc/passwd\\s*\\|\\s*grep\\s+['\"]?bash['\"]?\\s*\\|\\s*wc\\s+-l$"],
    hint:"쏟아내고 → 거르고 → 센다. 세 단계입니다.",
    e:"<code>cat /etc/passwd | grep bash | wc -l</code> — <code>grep -c bash /etc/passwd</code> 로도 같은 결과가 나옵니다. <b>여러 길이 있다는 것</b>도 리눅스의 특징입니다."}]},

{d:12,t:"찾기",g:"이름·조건으로 파일을 찾아낸다. 침해 조사의 기본 동작.",
c:"<p>파일이 어디 있는지 모를 때 씁니다.</p><p><b><code>find 경로 조건</code></b> — 가장 강력합니다. 실시간으로 뒤지므로 정확하지만 느립니다.<br><code>find /etc -name '*.conf'</code> — /etc 아래 .conf 파일<br><code>find . -type f</code> — 현재 폴더 아래 파일만(<code>d</code> 는 폴더)<br><code>find /var -size +100M</code> — 100MB 넘는 파일<br><code>find /home -mtime -1</code> — <b>최근 1일 안에 수정된 것</b></p><p><b><code>which 명령</code></b> — 그 명령의 실행 파일 위치.<br><b><code>locate 이름</code></b> — 미리 만든 색인에서 빠르게 검색(<code>sudo updatedb</code> 로 갱신).</p><p><b>보안에서 왜 중요한가.</b> 침해 조사에서 가장 자주 하는 질문이 <b>'최근에 바뀐 파일이 뭐냐'</b> 입니다. 공격자가 침입한 시각 이후 만들어지거나 수정된 파일을 찾으면 <b>범위가 확 좁혀집니다.</b></p><p><code>find /var/www -type f -mtime -1</code> — 웹 폴더에서 하루 안에 바뀐 파일. <b>웹셸을 찾는 가장 빠른 방법</b>입니다.</p><p>오류가 많이 나면 <code>2&gt;/dev/null</code> 을 붙이세요(어제 배운 것).</p>",
term:"hong@server:~$ find /etc -name '*.conf' 2>/dev/null | head -5\n/etc/ld.so.conf\n/etc/rsyslog.conf\nhong@server:~$ find /tmp -type f -mtime -1 2>/dev/null\n/tmp/.x/kworker      <b># 최근 생긴 수상한 파일</b>",
lab:["<code>find /etc -name '*.conf' 2&gt;/dev/null | head</code> 를 실행한다","<code>find ~ -type f | wc -l</code> 로 홈에 파일이 몇 개인지 센다","<code>find ~ -type d | head</code> 로 폴더만 찾아본다","<code>find /tmp -type f -mtime -1 2&gt;/dev/null</code> 로 최근 하루 안에 생긴 임시 파일을 본다","<code>which ls</code> 와 <code>which python3</code> 를 실행한다","<code>find / -name 'auth.log' 2&gt;/dev/null</code> 로 로그 파일 위치를 찾아본다","<code>find ~ -size +1M 2&gt;/dev/null</code> 로 큰 파일을 찾는다","'침해 시각 이후 변경된 파일 찾기' 명령을 자기 치트시트에 적어둔다"],
q:[{t:"웹서버가 해킹된 것 같다. 업로드된 웹셸을 가장 빠르게 찾는 방법은?",o:["모든 파일을 하나씩 열어본다","<code>find /var/www -type f -mtime -1</code> 로 최근 변경된 파일을 찾는다","서버를 재부팅한다","백신을 돌린다"],a:1,
  e:"<b>시간축으로 범위를 좁히는 것</b>이 조사의 기본입니다. 파일 수만 개 중 최근 하루에 바뀐 것은 몇 개 안 되고, 거기서 시작하면 됩니다."},
   {t:"<code>find</code> 에서 <code>-type f</code> 와 <code>-type d</code> 의 차이는?",o:["파일 크기 기준","f 는 일반 파일, d 는 디렉터리","f 는 빠른 검색","차이 없다"],a:1,
    e:"<b>file</b> 과 <b>directory</b> 입니다. 지정하지 않으면 둘 다 나와서 결과가 지저분해집니다."},
   {k:"cmd",t:"<code>/var/www</code> 아래에서 <b>최근 1일 이내에 수정된 파일</b>을 찾는 명령을 입력하세요.",
    ph:"find ...",a:["find /var/www -type f -mtime -1"],
    re:["^find\\s+/var/www\\s+.*-mtime\\s+-1"],
    hint:"수정 시각 조건은 mtime 이고, '1일 이내' 는 마이너스입니다.",
    e:"<code>find /var/www -type f -mtime -1</code> — <code>-1</code> 은 '1일 이내', <code>+1</code> 은 '1일보다 오래된' 입니다. 부호를 헷갈리기 쉬우니 주의하세요."}]},

{d:13,t:"파일 편집",g:"서버에서 설정 파일을 열어 고치고 저장할 수 있게 된다.",
c:"<p>서버에는 메모장이 없습니다. 터미널에서 편집해야 합니다.</p><p><b><code>nano</code></b> — <b>초보자는 이걸 쓰세요.</b> 화면 아래에 단축키가 계속 표시됩니다.<br><code>nano 파일명</code> 으로 열고, 그냥 타이핑하면 됩니다.<br>저장: <b><code>Ctrl+O</code></b> → Enter · 종료: <b><code>Ctrl+X</code></b><br>(<code>^O</code> 표기의 <code>^</code> 는 Ctrl 을 뜻합니다)</p><p><b><code>vim</code></b> — 강력하지만 처음엔 어렵습니다. 다만 <b>어느 서버에나 있어서</b> 최소한 빠져나오는 법은 알아야 합니다.<br><code>i</code> 입력 모드 진입 → 편집 → <code>Esc</code> → <b><code>:wq</code></b> 저장 후 종료 · <b><code>:q!</code></b> 저장 안 하고 종료</p><p><b><code>:q!</code> 하나만은 꼭 외우세요.</b> 실수로 vim 에 들어갔을 때 탈출하는 방법입니다.</p><p><b>서버에서 설정 파일을 고칠 때 지킬 것:</b><br>① <b>먼저 백업</b> — <code>sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak</code><br>② 고친다<br>③ <b>문법 검증</b> — 서비스마다 검증 명령이 있습니다(<code>sshd -t</code>, <code>nginx -t</code>)<br>④ 재시작</p><p><b>②만 하고 ④로 건너뛰다 서버에 못 들어가게 되는 사고</b>가 정말 흔합니다. SSH 설정이 특히 그렇습니다.</p>",
term:"hong@server:~$ nano note.txt\n\n  GNU nano 7.2          note.txt\n  안녕하세요█\n\n<b>^O</b> Write Out   <b>^X</b> Exit   ^W Where Is",
lab:["<code>nano note.txt</code> 로 파일을 만들고 아무 내용이나 쓴다","<code>Ctrl+O</code> → Enter 로 저장하고 <code>Ctrl+X</code> 로 나온다","<code>cat note.txt</code> 로 저장된 것을 확인한다","<code>nano note.txt</code> 로 다시 열어 내용을 수정하고 저장한다","<code>vim note.txt</code> 로 열어보고 <b><code>:q!</code></b> 로 빠져나온다","vim 에서 <code>i</code> → 글자 입력 → <code>Esc</code> → <code>:wq</code> 를 한 번 해본다","<code>cp note.txt note.txt.bak</code> 으로 백업하는 습관을 연습한다","'설정 고치기 4단계'(백업→수정→검증→재시작)를 적어둔다"],
q:[{t:"실수로 vim 에 들어갔다. 아무것도 저장하지 않고 나오는 방법은?",o:["Ctrl+C","Ctrl+X","<code>:q!</code> 입력 후 Enter","Esc 두 번"],a:2,
  e:"<b><code>:q!</code></b> 입니다. <code>Esc</code> 를 먼저 눌러 명령 모드로 간 뒤 입력합니다. 이것만 알아도 vim 앞에서 당황하지 않습니다."},
   {t:"SSH 설정 파일을 고친 뒤 재시작하기 전에 반드시 해야 할 일은?",o:["서버 재부팅","<code>sudo sshd -t</code> 로 문법을 검증한다","백신 검사","로그 삭제"],a:1,
    e:"설정에 오타가 있으면 <b>SSH 서비스가 안 뜨고, 원격 서버라면 다시는 못 들어갑니다.</b> 검증 명령은 이런 사고를 막는 안전장치입니다."}]},

{d:14,t:"프로세스 — 지금 뭐가 돌고 있나",g:"실행 중인 프로그램을 확인하고 필요하면 멈춘다.",
c:"<p><b>프로세스</b>는 <b>지금 실행 중인 프로그램</b>입니다. 각각 <b>PID</b>(번호)를 갖습니다.</p><p><b><code>ps aux</code></b> — 전체 프로세스 목록. 열 순서는 <b>사용자 · PID · CPU% · MEM% · … · 명령</b> 입니다.<br><b><code>ps auxf</code></b> — <b>트리 모양으로</b> 보여줍니다. <b><code>f</code> 하나가 결정적입니다</b> — 누가 누구를 실행했는지 보이거든요.<br><b><code>top</code></b> / <b><code>htop</code></b> — 실시간 모니터. <code>q</code> 로 나옵니다.<br><b><code>kill PID</code></b> — 종료 요청. 안 죽으면 <code>kill -9 PID</code>(강제).</p><p><b>보안에서 왜 중요한가.</b> 프로세스 <b>부모-자식 관계</b>가 침해 탐지의 핵심입니다.</p><p>웹서버(<code>nginx</code>) 아래에 <code>bash</code> 가 붙어 있다면? 웹서버가 셸을 실행할 이유는 없습니다. <b>그건 웹셸입니다.</b> 이 아이디어가 ACT 1·3 에서 계속 나옵니다.</p><p>그리고 <b>이름을 믿지 마세요.</b> <code>ps aux</code> 에 <code>svchost</code> 라고 떠도 실제 경로가 <code>/tmp/svchost</code> 라면 위장입니다. <b>경로까지 확인</b>하는 습관을 들이세요.</p>",
term:"hong@server:~$ ps auxf | head -8\nroot     1024  nginx: master process\nwww-data 1025   \\_ nginx: worker process\nwww-data 8811   <b>\\_ /bin/bash -i</b>          <b># 웹서버가 셸을?</b>\nwww-data 8812       <b>\\_ nc 45.13.x.x 4444</b>",
lab:["<code>ps aux | head -20</code> 으로 프로세스 목록을 본다","<code>ps auxf | less</code> 로 <b>트리 구조</b>를 보고 부모-자식 관계를 눈에 익힌다","<code>ps aux | wc -l</code> 로 몇 개가 돌고 있는지 센다","<code>top</code> 을 실행해 실시간 화면을 보고 <code>q</code> 로 나온다","<code>sleep 300 &amp;</code> 로 백그라운드 프로세스를 하나 띄운다","<code>ps aux | grep sleep</code> 으로 그 프로세스를 찾아 PID 를 확인한다","<code>kill &lt;그 PID&gt;</code> 로 종료하고 사라졌는지 확인한다","<code>ps aux --sort=-%cpu | head -5</code> 로 CPU 를 많이 쓰는 순으로 본다"],
q:[{t:"<code>ps auxf</code> 에서 웹서버(nginx) 아래에 <code>/bin/bash</code> 가 자식으로 보인다. 가장 유력한 해석은?",o:["정상적인 설정 스크립트","웹 취약점으로 셸이 실행된 웹셸 상황","로그 로테이션 중","시스템 업데이트 중"],a:1,
  e:"웹서버는 셸을 낳을 이유가 없습니다. <b>부모-자식 관계의 이상</b>이 침해 탐지의 핵심 아이디어이고, 이 코스 내내 반복해서 나옵니다."},
   {t:"<code>ps aux</code> 에 익숙한 이름의 프로세스가 보인다. 무엇을 더 확인해야 하나?",o:["더 볼 것 없다","실행 파일의 <b>경로</b> — /tmp 같은 곳이면 이름을 훔친 위장이다","CPU 사용량","시작 시각"],a:1,
    e:"<b>이름은 아무거나 붙일 수 있습니다.</b> 정상 시스템 프로세스는 <code>/usr/sbin</code> 같은 정해진 곳에 있습니다. 경로가 <code>/tmp</code> 면 그 자체로 악성입니다."},
   {k:"cmd",t:"프로세스를 <b>트리 형태</b>로 전부 보는 명령을 입력하세요.",ph:"ps ...",a:["ps auxf"],
    re:["^ps\\s+auxf$|^ps\\s+-auxf$"],
    hint:"ps aux 에 forest 를 뜻하는 글자 하나를 더합니다.",
    e:"<code>ps auxf</code> — <code>f</code> 가 forest(트리)입니다. 이 한 글자가 '누가 누구를 실행했는가' 를 보여주고, 그게 침해를 드러냅니다."}]},

{d:15,t:"프로그램 설치하기",g:"필요한 도구를 직접 설치할 수 있게 된다.",
c:"<p>이 코스에서 앞으로 수십 개의 도구를 설치합니다. 오늘 그 방법을 익힙니다.</p><p>리눅스는 <b>패키지 관리자</b>로 프로그램을 설치합니다. 웹에서 파일을 받아 실행하는 게 아니라, <b>공식 저장소에서 검증된 것을 가져옵니다.</b></p><p><b>데비안·우분투 계열</b> (<code>apt</code>):<br><code>sudo apt update</code> — <b>목록 갱신. 설치 전에 먼저 하세요</b><br><code>sudo apt install 패키지</code> — 설치<br><code>sudo apt remove 패키지</code> — 제거<br><code>apt search 키워드</code> — 검색<br><code>apt list --installed</code> — 설치된 것 목록</p><p><b>RHEL·CentOS·Rocky 계열</b>은 <code>dnf</code>(또는 <code>yum</code>)를 씁니다. <code>sudo dnf install 패키지</code>.</p><p><b><code>apt update</code> 를 먼저 하는 이유:</b> 내 컴퓨터가 가진 <b>패키지 목록이 낡았으면</b> 설치가 실패하거나 옛 버전이 깔립니다. <code>update</code> 는 목록 갱신, <code>upgrade</code> 는 실제 업그레이드 — <b>둘은 다릅니다.</b></p><p><b>보안 관점:</b> 인터넷에서 <code>curl ... | sudo bash</code> 로 설치하라는 안내를 자주 봅니다. 이건 <b>남이 만든 스크립트를 확인 없이 root 로 실행</b>하는 것입니다. 편하지만 위험하고, 실제 공급망 공격 경로입니다. 가능하면 공식 저장소를 쓰고, 꼭 써야 한다면 <b>스크립트를 먼저 받아서 읽어보세요.</b></p>",
term:"hong@server:~$ sudo apt update\nGet:1 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]\nhong@server:~$ sudo apt install -y tree jq\nSetting up tree ... Setting up jq ...\nhong@server:~$ tree -L 1 /var\n/var\n├── log\n└── tmp",
lab:["<code>sudo apt update</code> 를 실행한다","<code>sudo apt install -y tree jq</code> 로 도구 두 개를 설치한다","<code>tree -L 2 /etc | head -30</code> 으로 폴더 구조를 그림으로 본다","<code>apt search wireshark | head</code> 로 패키지를 검색해본다","<code>apt list --installed | wc -l</code> 로 설치된 패키지 수를 센다","<code>which tree</code> 로 설치된 위치를 확인한다","<code>curl ... | sudo bash</code> 방식이 왜 위험한지 3줄로 적어본다","앞으로 설치할 도구 목록을 미리 메모해둔다"],
q:[{t:"<code>apt update</code> 와 <code>apt upgrade</code> 의 차이는?",o:["같은 명령이다","update 는 패키지 목록만 갱신하고, upgrade 는 실제로 프로그램을 새 버전으로 올린다","update 가 더 위험하다","upgrade 는 삭제한다"],a:1,
  e:"<b>update = 목록 갱신</b>, <b>upgrade = 실제 설치</b>입니다. 설치 전에 <code>update</code> 를 안 하면 '패키지를 찾을 수 없다' 는 오류가 자주 납니다."},
   {t:"<code>curl https://어딘가/install.sh | sudo bash</code> 방식이 위험한 이유는?",o:["느려서","내용을 확인하지 않은 남의 스크립트를 root 권한으로 실행하는 것이라, 사이트가 침해되면 그대로 당하기 때문","용량이 커서","인터넷이 필요해서"],a:1,
    e:"실제 공급망 공격 경로입니다. <b>최소한 <code>curl -o install.sh ... && less install.sh</code> 로 읽어보고</b> 실행하세요."},
   {k:"cmd",t:"패키지 목록을 갱신하는 명령을 입력하세요. (우분투 기준)",ph:"...",a:["sudo apt update"],
    re:["^apt(-get)?\\s+update$"],
    hint:"관리자 권한이 필요하고, 갱신을 뜻하는 단어입니다.",
    e:"<code>sudo apt update</code> — 설치 작업의 <b>거의 항상 첫 단계</b>입니다."}]},

{d:16,t:"서비스 다루기",g:"백그라운드에서 도는 프로그램을 시작·중지·확인한다.",
c:"<p>웹서버·SSH·데이터베이스처럼 <b>계속 떠 있어야 하는 프로그램</b>을 <b>서비스</b>(데몬)라고 합니다. 요즘 리눅스는 <code>systemd</code> 가 관리합니다.</p><p><b><code>systemctl status 서비스</code></b> — 상태 확인. <b>가장 많이 씁니다</b><br><b><code>systemctl start / stop / restart 서비스</code></b> — 시작·중지·재시작<br><b><code>systemctl enable / disable 서비스</code></b> — <b>부팅 시 자동 시작</b> 여부<br><b><code>systemctl list-units --type=service</code></b> — 돌고 있는 서비스 목록</p><p><b><code>start</code> 와 <code>enable</code> 은 다릅니다.</b> <code>start</code> 는 <b>지금</b> 켜는 것이고 <code>enable</code> 은 <b>다음 부팅에도</b> 켜지게 하는 것입니다. 둘 다 필요하면 <code>systemctl enable --now 서비스</code>.</p><p><b>보안 관점 두 가지.</b></p><p>① <b>안 쓰는 서비스는 끄세요.</b> 돌고 있는 서비스 하나하나가 공격 표면입니다. <code>list-units</code> 로 훑어보고 정체를 모르는 게 있으면 조사하세요.</p><p>② <b>공격자는 서비스로 지속성을 확보합니다.</b> 악성 프로그램을 서비스로 등록해두면 <b>재부팅해도 살아납니다.</b> 그래서 조사할 때 <code>systemctl list-unit-files --state=enabled</code> 로 자동 시작 목록을 확인합니다. 이 이야기가 ACT 1 에서 본격적으로 나옵니다.</p>",
term:"hong@server:~$ systemctl status ssh\n● ssh.service - OpenBSD Secure Shell server\n     Loaded: loaded (/lib/systemd/system/ssh.service; <b>enabled</b>)\n     Active: <b>active (running)</b> since Thu 21:30:02 KST\n       Main PID: 812 (sshd)",
lab:["<code>systemctl status ssh</code> 로 SSH 서비스 상태를 본다 (<code>q</code> 로 나옴)","<code>systemctl list-units --type=service --state=running | head -20</code> 으로 돌고 있는 서비스를 훑는다","<code>systemctl list-unit-files --state=enabled | head -20</code> 으로 자동 시작 목록을 본다","정체를 모르는 서비스 이름 하나를 골라 검색해본다","<code>systemctl is-active ssh</code> 와 <code>systemctl is-enabled ssh</code> 를 실행해 차이를 본다","<code>systemctl --failed</code> 로 실패한 서비스가 있는지 확인한다","'start 와 enable 의 차이' 를 자기 말로 한 줄 적는다","자동 시작 목록을 파일로 저장해 <b>기준선</b>으로 남긴다"],
q:[{t:"<code>systemctl start</code> 와 <code>systemctl enable</code> 의 차이는?",o:["같다","start 는 지금 실행, enable 은 부팅 시 자동 실행 설정","enable 이 더 빠르다","start 는 임시 계정으로 실행"],a:1,
  e:"<b>지금 vs 다음 부팅부터</b>입니다. 서비스를 켰는데 재부팅하면 꺼져 있다면 <code>enable</code> 을 안 한 것입니다."},
   {t:"침해 조사에서 <code>systemctl list-unit-files --state=enabled</code> 를 확인하는 이유는?",o:["성능 점검","공격자가 악성 프로그램을 서비스로 등록해 재부팅 후에도 살아남게 만들 수 있기 때문","용량 확인","네트워크 점검"],a:1,
    e:"<b>지속성(persistence)</b> 점검입니다. 서비스 등록은 공격자가 가장 즐겨 쓰는 방법 중 하나이고, ACT 1 에서 자세히 다룹니다."}]},

{d:17,t:"네트워크 기본기",g:"IP 를 확인하고 연결을 테스트하고 웹 요청을 보낸다.",
c:"<p>보안 일은 네트워크와 뗄 수 없습니다. 기본 도구 넷만 익힙니다.</p><p><b><code>ip a</code></b> — 내 IP 주소 확인 (예전 <code>ifconfig</code> 의 후계)<br><b><code>ping 대상</code></b> — 상대가 살아있는지. <code>Ctrl+C</code> 로 중단, <code>ping -c 4</code> 로 4번만<br><b><code>curl URL</code></b> — 웹 요청을 보내고 응답을 받습니다<br><b><code>dig 도메인</code></b> — 도메인이 어느 IP 인지 (DNS 조회)</p><p><b><code>curl</code> 이 특히 유용합니다.</b><br><code>curl -I https://example.com</code> — <b>헤더만</b> 받기<br><code>curl -s URL</code> — 진행 표시 없이 조용히<br><code>curl -o out.html URL</code> — 파일로 저장<br><code>curl -A '이름' URL</code> — <b>User-Agent 바꾸기</b></p><p>마지막 것이 흥미롭습니다. 서버는 <b>누가 요청했는지를 User-Agent 헤더로 판단</b>하는데, 이건 <b>얼마든지 위조할 수 있습니다.</b> 그래서 웹 로그의 User-Agent 를 그대로 믿으면 안 되고, 반대로 <code>sqlmap</code> 같은 값이 보이면 <b>숨길 생각조차 없는 자동화 공격</b>이라는 뜻입니다.</p><p><b>포트</b> 개념도 잡고 갑시다. IP 가 건물 주소라면 포트는 <b>몇 호실</b>인지입니다. 22=SSH, 80=HTTP, 443=HTTPS, 53=DNS, 3389=RDP. 이 다섯 개는 지금 외워두세요.</p>",
term:"hong@server:~$ curl -I https://example.com\nHTTP/2 200\ncontent-type: text/html; charset=UTF-8\nhong@server:~$ dig +short example.com\n93.184.215.14",
lab:["<code>ip a</code> 로 내 IP 주소를 확인한다","<code>ping -c 4 8.8.8.8</code> 로 인터넷 연결을 테스트한다","<code>ping -c 4 google.com</code> 으로 도메인도 되는지 확인한다 (DNS 가 동작한다는 뜻)","<code>curl -I https://example.com</code> 로 응답 헤더를 본다","<code>curl -s https://example.com | head -20</code> 으로 HTML 을 받아본다","<code>dig +short google.com</code> 으로 IP 를 조회한다","<code>curl -A 'sqlmap/1.7' -I https://example.com</code> 로 User-Agent 를 바꿔 보낸다","포트 5개(22·80·443·53·3389)를 카드로 만들어 외운다"],
q:[{t:"웹 로그의 User-Agent 를 그대로 믿으면 안 되는 이유는?",o:["암호화되어서","클라이언트가 보내는 값이라 얼마든지 위조할 수 있기 때문","서버가 지워서","너무 길어서"],a:1,
  e:"<code>curl -A</code> 한 줄로 바뀝니다. 다만 <b>위조하지 않은 경우</b>도 많아서, <code>sqlmap</code> 같은 값이 보이면 그건 그것대로 유용한 신호입니다."},
   {t:"SSH 의 기본 포트 번호는?",o:["21","22","23","25"],a:1,
    e:"<b>22</b> 입니다. 21=FTP, 23=Telnet, 25=SMTP. 이 코스에서 22번 포트 이야기가 계속 나옵니다."},
   {k:"cmd",t:"<code>example.com</code> 의 <b>응답 헤더만</b> 받아오는 명령을 입력하세요.",ph:"curl ...",a:["curl -I https://example.com"],
    re:["^curl\\s+-I\\s+https?://example\\.com/?$"],
    hint:"head 를 뜻하는 대문자 옵션입니다.",
    e:"<code>curl -I</code> — 본문 없이 헤더만 받습니다. 서버 종류·리다이렉션·보안 헤더를 빠르게 확인할 때 씁니다."}]},

{d:18,t:"압축과 파일 전송",g:"증거를 묶어서 안전하게 옮긴다.",
c:"<p>침해 조사에서 <b>로그를 묶어 반출</b>하는 일이 자주 있습니다. 그 방법입니다.</p><p><b><code>tar</code></b> — 여러 파일을 하나로 묶습니다. 옵션이 악명 높은데, <b>두 조합만</b> 외우면 됩니다.<br><b>묶기:</b> <code>tar czf 결과.tar.gz 대상폴더</code><br><b>풀기:</b> <code>tar xzf 파일.tar.gz</code><br>(<code>c</code>=create, <code>x</code>=extract, <code>z</code>=gzip 압축, <code>f</code>=파일 지정)<br>내용만 보려면 <code>tar tzf 파일.tar.gz</code></p><p><b><code>gzip</code> / <code>gunzip</code></b> — 파일 하나를 압축·해제. <b>로그 파일이 <code>.gz</code> 로 되어 있는 이유</b>가 이것입니다.</p><p><b><code>zcat</code>, <code>zgrep</code></b> — <b>압축을 풀지 않고</b> 바로 읽고 검색합니다. <code>zgrep 'Failed' auth.log.2.gz</code>. <b>오래된 로그를 뒤질 때 필수</b>입니다.</p><p><b><code>scp</code></b> — 서버 간 파일 복사.<br><code>scp 파일 사용자@서버:/경로</code> — 보내기<br><code>scp 사용자@서버:/경로/파일 .</code> — 가져오기</p><p><b>증거를 옮길 때는 해시를 함께 남기세요.</b><br><code>sha256sum evidence.tar.gz &gt; evidence.sha256</code><br>이러면 나중에 <b>파일이 바뀌지 않았음을 증명</b>할 수 있습니다. ACT 5 에서 이게 왜 중요한지 자세히 다룹니다.</p>",
term:"hong@server:~$ sudo tar czf logs.tar.gz /var/log/auth.log*\nhong@server:~$ ls -lh logs.tar.gz\n-rw-r--r-- 1 root root <b>2.1M</b> Aug 27 21:40 logs.tar.gz\nhong@server:~$ sha256sum logs.tar.gz > logs.sha256",
lab:["연습용 폴더를 만들고 파일 몇 개를 넣는다","<code>tar czf backup.tar.gz 폴더명</code> 으로 묶는다","<code>ls -lh backup.tar.gz</code> 로 크기를 확인한다","<code>tar tzf backup.tar.gz</code> 로 <b>풀지 않고</b> 내용을 본다","<code>mkdir restore &amp;&amp; tar xzf backup.tar.gz -C restore</code> 로 풀어본다","<code>sudo zgrep 'Failed' /var/log/auth.log.*.gz 2&gt;/dev/null | head</code> 로 압축 로그를 검색한다","<code>sha256sum backup.tar.gz</code> 로 해시를 뽑아 파일에 저장한다","<code>sha256sum -c</code> 로 무결성을 검증해본다"],
q:[{t:"압축된 로그 <code>auth.log.2.gz</code> 에서 문자열을 찾는 가장 편한 방법은?",o:["먼저 gunzip 으로 푼다","<code>zgrep</code> 으로 압축을 푸는 것 없이 바로 검색한다","cat 으로 연다","불가능하다"],a:1,
  e:"<b><code>zgrep</code></b> 입니다. 로테이션된 오래된 로그가 전부 <code>.gz</code> 라, 과거를 조사할 때 반드시 쓰게 됩니다."},
   {t:"증거 파일을 옮길 때 해시를 함께 남기는 이유는?",o:["용량을 줄이려고","전송·보관 중에 파일이 변경되지 않았음을 나중에 증명하기 위해","압축률을 높이려고","권한을 유지하려고"],a:1,
    e:"<b>무결성 증명</b>입니다. 해시가 같으면 '조사 과정에서 손대지 않았다' 를 입증할 수 있고, 이게 증거의 신뢰를 만듭니다."},
   {k:"cmd",t:"<code>logs</code> 폴더를 <code>logs.tar.gz</code> 로 압축하는 명령을 입력하세요.",ph:"tar ...",a:["tar czf logs.tar.gz logs"],
    re:["^tar\\s+-?czf\\s+\\S*logs\\.tar\\.gz\\s+\\S*logs/?$"],
    hint:"create · gzip · file 세 글자를 붙여 씁니다.",
    e:"<code>tar czf logs.tar.gz logs</code> — 풀 때는 <code>c</code> 대신 <code>x</code>(<code>tar xzf</code>). <b>이 두 줄만 외우면</b> tar 의 90% 는 해결됩니다."}]},

{d:19,t:"셸 스크립트 첫걸음",g:"반복하는 명령을 파일로 묶어 자동화한다.",
c:"<p>같은 명령을 매번 치는 대신 <b>파일에 적어두고 실행</b>할 수 있습니다. 그게 셸 스크립트입니다.</p><p><b>기본 형태:</b></p><p><code>#!/bin/bash</code><br><code># 로그 요약 스크립트</code><br><code>echo \"=== 실패한 로그인 ===\"</code><br><code>grep 'Failed password' /var/log/auth.log | wc -l</code></p><p>첫 줄 <b><code>#!/bin/bash</code></b> 를 <b>셔뱅(shebang)</b> 이라고 합니다. '이 파일을 bash 로 실행하라' 는 표시이고, <b>반드시 첫 줄이어야</b> 합니다.</p><p><b>실행 방법:</b> <code>chmod +x script.sh</code> 로 실행 권한을 주고 <code>./script.sh</code>. (Day 9 에서 배운 것입니다)</p><p><b>변수</b>는 <code>=</code> 앞뒤에 <b>공백 없이</b> 씁니다. <code>NAME=\"hong\"</code>. 쓸 때는 <code>$NAME</code> 또는 <code>\"${NAME}\"</code>.</p><p><b>실무 감각 하나.</b> 변수를 쓸 때는 <b>큰따옴표로 감싸세요.</b> <code>\"$FILE\"</code>. 파일 이름에 공백이 있으면 따옴표 없이는 두 개로 쪼개져서, 엉뚱한 파일이 지워지는 사고가 납니다.</p><p><b>보안 관점:</b> 공격자도 스크립트를 씁니다. cron 에 등록된 스크립트, <code>/tmp</code> 의 <code>.sh</code> 파일을 조사 때 반드시 열어보세요. 그리고 여러분이 만든 스크립트가 <b>남이 수정할 수 있는 권한</b>이면 그게 백도어가 됩니다.</p>",
term:"hong@server:~$ cat check.sh\n#!/bin/bash\necho \"=== 실패한 로그인 ===\"\ngrep -c 'Failed password' /var/log/auth.log\nhong@server:~$ chmod +x check.sh && ./check.sh\n=== 실패한 로그인 ===\n<b>1847</b>",
lab:["<code>nano check.sh</code> 로 파일을 만들고 셔뱅을 첫 줄에 쓴다","<code>echo</code> 와 <code>date</code> 를 넣어 간단한 스크립트를 완성한다","<code>chmod +x check.sh</code> 후 <code>./check.sh</code> 로 실행한다","변수를 하나 만들어 써본다 (<code>NAME=\"hong\"</code> 후 <code>echo \"안녕 $NAME\"</code>)","<code>=</code> 앞뒤에 공백을 넣어보고 오류가 나는 것을 확인한다","로그 요약 스크립트를 만들어본다 (실패 횟수 + 현재 시각)","<code>bash -n check.sh</code> 로 문법만 검사해본다","셔뱅을 빼고 실행하면 어떻게 되는지 확인해본다"],
q:[{t:"셸 스크립트 첫 줄의 <code>#!/bin/bash</code> 를 무엇이라 하나?",o:["주석","셔뱅(shebang)","헤더","매직 넘버"],a:1,
  e:"<b>셔뱅</b>입니다. 이 파일을 어떤 프로그램으로 해석할지 알려줍니다. <code>#!/usr/bin/env python3</code> 처럼 파이썬 스크립트에도 씁니다."},
   {t:"스크립트에서 변수를 <code>\"$FILE\"</code> 처럼 큰따옴표로 감싸는 이유는?",o:["가독성","파일 이름에 공백이 있을 때 여러 개로 쪼개지는 것을 막기 위해","속도","문법상 필수라서"],a:1,
    e:"<code>rm $FILE</code> 에서 FILE 이 <code>my file.txt</code> 라면 <code>my</code> 와 <code>file.txt</code> 두 개를 지우려 합니다. <b>실제로 사고가 나는 지점</b>입니다."},
   {t:"침해 조사에서 <code>/tmp</code> 의 <code>.sh</code> 파일을 반드시 열어봐야 하는 이유는?",o:["용량이 커서","공격자가 자동화·지속성 용도로 스크립트를 떨궈두는 흔한 장소이기 때문","시스템 파일이라서","권한이 없어서"],a:1,
    e:"<code>/tmp</code> 는 누구나 쓸 수 있고 재부팅하면 지워집니다. <b>공격자의 작업 폴더</b>가 되기 딱 좋습니다."}]},

{d:20,t:"[기초 졸업] 로그 앞에 서기",g:"배운 것을 전부 이어 붙여, 내일부터 시작할 로그 분석을 미리 맛본다.",boss:true,
c:"<p><b>기초 20일을 마쳤습니다.</b> 오늘은 배운 것을 전부 이어서, 내일부터 시작할 <b>진짜 로그 분석</b>을 미리 해봅니다.</p><p>지금까지 배운 것을 떠올려보세요.<br>파일 보기(<code>cat</code>·<code>tail</code>) → 위치 찾기(<code>/var/log</code>) → 걸러내기(<code>grep</code>) → 이어붙이기(<code>|</code>) → 세기(<code>wc -l</code>) → 저장하기(<code>&gt;</code>)</p><p><b>이 여섯 개면 침해 조사의 첫 단계가 됩니다.</b></p><p>예를 들어 이 한 줄:</p><p><code>sudo grep 'Failed password' /var/log/auth.log | wc -l</code></p><p>'인증 로그에서 비밀번호 실패한 줄만 골라 세어라' — <b>브루트포스 공격이 있었는지 확인하는 명령</b>입니다. 여러분은 이제 이걸 읽을 수 있습니다.</p><p><b>내일부터 ACT 1 이 시작됩니다.</b> 거기서는 이 도구들로 실제 침해를 추적합니다. 오늘 손에 익힌 것이 그대로 무기가 됩니다.</p><p>막히면 언제든 <b>ACT 0 으로 돌아오세요.</b> 기초를 다시 보는 건 후퇴가 아니라 정상적인 학습입니다.</p>",
term:"# 오늘 배운 것을 전부 이어 붙이면\n$ sudo grep 'Failed password' /var/log/auth.log | wc -l\n<b>1847</b>\n\n# 그리고 이게 ACT 1 의 시작점이다\n$ sudo grep 'Failed password' /var/log/auth.log | tail -3",
lab:["<code>sudo tail -50 /var/log/auth.log</code> 로 최근 인증 기록을 훑어본다","<code>sudo grep 'Failed' /var/log/auth.log | wc -l</code> 로 실패 횟수를 센다","<code>sudo grep 'Accepted' /var/log/auth.log | tail -5</code> 로 성공한 로그인을 본다","<code>sudo grep 'sudo:' /var/log/auth.log | tail -10</code> 으로 sudo 사용 기록을 본다","결과를 <code>&gt; ~/first-report.txt</code> 로 저장한다","<code>ps auxf | head -20</code> 으로 프로세스 트리를 다시 본다","<code>systemctl list-unit-files --state=enabled | wc -l</code> 로 자동 시작 서비스 수를 센다","ACT 0 에서 배운 명령 20개를 <b>자기만의 치트시트</b>로 정리해 저장한다","'막히면 여기로 돌아온다' 는 마음으로 이 파일을 잘 보관한다"],
q:[{t:"<code>grep 'Failed password' /var/log/auth.log | wc -l</code> 이 하는 일을 한 문장으로 고르면?",o:["실패한 로그인을 삭제한다","인증 로그에서 비밀번호 실패 줄만 골라 그 개수를 센다","비밀번호를 바꾼다","로그를 압축한다"],a:1,
  e:"<b>걸러내고 → 센다.</b> 이 한 줄이 '브루트포스 공격이 있었나' 를 확인하는 명령이고, 내일부터 시작할 ACT 1 의 출발점입니다."},
   {t:"기초를 마친 지금, 다음 단계로 가장 적절한 태도는?",o:["기초는 다 끝났으니 다시 안 봐도 된다","막히면 언제든 돌아와서 다시 보는 것이 정상적인 학습이다","전부 외운 뒤에 넘어간다","기초를 처음부터 다시 한다"],a:1,
    e:"<b>돌아오는 것은 후퇴가 아닙니다.</b> 실무자도 <code>man</code> 을 매일 봅니다. 외우는 게 목표가 아니라 <b>찾아 쓸 수 있는 상태</b>가 목표입니다."},
   {k:"cmd",t:"인증 로그에서 <code>Accepted</code> 가 들어간 줄의 <b>마지막 5줄</b>을 보는 파이프라인을 입력하세요.",
    ph:"grep ... | ...",a:["grep 'Accepted' /var/log/auth.log | tail -5"],
    re:["^grep\\s+['\"]?accepted['\"]?\\s+/var/log/auth\\.log\\s*\\|\\s*tail\\s+(-n\\s*)?-?\\s*5$"],
    hint:"걸러내고 → 뒤에서 자르기. 두 단계입니다.",
    e:"<code>grep 'Accepted' /var/log/auth.log | tail -5</code> — <b>성공한 로그인</b>을 보는 명령입니다. 브루트포스 실패가 수천 건 있는데 그 뒤에 이게 하나 있다면, 그건 <b>뚫린 것</b>입니다. 내일 ACT 1 에서 바로 이 이야기를 합니다."}]}

]},
