const ACTS=[

{n:0,t:"레드팀 입문과 정찰",s:"공격자는 어떻게 생각하고, 어디서부터 시작하는가. 손대기 전에 눈으로 다 본다.",days:[

{d:1,t:"공격자처럼 생각하기",g:"방어자와 공격자의 시점 차이를 이해하고, 킬체인의 큰 그림을 잡는다.",
c:"<p>방어를 공부하셨으니 이제 <b>반대편</b>에 서봅니다. 좋은 공격자는 좋은 방어자가 됩니다 — 상대의 수를 알아야 막으니까요.</p><p><b>가장 큰 차이는 '비대칭'입니다.</b><br>방어자는 <b>모든 문</b>을 지켜야 합니다. 공격자는 <b>문 하나</b>만 열면 됩니다.<br>방어자는 100% 를 방어해야 이기고, 공격자는 1% 만 뚫어도 이깁니다. 그래서 공격자는 <b>가장 약한 곳</b>을 찾는 데 집중합니다.</p><p><b>공격은 순서가 있습니다.</b> 이걸 <b>사이버 킬체인</b> 또는 공격 생명주기라 부릅니다.<br>① <b>정찰</b>(Recon) — 대상을 관찰한다<br>② <b>초기 침투</b>(Initial Access) — 첫 발을 들인다<br>③ <b>권한 상승</b>(PrivEsc) — 더 높은 권한을 얻는다<br>④ <b>내부 이동</b>(Lateral Movement) — 옆 시스템으로 퍼진다<br>⑤ <b>목적 달성</b>(Actions) — 데이터 탈취·지속성 확보</p><p><b>이 코스는 이 순서를 그대로 따라갑니다.</b> ACT 0 은 ①번, <b>정찰</b>입니다. 공격의 80%는 사실 손대기 전 '보는 일'입니다. 아무것도 건드리지 않고 대상을 완전히 파악하는 것 — 거기서 실력이 갈립니다.</p><p>방어자 시절 배운 <b>MITRE ATT&CK</b>을 기억하세요. 그건 <b>공격자의 수법을 정리한 사전</b>입니다. 이제 그걸 반대로, <b>내가 쓸 기술 목록</b>으로 읽습니다.</p>",
term:"# 공격의 5단계 — 이 코스의 지도\n[1] 정찰      nmap, gobuster, OSINT      <- ACT 0 (지금 여기)\n[2] 초기 침투  exploit, 웹 취약점, 피싱\n[3] 권한 상승  SUID, 커널, 오설정\n[4] 내부 이동  pivoting, AD, pass-the-hash\n[5] 목적 달성  exfil, 지속성, 흔적 정리",
lab:["방어자와 공격자의 '비대칭'을 자기 말로 한 줄 적는다","사이버 킬체인 5단계를 순서대로 외워 적는다","내가 방어자로 배운 것 중 공격에도 쓰일 지식 3개를 꼽는다","MITRE ATT&CK 웹사이트(attack.mitre.org)에서 Tactics 목록을 훑는다","'정찰'이 왜 공격의 80%인지 생각해 적는다","좋아하는 CTF 플랫폼 하나를 정한다 (TryHackMe·HackTheBox·picoCTF 중)","이 코스를 끝냈을 때 하고 싶은 것을 한 줄로 적어둔다"],
q:[{t:"공격자와 방어자의 근본적인 비대칭을 가장 잘 설명한 것은?",o:["공격자가 항상 더 똑똑하다","방어자는 모든 곳을 지켜야 하지만 공격자는 한 곳만 뚫으면 된다","공격자는 도구가 더 많다","방어자는 법의 보호를 받는다"],a:1,
  e:"<b>1% 대 100%</b> 입니다. 이 비대칭 때문에 공격자는 '가장 약한 고리' 를 찾는 데 집중하고, 방어자는 공격 표면 전체를 줄이는 데 집중합니다."},
   {t:"사이버 킬체인에서 가장 먼저 오는 단계는?",o:["권한 상승","정찰","초기 침투","내부 이동"],a:1,
    e:"<b>정찰(Recon)</b> 입니다. 대상을 관찰하는 단계이고, 이 ACT 전체가 여기에 해당합니다. 잘 본 만큼 잘 뚫습니다."},
   {t:"방어자로서 배운 MITRE ATT&CK을 공격자 시점에서 다시 읽으면 무엇이 되는가?",o:["방어 규칙 목록","공격자가 쓰는 기술(TTP)의 사전","취약점 데이터베이스","로그 형식 표준"],a:1,
    e:"ATT&CK은 원래 <b>실제 공격자의 수법을 정리</b>한 것입니다. 방어자는 '이걸 탐지하자' 로 읽고, 공격자는 '이걸 써보자' 로 읽습니다. 같은 지도를 양쪽에서 보는 겁니다."}]},

{d:2,t:"허가와 범위 — 넘으면 범죄다",g:"공격 기술을 어디서 써도 되고 어디서 쓰면 안 되는지 명확히 한다.",
c:"<p><b>가장 중요한 날입니다.</b> 기술보다 이걸 먼저 못 박습니다.</p><p>이 코스에서 배우는 기술은 <b>허가받은 대상</b>에만 씁니다. 남의 서버에 <code>nmap</code> 한 번 돌리는 것도, 나라에 따라 <b>범죄</b>가 됩니다. 한국은 <b>정보통신망법</b>으로 무단 침입·접근을 처벌합니다.</p><p><b>합법적으로 연습할 곳은 넘칩니다.</b><br><b>CTF 플랫폼</b> — TryHackMe, HackTheBox, picoCTF. 일부러 취약하게 만든 <b>연습용 표적</b>입니다.<br><b>내 실습실</b> — 내 PC 안에 가상머신으로 표적을 세웁니다. Metasploitable, DVWA, VulnHub.<br><b>버그바운티</b> — HackerOne, Bugcrowd. 기업이 '우리를 뚫어달라' 고 공개한 프로그램. <b>단, 명시된 범위(scope) 안에서만.</b></p><p>실제 업무(모의해킹)에는 <b>ROE</b>(Rules of Engagement, 교전 규칙)라는 문서가 있습니다.<br>· <b>범위</b>(scope) — 어떤 IP·도메인을 건드려도 되는가<br>· <b>제외</b>(out of scope) — 절대 건드리면 안 되는 것 (보통 운영 DB, 결제 시스템)<br>· <b>기간</b>과 <b>시간대</b> — 언제 해도 되는가<br>· <b>금지 기법</b> — DoS·소셜엔지니어링 허용 여부</p><p><b>원칙 하나만 기억하세요: 서면 허가 없이는 아무것도 건드리지 않는다.</b> '테스트였다', '취약점을 알려주려 했다' 는 변명이 되지 않습니다. 이 코스의 실습은 전부 <b>본인 실습실이나 허가된 CTF</b>에서 하세요.</p>",
term:"# 이 코스 실습을 할 안전한 곳\n[O] 내 PC 안 가상머신 (Metasploitable, DVWA)\n[O] TryHackMe / HackTheBox / picoCTF\n[O] 버그바운티 — 명시된 scope 안에서만\n\n[X] 남의 웹사이트, 회사 서버, 공공 IP\n[X] '그냥 nmap 만' 도 무단이면 위법",
lab:["정보통신망법 제48조(침해행위 금지)를 한 번 읽어본다","'허가 없이는 건드리지 않는다' 를 노트 맨 앞에 적는다","합법 연습처 3곳의 계정을 만든다 (THM·HTB·picoCTF)","ROE 의 4가지 항목(범위·제외·기간·금지기법)을 외운다","버그바운티 프로그램 하나의 scope 페이지를 읽어본다","'in scope' 와 'out of scope' 의 차이를 예로 들어 적는다","실습용 가상머신을 하나 정한다 (Metasploitable 2 추천)"],
q:[{t:"허가 없이 남의 서버에 <code>nmap</code> 포트 스캔만 돌렸다. 법적으로는?",o:["스캔은 접속이 아니라 항상 합법","나라·상황에 따라 무단 접근으로 처벌될 수 있다","포트를 안 열었으면 괜찮다","공개된 서버면 괜찮다"],a:1,
  e:"스캔도 <b>무단 접근 시도</b>로 볼 수 있습니다. '건드리지 않았다' 는 기준이 생각보다 낮습니다. <b>서면 허가나 명시된 scope 없이는 하지 마세요.</b>"},
   {t:"버그바운티에서 'out of scope' 로 표시된 시스템을 뚫었다면?",o:["보상을 더 받는다","허가 범위를 벗어난 것이라 불법이 될 수 있다","문제없다, 같은 회사니까","경고만 받는다"],a:1,
    e:"scope 밖은 <b>허가가 없는 것</b>입니다. 같은 회사여도 out of scope 를 건드리면 프로그램 위반이고, 법적 문제가 됩니다. <b>scope 는 계약서처럼 지켜야 합니다.</b>"},
   {t:"모의해킹의 ROE(교전 규칙)에 보통 없는 항목은?",o:["건드려도 되는 범위(scope)","절대 건드리면 안 되는 제외 대상","테스트 가능 기간","공격자의 실명과 주민번호"],a:3,
    e:"ROE 는 <b>범위·제외·기간·금지기법</b>을 정합니다. 무엇을 언제 어떻게 해도 되는지의 계약이지, 개인정보를 담는 문서가 아닙니다."}]},

{d:3,t:"공격자의 실습실 차리기",g:"안전하게 격리된 곳에서 표적을 세우고 공격 도구를 갖춘다.",
c:"<p>연습하려면 <b>공격 머신</b>과 <b>표적 머신</b>이 필요합니다. 둘 다 내 PC 안에 가상머신으로 두고, <b>바깥 인터넷과 분리</b>하는 게 핵심입니다.</p><p><b>공격 머신 — Kali Linux</b><br>모의해킹 도구가 처음부터 다 깔려 있는 리눅스입니다. <code>nmap</code>, <code>gobuster</code>, <code>Burp Suite</code>, <code>metasploit</code>, <code>hashcat</code>… 이 코스에서 쓸 도구가 전부 들어 있습니다. Parrot OS 도 대안입니다.</p><p><b>표적 머신 — 일부러 취약한 것들</b><br><b>Metasploitable 2/3</b> — 취약점 백화점. 초보 연습의 표준.<br><b>DVWA</b>(Damn Vulnerable Web App) — 웹 취약점 연습용.<br><b>VulnHub</b> — 다운받아 푸는 표적 모음.<br><b>TryHackMe / HackTheBox</b> — 브라우저나 VPN 으로 접속하는 온라인 표적.</p><p><b>격리가 생명입니다.</b> 가상머신 네트워크를 <b>Host-Only</b> 나 <b>Internal</b> 로 설정하세요. 취약한 표적이 실제 인터넷에 노출되면 <b>진짜 공격자에게 먹힙니다</b> — 내가 세운 표적이 남을 공격하는 발판이 될 수 있습니다.</p><p>VirtualBox 나 VMware 로 가상머신을 돌립니다. 표적을 켜고 <code>ip a</code> 로 IP 를 확인한 뒤, Kali 에서 그 IP 로 접근되는지 <code>ping</code> 으로 확인하면 실습실 준비 끝입니다.</p>",
term:"kali@kali:~$ ip a | grep inet\n    inet 192.168.56.101/24    # 내 공격 머신\nkali@kali:~$ ping -c 2 192.168.56.102   # 표적\n64 bytes from 192.168.56.102: icmp_seq=1 ttl=64 time=0.4 ms\n# 표적이 살아있다 — 실습 준비 완료",
lab:["VirtualBox 또는 VMware 를 설치한다","Kali Linux 가상머신을 내려받아 부팅한다","표적으로 Metasploitable 2 를 내려받아 부팅한다","두 VM 의 네트워크를 Host-Only 로 설정해 인터넷과 분리한다","각 VM 에서 <code>ip a</code> 로 IP 를 확인한다","Kali 에서 표적으로 <code>ping</code> 이 되는지 확인한다","<code>nmap --version</code> 으로 Kali 에 도구가 있는지 확인한다"],
q:[{t:"Kali Linux 가 모의해킹에 쓰이는 이유는?",o:["가장 빠른 리눅스라서","공격 도구가 처음부터 대부분 설치되어 있어서","해킹이 합법이 되는 OS라서","백신이 없어서"],a:1,
  e:"Kali 는 <b>도구 모음이 갖춰진 배포판</b>일 뿐입니다. OS 가 무엇이냐는 합법성과 무관합니다 — 어디에 쓰느냐가 전부입니다."},
   {t:"취약한 표적 가상머신의 네트워크를 Host-Only/Internal 로 두는 이유는?",o:["속도가 빨라서","취약한 표적이 실제 인터넷에 노출되면 진짜 공격자에게 뚫려 악용될 수 있어서","IP를 아껴서","가상머신 규칙이라서"],a:1,
    e:"일부러 취약하게 만든 머신입니다. 인터넷에 붙으면 <b>남을 공격하는 발판</b>이 됩니다. 반드시 격리하세요."},
   {k:"cmd",t:"표적 <code>192.168.56.102</code> 가 살아있는지 <b>2번만</b> 핑을 보내 확인하는 명령을 입력하세요.",
    ph:"ping ...","a":["ping -c 2 192.168.56.102"],"re":["^ping\\s+-c\\s*2\\s+192\\.168\\.56\\.102$"],
    hint:"횟수를 정하는 옵션은 count 의 앞 글자입니다.",
    e:"<code>ping -c 2 192.168.56.102</code> — <code>-c</code> 없이 리눅스에서 핑하면 무한히 갑니다(<code>Ctrl+C</code> 로 중단). 표적이 핑에 응답하지 않게 설정된 경우도 많으니, 안 된다고 죽었다 단정하면 안 됩니다."}]},

{d:4,t:"공격 방법론 — 순서가 실력이다",g:"주먹구구가 아니라 정해진 순서로 대상을 공략하는 틀을 익힌다.",
c:"<p>초보와 숙련자의 차이는 도구가 아니라 <b>순서</b>입니다. 숙련자는 늘 같은 방법론을 따릅니다.</p><p><b>정찰 → 열거 → 침투 → 상승 → 확장</b></p><p><b>① 정찰(Recon)</b> — 대상이 무엇인지 넓게 본다. 어떤 IP, 어떤 도메인, 어떤 회사인가.<br><b>② 열거(Enumeration)</b> — 발견한 것을 깊게 판다. 이 포트에 뭐가 돌고, 버전이 몇이고, 어떤 사용자·공유·디렉터리가 있는가. <b>여기가 가장 중요합니다.</b><br><b>③ 침투(Exploitation)</b> — 찾은 약점으로 첫 발을 들인다.<br><b>④ 권한 상승(PrivEsc)</b> — 낮은 권한에서 root/administrator 로.<br><b>⑤ 확장(Post-Exploitation)</b> — 내부 이동, 지속성, 목표 달성.</p><p><b>가장 흔한 초보의 실수: 열거를 대충 하고 바로 익스플로잇으로 뛴다.</b> 그러다 막히면 '풀 게 없다' 고 합니다. 사실은 <b>안 본 포트, 안 판 디렉터리, 안 읽은 버전</b>에 답이 있었던 겁니다.</p><p>격언이 있습니다. <b>\"Enumerate more.\"</b> 막히면 답은 거의 항상 '더 열거하라' 입니다. 이 코스의 ACT 0 전체가 ①②, 즉 <b>정찰과 열거</b>에 집중하는 이유입니다.</p><p>그리고 <b>기록하세요.</b> 찾은 포트·버전·자격증명을 전부 메모합니다. 나중에 ③④에서 그 조각들이 열쇠가 됩니다.</p>",
term:"# 표적 하나를 공략하는 표준 순서\n1. nmap -p- 표적          # 열린 포트 전부\n2. nmap -sV -sC -p22,80   # 그 포트를 깊게\n3. gobuster / enum4linux  # 서비스별 열거\n4. searchsploit <버전>    # 약점 찾기\n5. exploit -> shell       # 침투\n... 기록하고, 막히면 다시 2번으로",
lab:["'정찰→열거→침투→상승→확장' 5단계를 외워 적는다","'Enumerate more' 격언의 의미를 자기 말로 적는다","초보가 익스플로잇으로 성급히 뛰면 뭘 놓치는지 3가지 적는다","공략 노트 템플릿을 만든다 (IP·포트·버전·자격증명·메모 칸)","열거와 정찰의 차이를 한 문장으로 구분해 적는다","좋아하는 CTF 표적 하나에서 이 순서를 머릿속으로 적용해본다","'막히면 2번으로 돌아간다' 를 노트에 적어둔다"],
q:[{t:"모의해킹에서 초보가 가장 흔히 하는 실수는?",o:["도구를 너무 많이 쓴다","열거를 대충 하고 바로 익스플로잇으로 뛴다","기록을 너무 많이 한다","정찰에 시간을 너무 쓴다"],a:1,
  e:"<b>Enumerate more.</b> 막혔을 때 답은 거의 항상 '아직 안 본 곳' 에 있습니다. 열거는 지루하지만 여기서 승부가 납니다."},
   {t:"방법론에서 '열거(Enumeration)' 가 하는 일은?",o:["대상을 넓게 훑기","발견한 서비스를 깊게 파서 버전·사용자·경로를 알아내기","권한을 올리기","흔적을 지우기"],a:1,
    e:"정찰이 '넓게' 라면 열거는 '깊게' 입니다. 포트 하나하나에 뭐가 돌고 어떤 약점이 있는지 캐내는 단계이고, 공략의 핵심입니다."},
   {t:"공략 중 계속 기록을 남기는 이유로 가장 적절한 것은?",o:["보고서 분량을 채우려고","정찰·열거에서 찾은 조각들이 나중 침투·상승 단계의 열쇠가 되기 때문","도구가 요구해서","법으로 정해져서"],a:1,
    e:"초기에 스쳐 지나간 버전 번호나 사용자 이름이 나중에 결정적 단서가 됩니다. <b>본 것을 다 적어두는 사람</b>이 결국 뚫습니다."}]},

{d:5,t:"포트와 프로토콜 — 공격자의 지도",g:"포트 번호만 보고 그 뒤에 무엇이 있는지, 어떻게 공략할지 감을 잡는다.",
c:"<p>정찰의 결과는 결국 <b>열린 포트 목록</b>입니다. 포트 번호를 보면 <b>거기서 뭘 노려야 하는지</b> 바로 떠올라야 합니다. 방어자 때 배운 포트를 이제 <b>공격 표면</b>으로 다시 봅니다.</p><p><b>웹 — 가장 큰 공격 표면</b><br>80(HTTP)·443(HTTPS)·8080·8000·8443. 웹이 보이면 <b>디렉터리 열거, 로그인 우회, 인젝션</b>을 떠올립니다. 요즘 실전의 대부분이 웹입니다.</p><p><b>원격 접속 — 자격증명이 핵심</b><br>22(SSH)·3389(RDP)·5900(VNC)·23(Telnet, 평문!). 약한 비밀번호나 유출된 키가 있으면 그대로 들어갑니다.</p><p><b>파일 공유 — 열거의 보물창고</b><br>21(FTP, 익명 로그인?)·139/445(SMB)·2049(NFS). 공유 폴더에 <b>비밀번호·설정파일·백업</b>이 굴러다니는 경우가 많습니다.</p><p><b>데이터베이스</b><br>3306(MySQL)·5432(PostgreSQL)·1433(MSSQL)·27017(MongoDB)·6379(Redis). 인증 없이 열려 있거나 기본 계정을 쓰는 경우가 놀랄 만큼 많습니다.</p><p><b>기타 노른자</b><br>25(SMTP)·53(DNS)·161(SNMP, 정보 유출)·111(RPC).</p><p><b>비표준 포트를 의심하세요.</b> 8080 에 관리자 페이지, 8443 에 개발용 서버가 열려 있는 경우가 흔합니다. 그래서 <b>모든 포트</b>를 스캔하는 게 중요합니다(<code>-p-</code>). 잘 알려진 1000개만 보면 노른자를 놓칩니다.</p>",
term:"# 포트를 보면 공략 지점이 보인다\n22/tcp   ssh       -> 약한 비번? 유출 키?\n80/tcp   http      -> 디렉터리 열거, 인젝션\n445/tcp  smb       -> 익명 공유? enum4linux\n3306/tcp mysql     -> 인증 없이? 기본 계정?\n6379/tcp redis     -> 인증 없이 열린 경우 많음",
lab:["웹 관련 포트 5개를 외워 적는다 (80·443·8080·8000·8443)","원격 접속 포트 4개를 적고 각각 무엇을 노릴지 쓴다","파일 공유 포트(21·139·445·2049)와 노림수를 적는다","데이터베이스 포트 5개와 그 DB 이름을 짝짓는다","'왜 -p- 로 전 포트를 봐야 하는지' 한 줄 적는다","평문 프로토콜(23·21·23·110)이 왜 위험한지 적는다","자주 쓰는 포트→서비스→공략 치트시트를 만든다"],
q:[{t:"공격 표면이 가장 넓어 실전에서 가장 자주 노려지는 포트군은?",o:["데이터베이스","웹(80·443·8080 등)","DNS","SNMP"],a:1,
  e:"현대 실전 침투의 대부분이 <b>웹</b>에서 일어납니다. 디렉터리 열거·인젝션·인증 우회 등 노릴 거리가 가장 많습니다."},
   {t:"nmap 에서 잘 알려진 1000개 포트만 스캔하면 생기는 문제는?",o:["너무 느리다","8080·8443 같은 비표준 포트의 서비스를 놓칠 수 있다","IP가 차단된다","결과가 부정확하다"],a:1,
    e:"관리자 페이지·개발 서버가 <b>비표준 포트</b>에 있는 경우가 흔합니다. 그래서 <code>-p-</code> 로 전 포트를 보는 습관이 중요합니다."},
   {t:"포트 6379(Redis)를 발견했을 때 공격자가 가장 먼저 떠올리는 것은?",o:["암호화되어 안전하다","인증 없이 열려 있거나 기본 설정인 경우가 많다","웹 서버다","DNS 서버다"],a:1,
    e:"Redis·MongoDB·Elasticsearch 는 기본이 <b>인증 없음</b>인 시절이 길었습니다. 아직도 무인증으로 노출된 사례가 많아 즉시 노려집니다."}]},

{d:6,t:"수동 정찰 — 건드리지 않고 알아내기",g:"표적에 패킷 하나 안 보내고 공개 정보만으로 대상을 파악한다.",
c:"<p>정찰은 두 가지입니다. <b>수동(Passive)</b> 은 표적을 직접 건드리지 않고 <b>공개된 정보</b>만 모읍니다. <b>능동(Active)</b> 은 표적에 직접 패킷을 보냅니다(다음 날). 수동은 흔적이 안 남아 조용하고, 법적으로도 안전합니다.</p><p><b>WHOIS</b> — 도메인 등록 정보. 소유 조직, 등록일, 네임서버, 때로 담당자 이메일.<br><code>whois example.com</code></p><p><b>DNS 조회</b> — 도메인이 어떤 IP·서비스로 연결되는지.<br><code>dig example.com</code>, <code>dig MX example.com</code>(메일서버), <code>dig TXT</code>(SPF·검증 기록).</p><p><b>구글 도킹(Google Dorking)</b> — 검색 연산자로 노출된 것을 찾습니다.<br><code>site:example.com</code> 그 도메인만 · <code>filetype:pdf</code> 특정 파일 · <code>intitle:\"index of\"</code> 열린 디렉터리 · <code>inurl:admin</code> 관리 페이지.</p><p><b>인증서 투명성(crt.sh)</b> — HTTPS 인증서 기록에서 <b>서브도메인</b>이 줄줄이 나옵니다. <code>dev.</code>, <code>staging.</code>, <code>vpn.</code> 같은 숨은 자산이 드러납니다.</p><p><b>기타</b> — Shodan(인터넷에 노출된 장비 검색엔진), Wayback Machine(과거 페이지), LinkedIn(직원 명단 → 사용자명 규칙 추론), GitHub(실수로 올린 API 키·비밀번호).</p><p><b>수동 정찰만으로도 놀랄 만큼 많이 알아냅니다.</b> 서브도메인, 기술 스택, 직원 이메일 형식, 노출된 문서 — 전부 표적을 건드리기 전에 모을 수 있습니다.</p>",
term:"kali@kali:~$ dig +short example.com\n93.184.216.34\nkali@kali:~$ dig +short MX example.com\n10 mail.example.com\nkali@kali:~$ whois example.com | grep -i 'org\\|name server'\nOrg Name: Example Inc.\nName Server: A.IANA-SERVERS.NET",
lab:["<code>whois</code> 로 아무 도메인의 등록 정보를 조회한다","<code>dig +short</code> 로 도메인의 A 레코드(IP)를 본다","<code>dig MX</code> 로 메일 서버를 조회한다","<code>dig TXT</code> 로 SPF 등 텍스트 레코드를 본다","crt.sh 에서 한 도메인의 서브도메인 목록을 본다","구글 도킹 <code>site:</code> 와 <code>filetype:</code> 를 직접 써본다","'수동 정찰만으로 알 수 있는 것' 목록을 6개 이상 적는다"],
q:[{t:"수동(Passive) 정찰의 핵심 특징은?",o:["가장 빠르다","표적에 직접 패킷을 보내지 않고 공개 정보만 모아 흔적이 남지 않는다","가장 정확하다","도구가 필요 없다"],a:1,
  e:"수동 정찰은 <b>표적을 건드리지 않습니다.</b> WHOIS·DNS·검색엔진·인증서 기록 등 이미 공개된 것만 봅니다. 조용하고 안전합니다."},
   {t:"crt.sh(인증서 투명성 로그)가 정찰에 유용한 이유는?",o:["비밀번호가 나온다","HTTPS 인증서 기록에서 숨은 서브도메인이 드러난다","포트를 알려준다","취약점을 보여준다"],a:1,
    e:"인증서를 발급받으면 공개 로그에 남습니다. <code>dev.</code>·<code>vpn.</code> 같은 <b>내부용 서브도메인</b>이 여기서 노출되는 경우가 많습니다."},
   {k:"cmd",t:"<code>example.com</code> 의 <b>메일 서버(MX 레코드)</b>를 간결하게 조회하는 명령을 입력하세요.",
    ph:"dig ...","a":["dig +short MX example.com"],"re":["^dig\\s+(\\+short\\s+mx\\s+example\\.com|mx\\s+example\\.com\\s+\\+short)$"],
    hint:"레코드 타입 MX 를 지정하고, 짧게 보는 옵션을 붙입니다.",
    e:"<code>dig +short MX example.com</code> — 메일 서버를 알면 피싱·SMTP 공격의 표적이 됩니다. 수동 정찰의 기본 조회입니다."}]},

{d:7,t:"능동 정찰 — 살아있는 호스트 찾기",g:"네트워크 대역에서 실제로 켜져 있는 장비를 골라낸다.",
c:"<p>이제 <b>능동 정찰</b>입니다 — 표적에 직접 패킷을 보냅니다. 흔적이 남으니 <b>반드시 허가된 대상</b>에만 하세요.</p><p>큰 네트워크(예: <code>192.168.1.0/24</code> = 254개 주소)를 받으면, 먼저 <b>어느 주소가 살아있는지</b> 골라냅니다. 죽은 IP 254개를 다 포트스캔하는 건 낭비니까요. 이걸 <b>호스트 발견</b> 또는 <b>핑 스윕</b>이라 합니다.</p><p><b>nmap 핑 스캔</b> — 포트는 안 보고 살아있는지만.<br><code>nmap -sn 192.168.1.0/24</code><br><code>-sn</code> 은 'no port scan' 입니다. ICMP·ARP 등으로 응답하는 호스트만 나열합니다.</p><p><b>arp-scan / netdiscover</b> — 같은 랜(LAN)이라면 ARP 로 훨씬 확실하게 찾습니다. 방화벽이 ICMP(핑)를 막아도 ARP 는 같은 네트워크에서 막기 어렵습니다.<br><code>sudo arp-scan -l</code> · <code>sudo netdiscover -r 192.168.1.0/24</code></p><p><b>주의: 핑에 응답 안 한다고 죽은 게 아닙니다.</b> 방화벽이 ICMP 를 차단한 호스트는 핑 스윕에 안 잡힙니다. 그래서 확실히 하려면 <code>nmap -Pn</code>(핑 생략하고 무조건 스캔)을 쓰기도 합니다. 다만 느려집니다 — 상황에 따라 고릅니다.</p><p>CIDR 표기를 이해하세요. <code>/24</code> = 256개(254개 호스트), <code>/16</code> = 65536개. 스캔 범위를 정하는 기본입니다.</p>",
term:"kali@kali:~$ nmap -sn 192.168.56.0/24\nNmap scan report for 192.168.56.1\nHost is up (0.00021s latency).\nNmap scan report for 192.168.56.102\nHost is up (0.00035s latency).\nNmap done: 256 IP addresses (2 hosts up)",
lab:["<code>nmap -sn</code> 으로 내 실습 대역의 살아있는 호스트를 찾는다","<code>sudo arp-scan -l</code> 로 같은 랜의 장비를 나열한다","<code>-sn</code>(핑만)과 일반 스캔의 차이를 이해한다","CIDR <code>/24</code>가 몇 개 주소인지 계산해 적는다","핑에 응답 안 하는 호스트를 찾는 <code>-Pn</code> 을 시험한다","ICMP 차단 시 ARP가 왜 더 확실한지 적는다","발견한 호스트 IP를 공략 노트에 기록한다"],
q:[{t:"<code>nmap -sn</code> 이 하는 일은?",o:["모든 포트를 스캔한다","포트는 스캔하지 않고 살아있는 호스트만 찾는다","서비스 버전을 알아낸다","취약점을 찾는다"],a:1,
  e:"<code>-sn</code> = no port scan. <b>호스트 발견(핑 스윕)</b> 전용입니다. 큰 대역에서 살아있는 것만 먼저 골라내 시간을 아낍니다."},
   {t:"같은 랜에서 방화벽이 핑(ICMP)을 막아도 호스트를 찾을 수 있는 방법은?",o:["불가능하다","ARP 스캔(arp-scan·netdiscover)을 쓴다","DNS를 쓴다","재부팅한다"],a:1,
    e:"ARP 는 같은 네트워크에서 통신의 기본이라 막기 어렵습니다. <b>핑이 막힌 호스트도 ARP로는 드러납니다.</b>"},
   {k:"cmd",t:"<code>192.168.56.0/24</code> 대역에서 <b>포트 스캔 없이 살아있는 호스트만</b> 찾는 nmap 명령을 입력하세요.",
    ph:"nmap ...","a":["nmap -sn 192.168.56.0/24"],"re":["^nmap\\s+-sn\\s+192\\.168\\.56\\.0/24$"],
    hint:"'포트 스캔 안 함' 옵션은 두 글자입니다.",
    e:"<code>nmap -sn 192.168.56.0/24</code> — 살아있는 호스트 목록을 먼저 얻고, 그다음 각 호스트를 자세히 스캔하는 게 정석 순서입니다."}]},

{d:8,t:"nmap 포트 스캔 기초",g:"한 호스트에서 어떤 포트가 열려 있는지 정확히 알아낸다.",
c:"<p><b>nmap</b> 은 정찰의 심장입니다. 살아있는 호스트를 찾았으면, 이제 그 호스트의 <b>열린 포트</b>를 봅니다. 열린 포트 = 돌아가는 서비스 = 공격 표면.</p><p><b>기본 스캔</b><br><code>nmap 192.168.56.102</code><br>잘 알려진 1000개 포트를 봅니다. 빠르지만 <b>노른자를 놓칠 수 있습니다.</b></p><p><b>전 포트 스캔 — 이게 기본이 되어야 합니다</b><br><code>nmap -p- 192.168.56.102</code><br><code>-p-</code> 는 1~65535 전부. 8080·8443·비표준 포트까지 다 봅니다. 느리지만 확실합니다.</p><p><b>특정 포트만</b><br><code>nmap -p 22,80,443 표적</code> · <code>nmap -p 1-1000 표적</code></p><p><b>스캔 방식</b><br><b><code>-sS</code></b> SYN 스캔(기본, root 필요) — 연결을 끝까지 안 맺어 빠르고 은밀.<br><b><code>-sT</code></b> TCP 연결 스캔 — 완전한 연결. root 없을 때.<br><b><code>-sU</code></b> UDP 스캔 — DNS·SNMP 등. 느리지만 놓치면 안 되는 것들이 있음.</p><p>결과의 <b>상태</b>를 읽습니다. <b>open</b>(서비스 살아있음), <b>closed</b>(응답하지만 서비스 없음), <b>filtered</b>(방화벽이 막아 응답 없음).</p><p><b>실전 요령:</b> 빠른 전 포트 스캔으로 열린 포트를 먼저 찾고(<code>-p-</code>), 그 포트만 골라 다음 날 배울 깊은 스캔(<code>-sV -sC</code>)을 겁니다. 두 단계로 나누면 빠르고 정확합니다.</p>",
term:"kali@kali:~$ nmap -p- 192.168.56.102\nPORT     STATE SERVICE\n21/tcp   open  ftp\n22/tcp   open  ssh\n80/tcp   open  http\n445/tcp  open  microsoft-ds\n3306/tcp open  mysql\n8080/tcp open  http-proxy    # 비표준 포트 — -p- 라서 잡혔다",
lab:["<code>nmap 표적</code> 으로 기본 스캔을 돌린다","<code>nmap -p- 표적</code> 으로 전 포트를 스캔한다","기본 스캔과 <code>-p-</code> 결과의 포트 수를 비교한다","<code>nmap -p 22,80,445 표적</code> 으로 특정 포트만 본다","open·closed·filtered 상태의 차이를 확인한다","<code>-sU</code> 로 UDP 포트를 스캔해본다(느림)","열린 포트를 전부 공략 노트에 기록한다"],
q:[{t:"nmap 에서 <code>-p-</code> 가 의미하는 것은?",o:["잘 알려진 1000개 포트","1번부터 65535번까지 전체 포트","열린 포트만","UDP 포트만"],a:1,
  e:"<code>-p-</code> = <b>전 포트(1-65535)</b>. 비표준 포트의 숨은 서비스를 놓치지 않으려면 기본으로 삼아야 합니다."},
   {t:"포트 상태가 <b>filtered</b> 로 나온다는 것은?",o:["서비스가 살아있다","방화벽이 막아 응답이 없어 열림/닫힘을 판단할 수 없다","포트가 닫혀 있다","스캔이 실패했다"],a:1,
    e:"<b>filtered</b> 는 방화벽·필터가 응답을 삼킨 상태입니다. open 도 closed 도 확정할 수 없습니다. <code>open</code> 이라야 서비스가 돌고 있는 겁니다."},
   {k:"cmd",t:"표적 <code>192.168.56.102</code> 의 <b>모든 포트</b>를 스캔하는 nmap 명령을 입력하세요.",
    ph:"nmap ...","a":["nmap -p- 192.168.56.102"],"re":["^nmap\\s+-p-\\s+192\\.168\\.56\\.102$"],
    hint:"전 포트를 뜻하는 옵션은 -p 뒤에 하이픈 하나입니다.",
    e:"<code>nmap -p- 192.168.56.102</code> — 여기서 나온 열린 포트들을 다음 단계에서 <code>-sV -sC</code> 로 깊게 팝니다."}]},

{d:9,t:"nmap 심화 — 버전과 OS 알아내기",g:"열린 포트 뒤에서 무엇이, 어떤 버전으로 돌고 있는지 정확히 캐낸다.",
c:"<p>포트가 열린 걸 아는 것만으로는 부족합니다. <b>어떤 소프트웨어가 몇 버전으로</b> 돌고 있는지 알아야 약점을 찾습니다. 버전 하나가 곧 CVE 하나로 이어집니다.</p><p><b>서비스·버전 탐지</b><br><code>nmap -sV 192.168.56.102</code><br>배너를 읽어 <code>Apache 2.4.49</code>, <code>OpenSSH 7.2</code> 처럼 <b>정확한 버전</b>을 뽑습니다. 이게 다음 단계(약점 찾기)의 핵심 입력입니다.</p><p><b>OS 추정</b><br><code>sudo nmap -O 192.168.56.102</code><br>TCP/IP 특성으로 운영체제를 추정합니다(Linux 3.x, Windows 10 등).</p><p><b>한 방에 — 실전에서 가장 많이 치는 조합</b><br><code>nmap -sC -sV -p22,80,445 192.168.56.102</code><br><code>-sV</code> 버전 + <code>-sC</code> 기본 스크립트(다음 날). 앞서 <code>-p-</code> 로 찾은 포트만 지정해 빠르게.</p><p><b>속도 조절 — 타이밍</b><br><code>-T0</code>(가장 느림·은밀) ~ <code>-T5</code>(가장 빠름·시끄러움). 실습·CTF 는 <code>-T4</code> 가 무난합니다. 실전에서 탐지를 피하려면 낮춥니다.</p><p><b>결과를 저장하세요.</b> <code>-oN out.txt</code>(사람용), <code>-oA scan</code>(세 형식 전부). 나중에 다시 볼 정찰 기록입니다.</p><p><b>왜 버전이 중요한가:</b> <code>Apache 2.4.49</code> 를 보는 순간 숙련자는 <b>CVE-2021-41773(경로 순회)</b> 을 떠올립니다. 버전 → 알려진 취약점 → 익스플로잇. 이 사슬이 정찰의 목적입니다.</p>",
term:"kali@kali:~$ nmap -sV -p22,80 192.168.56.102\nPORT   STATE SERVICE VERSION\n22/tcp open  ssh     OpenSSH 4.7p1 Debian 8ubuntu1\n80/tcp open  http    Apache httpd 2.2.8 ((Ubuntu))\n# 버전이 낮다 -> 알려진 취약점이 널렸다",
lab:["<code>nmap -sV 표적</code> 으로 서비스 버전을 알아낸다","앞서 찾은 열린 포트만 골라 <code>-sV -p</code> 로 스캔한다","<code>sudo nmap -O 표적</code> 으로 OS를 추정한다","<code>-sC -sV</code> 조합을 한 번에 돌린다","<code>-T4</code> 와 기본 속도의 차이를 느껴본다","<code>-oN out.txt</code> 로 결과를 파일로 저장한다","찾은 버전 번호를 전부 노트에 적는다 (다음 날 CVE 검색용)"],
q:[{t:"nmap <code>-sV</code> 가 알아내는 것은?",o:["OS 종류","포트에서 돌아가는 서비스의 정확한 소프트웨어와 버전","방화벽 규칙","사용자 목록"],a:1,
  e:"<code>-sV</code> = 버전 탐지. <code>Apache 2.4.49</code> 같은 <b>정확한 버전</b>을 뽑아냅니다. 이 버전이 곧 취약점 검색의 열쇠입니다."},
   {t:"정찰에서 소프트웨어 버전을 알아내는 것이 결정적인 이유는?",o:["보고서에 필요해서","버전으로 알려진 취약점(CVE)과 익스플로잇을 특정할 수 있어서","속도를 높여서","방화벽을 우회해서"],a:1,
    e:"버전 → 알려진 CVE → 공개 익스플로잇. 이 사슬이 정찰의 목적입니다. <code>vsftpd 2.3.4</code> 를 보면 백도어를 떠올리는 식입니다."},
   {k:"cmd",t:"표적 <code>10.10.10.5</code> 의 포트 <b>22와 80</b>에 대해 <b>서비스 버전</b>을 알아내는 nmap 명령을 입력하세요.",
    ph:"nmap ...","a":["nmap -sV -p22,80 10.10.10.5"],
    "re":["^nmap\\s+-sv\\s+-p\\s*22,80\\s+10\\.10\\.10\\.5$","^nmap\\s+-p\\s*22,80\\s+-sv\\s+10\\.10\\.10\\.5$"],
    hint:"버전 탐지 옵션과 포트 지정 옵션을 함께 씁니다.",
    e:"<code>nmap -sV -p22,80 10.10.10.5</code> — 옵션 순서는 상관없습니다. 앞서 <code>-p-</code> 로 찾은 포트만 지정하면 훨씬 빠릅니다."}]},

{d:10,t:"nmap NSE — 스크립트로 자동 열거",g:"nmap의 스크립트 엔진으로 취약점과 정보를 자동으로 캐낸다.",
c:"<p>nmap 은 단순 포트 스캐너가 아닙니다. <b>NSE</b>(Nmap Scripting Engine)로 수백 개의 자동 점검을 돌릴 수 있습니다 — 취약점 확인, 자격증명 시도, 정보 수집까지.</p><p><b>기본 스크립트</b><br><code>nmap -sC 표적</code> 또는 <code>--script=default</code><br>안전한 기본 점검 묶음. 배너, HTTP 제목, 익명 FTP 여부 등을 자동으로 봅니다. <code>-sV</code> 와 늘 함께 씁니다.</p><p><b>카테고리로 실행</b><br><code>--script=vuln</code> 알려진 취약점 점검 · <code>--script=safe</code> 안전한 것만 · <code>--script=auth</code> 인증 관련 · <code>--script=discovery</code> 정보 수집.</p><p><b>특정 스크립트</b><br><code>nmap --script=http-enum 표적</code> — 웹 디렉터리·앱 자동 열거<br><code>nmap --script=smb-enum-shares,smb-os-discovery 표적</code> — SMB 공유·OS<br><code>nmap --script=ftp-anon 표적</code> — 익명 FTP 로그인 가능 여부</p><p><b>스크립트는 어디 있나:</b> <code>/usr/share/nmap/scripts/</code> 에 <code>.nse</code> 파일로 있습니다. <code>ls /usr/share/nmap/scripts/ | grep smb</code> 로 SMB 관련 스크립트를 찾을 수 있습니다.</p><p><b>주의:</b> <code>--script=vuln</code> 은 실제로 <b>공격을 시도</b>하는 것들이 섞여 있습니다. 표적을 다운시킬 수도 있으니 <b>허가된 대상에만</b>, 운영 시스템에는 신중히 쓰세요. NSE 는 강력한 만큼 시끄럽습니다(로그에 다 남습니다).</p>",
term:"kali@kali:~$ nmap -sC -sV --script=ftp-anon -p21 192.168.56.102\nPORT   STATE SERVICE VERSION\n21/tcp open  ftp     vsftpd 2.3.4\n| ftp-anon: Anonymous FTP login allowed (FTP code 230)\n|_-rw-r--r-- 1 0 0  107 Jun 12 backup.sql   # 익명 로그인 + 백업 파일!",
lab:["<code>nmap -sC 표적</code> 으로 기본 스크립트를 돌린다","<code>--script=ftp-anon</code> 으로 익명 FTP 가능 여부를 본다","<code>--script=http-enum</code> 으로 웹 디렉터리를 자동 열거한다","<code>ls /usr/share/nmap/scripts/</code> 로 스크립트 목록을 본다","<code>ls .../scripts/ | grep smb</code> 로 SMB 스크립트를 찾는다","<code>--script=vuln</code> 을 실습 표적에만 조심히 돌려본다","NSE로 찾은 정보를 공략 노트에 추가한다"],
q:[{t:"nmap <code>-sC</code> 는 무엇을 하는가?",o:["전 포트 스캔","기본 NSE 스크립트 묶음을 실행해 자동으로 정보를 수집한다","OS를 탐지한다","연결을 암호화한다"],a:1,
  e:"<code>-sC</code> = <b>기본 스크립트 실행</b>. 배너·HTTP 제목·익명 로그인 등을 자동 점검합니다. <code>-sV</code> 와 짝지어 <code>-sC -sV</code> 로 씁니다."},
   {t:"<code>--script=vuln</code> 을 운영 시스템에 함부로 쓰면 안 되는 이유는?",o:["느려서","실제 공격을 시도하는 스크립트가 섞여 있어 시스템을 다운시킬 수 있어서","불법이라서","결과가 부정확해서"],a:1,
    e:"<code>vuln</code> 카테고리에는 <b>실제 익스플로잇을 던지는</b> 스크립트가 있습니다. 표적이 죽을 수 있으니 허가·격리된 환경에서만 쓰세요."},
   {k:"cmd",t:"표적 <code>10.10.10.5</code> 의 포트 21에서 <b>익명 FTP 로그인 가능 여부</b>를 확인하는 nmap 명령을 입력하세요.",
    ph:"nmap --script=...","a":["nmap --script=ftp-anon -p21 10.10.10.5"],
    "re":["^nmap\\s+--script[=\\s]ftp-anon\\s+-p\\s*21\\s+10\\.10\\.10\\.5$","^nmap\\s+-p\\s*21\\s+--script[=\\s]ftp-anon\\s+10\\.10\\.10\\.5$"],
    hint:"스크립트 이름은 ftp-anon, 포트는 21로 좁힙니다.",
    e:"<code>nmap --script=ftp-anon -p21 10.10.10.5</code> — 익명 로그인이 되면 파일 목록까지 보여줍니다. 열거의 지름길입니다."}]},

{d:11,t:"웹 정찰 — 서버의 정체 파악",g:"웹 포트를 발견하면 어떤 기술로 만들어졌는지부터 알아낸다.",
c:"<p>포트 80·443 을 보면 웹입니다 — 실전 공격 표면의 대부분. 웹은 열거할 게 많아 며칠에 걸쳐 다룹니다. 오늘은 <b>서버의 정체 파악</b>입니다.</p><p><b>기술 스택 식별</b><br><code>whatweb http://표적</code> — 서버 종류(Apache/nginx), CMS(WordPress/Drupal), 프레임워크, 언어를 한 번에 알려줍니다.<br>브라우저 확장 <b>Wappalyzer</b> 도 같은 일을 합니다.</p><p><b>HTTP 헤더 읽기</b><br><code>curl -I http://표적</code><br><code>Server:</code>(웹서버 버전), <code>X-Powered-By:</code>(PHP 버전 등), 쿠키 이름(<code>PHPSESSID</code>=PHP, <code>JSESSIONID</code>=Java)이 정체를 드러냅니다.</p><p><b>기본 파일 확인</b><br><code>robots.txt</code> — 검색엔진에게 '보지 마라' 고 한 경로. <b>공격자에겐 지도</b>입니다. <code>Disallow: /admin</code> 이 대놓고 관리 페이지를 알려주는 격.<br><code>sitemap.xml</code> — 페이지 목록.<br><code>/.git/</code>, <code>/.env</code> — 실수로 노출된 소스·설정. 대박 단서.</p><p><b>페이지 소스 보기</b> — HTML 주석에 개발자 메모·비밀번호·숨은 경로가 있는 경우가 흔합니다. <code>view-source:</code> 또는 <code>curl</code> 로 원본을 봅니다.</p><p><b>요령:</b> 브라우저로 직접 열어보세요. 로그인 폼, 검색창, 업로드 기능, URL 파라미터(<code>?id=1</code>) — 이런 <b>입력 지점</b>이 나중에 인젝션의 표적이 됩니다. 어떤 입력이 있는지 지도부터 그립니다.</p>",
term:"kali@kali:~$ whatweb http://192.168.56.102\nhttp://192.168.56.102 [200 OK] Apache[2.2.8], PHP[5.2.4],\n  WordPress[4.1], Title[Example Blog]\nkali@kali:~$ curl -s http://192.168.56.102/robots.txt\nUser-agent: *\nDisallow: /admin/        # 관리 페이지를 알려준 셈\nDisallow: /backup/",
lab:["<code>whatweb</code> 로 표적 웹의 기술 스택을 식별한다","<code>curl -I</code> 로 HTTP 응답 헤더를 읽는다","<code>Server</code>·<code>X-Powered-By</code> 헤더에서 버전을 뽑는다","<code>robots.txt</code> 를 열어 숨은 경로를 찾는다","<code>/.git/</code> 나 <code>/.env</code> 노출 여부를 확인한다","페이지 소스의 HTML 주석을 읽어본다","웹의 모든 입력 지점(폼·검색·파라미터)을 목록화한다"],
q:[{t:"<code>robots.txt</code> 가 공격자에게 유용한 이유는?",o:["비밀번호가 들어 있어서","관리자가 숨기고 싶은 경로를 Disallow로 대놓고 알려줘서","취약점 목록이라서","서버를 다운시켜서"],a:1,
  e:"<code>Disallow: /admin</code> 은 검색엔진에게 '보지 마' 지만 공격자에겐 '여기 있다' 입니다. 숨기려던 경로가 오히려 <b>지도</b>가 됩니다."},
   {t:"<code>whatweb</code> 이나 Wappalyzer로 알아내는 것은?",o:["열린 포트","웹사이트를 구성하는 서버·CMS·프레임워크·언어","사용자 비밀번호","네트워크 대역"],a:1,
    e:"<b>기술 스택</b>을 식별합니다. WordPress 4.1 을 알면 그 버전의 알려진 취약점과 플러그인 공격으로 이어집니다."},
   {k:"cmd",t:"<code>http://10.10.10.5</code> 의 <b>HTTP 응답 헤더만</b> 받아 서버 정보를 보는 명령을 입력하세요.",
    ph:"curl ...","a":["curl -I http://10.10.10.5"],"re":["^curl\\s+-I\\s+http://10\\.10\\.10\\.5/?$"],
    hint:"헤더만 받는 대문자 옵션입니다.",
    e:"<code>curl -I http://10.10.10.5</code> — <code>Server:</code>, <code>X-Powered-By:</code> 헤더가 웹서버·언어 버전을 드러냅니다. 웹 정찰의 첫 명령입니다."}]},

{d:12,t:"디렉터리 브루트포스 — 숨은 경로 찾기",g:"링크로 이어지지 않은 숨은 디렉터리와 파일을 사전으로 찾아낸다.",
c:"<p>웹사이트의 <b>보이는 링크</b>는 빙산의 일각입니다. <code>/admin</code>, <code>/backup</code>, <code>/config.php.bak</code> 처럼 <b>링크는 없지만 존재하는</b> 경로가 널려 있습니다. 이걸 <b>사전 공격(단어 목록으로 하나씩 요청)</b>으로 찾습니다.</p><p><b>gobuster — 가장 많이 씁니다</b><br><code>gobuster dir -u http://표적 -w 단어목록.txt</code><br>단어목록의 각 단어를 URL 뒤에 붙여 요청하고, <b>200·301·403</b> 같은 응답이 오는 경로를 찾습니다.</p><p><b>확장자까지</b><br><code>gobuster dir -u http://표적 -w 목록.txt -x php,txt,bak,zip</code><br><code>-x</code> 로 각 단어에 확장자를 붙여봅니다. <code>config</code> → <code>config.php</code>, <code>config.bak</code>. 백업 파일에서 소스·비밀번호가 나오는 경우가 많습니다.</p><p><b>ffuf — 더 빠르고 유연</b><br><code>ffuf -u http://표적/FUZZ -w 목록.txt</code><br><code>FUZZ</code> 자리에 단어를 넣습니다. URL 어디든 넣을 수 있어 파라미터·서브도메인 퍼징에도 씁니다.</p><p><b>단어목록</b>은 Kali 의 <code>/usr/share/wordlists/</code> 에 있습니다. <b>SecLists</b> 가 사실상 표준입니다. <code>dirb/common.txt</code>(작고 빠름), <code>dirbuster/directory-list-2.3-medium.txt</code>(크고 철저).</p><p><b>응답 코드를 읽으세요.</b> <b>200</b> 존재·접근가능, <b>301/302</b> 리다이렉트(디렉터리인 경우 많음), <b>403</b> 존재하지만 접근금지(있다는 것 자체가 단서!), <b>404</b> 없음. <b>403 도 소중합니다</b> — 뭔가 있다는 뜻이니까요.</p>",
term:"kali@kali:~$ gobuster dir -u http://192.168.56.102 \\\n  -w /usr/share/wordlists/dirb/common.txt -x php,bak\n/admin      (Status: 301)\n/backup     (Status: 200)\n/config.php (Status: 200)\n/robots.txt (Status: 200)\n/.git       (Status: 403)   # 존재한다! 접근만 막힘",
lab:["<code>gobuster dir</code> 로 표적 웹의 숨은 디렉터리를 찾는다","<code>-x php,txt,bak</code> 로 확장자까지 탐색한다","<code>/usr/share/wordlists/</code> 에서 단어목록을 골라본다","응답 코드 200·301·403·404의 의미를 구분한다","403 이 나온 경로도 왜 단서인지 이해한다","<code>ffuf</code> 로 같은 작업을 <code>FUZZ</code> 로 해본다","찾은 숨은 경로를 전부 방문해 확인하고 기록한다"],
q:[{t:"디렉터리 브루트포스가 찾아내는 것은?",o:["비밀번호","링크로 연결되지 않은 숨은 디렉터리·파일","열린 포트","사용자 목록"],a:1,
  e:"단어목록으로 하나씩 요청해, <b>보이는 링크에는 없지만 서버에 존재하는</b> 경로를 찾습니다. <code>/admin</code>·<code>/backup</code> 이 대표적입니다."},
   {t:"gobuster 결과에서 <b>403</b> 응답이 나온 경로가 의미하는 것은?",o:["경로가 없다","경로가 존재하지만 접근이 금지되어 있다 — 뭔가 있다는 단서","서버 오류","리다이렉트"],a:1,
    e:"<b>403 = 존재하지만 접근 금지.</b> 없으면 404 가 옵니다. 뭔가 있으니 막아둔 것이고, 우회 방법을 찾을 가치가 있습니다."},
   {k:"cmd",t:"<code>http://10.10.10.5</code> 에서 단어목록 <code>common.txt</code>로 <b>디렉터리를 탐색</b>하는 gobuster 명령을 입력하세요. (목록 경로는 <code>common.txt</code>로만)",
    ph:"gobuster dir ...","a":["gobuster dir -u http://10.10.10.5 -w common.txt"],
    "re":["^gobuster\\s+dir\\s+-u\\s+http://10\\.10\\.10\\.5/?\\s+-w\\s+\\S*common\\.txt$","^gobuster\\s+dir\\s+-w\\s+\\S*common\\.txt\\s+-u\\s+http://10\\.10\\.10\\.5/?$"],
    hint:"모드는 dir, URL은 -u, 단어목록은 -w 입니다.",
    e:"<code>gobuster dir -u http://10.10.10.5 -w common.txt</code> — <code>dir</code> 모드가 디렉터리 탐색입니다. <code>-x</code> 로 확장자를 붙이면 백업 파일까지 찾습니다."}]},

{d:13,t:"서브도메인과 가상호스트 열거",g:"하나의 IP 뒤에 숨은 여러 사이트를 찾아낸다.",
c:"<p>하나의 도메인 뒤에는 <b>여러 서브도메인</b>이 있습니다. <code>www.</code> 만 보이지만 <code>admin.</code>, <code>dev.</code>, <code>api.</code>, <code>staging.</code> 이 숨어 있죠. <b>개발·관리용 서브도메인이 보안이 약한 경우가 많아</b> 좋은 표적입니다.</p><p><b>수동으로(Day 6 복습)</b> — crt.sh 인증서 로그, 구글 도킹 <code>site:*.example.com</code>.</p><p><b>능동 열거 도구</b><br><code>ffuf -u http://표적 -H \"Host: FUZZ.example.com\" -w 목록.txt</code><br><code>gobuster vhost -u http://표적 -w 목록.txt</code><br>사전의 각 단어를 서브도메인으로 시도합니다.</p><p><b>가상호스트(vhost) 개념</b> — 한 서버(한 IP)가 <code>Host:</code> 헤더에 따라 <b>다른 사이트를 보여줍니다.</b> <code>admin.example.com</code> 과 <code>www.example.com</code> 이 같은 IP 라도 내용이 다릅니다. DNS 에 등록 안 된 내부용 vhost 는 <code>Host</code> 헤더를 바꿔 요청해야만 보입니다.</p><p><b>이게 왜 중요한가:</b> 포트스캔은 IP 를 봅니다. 하지만 그 IP 의 <code>Host: internal-admin.corp</code> 에 로그인 없는 관리 패널이 있을 수 있습니다. IP 만 봐서는 절대 안 보이는 자산입니다.</p><p><b>CTF·실전 요령:</b> vhost 를 찾으면 <code>/etc/hosts</code> 에 <code>표적IP admin.example.com</code> 을 추가해 브라우저로 접근합니다. <b>응답 크기가 다른 것</b>을 찾는 게 핵심입니다 — 존재하지 않는 vhost 는 다 같은 기본 페이지를 주지만, 진짜 있는 것은 크기가 다릅니다(<code>ffuf -fs</code> 로 기본 크기를 걸러냅니다).</p>",
term:"kali@kali:~$ ffuf -u http://192.168.56.102 \\\n  -H \"Host: FUZZ.example.com\" -w subdomains.txt -fs 4242\n[Status: 200, Size: 8901] admin\n[Status: 200, Size: 5510] dev\n# admin.example.com 이 다른 크기 -> 진짜 존재",
lab:["crt.sh 에서 한 도메인의 서브도메인을 수집한다","<code>gobuster vhost</code> 로 가상호스트를 열거한다","<code>ffuf</code> 의 <code>Host: FUZZ</code> 방식으로 서브도메인을 찾는다","기본 응답 크기를 확인하고 <code>-fs</code> 로 걸러낸다","찾은 vhost 를 <code>/etc/hosts</code> 에 추가해 접속한다","서브도메인과 vhost 의 차이를 이해한다","발견한 서브도메인마다 어떤 사이트인지 기록한다"],
q:[{t:"개발·관리용 서브도메인(<code>dev.</code>·<code>admin.</code>)이 좋은 표적인 이유는?",o:["더 빠르다","운영 사이트보다 보안이 허술한 경우가 많다","항상 인증이 없다","IP가 다르다"],a:1,
  e:"개발·스테이징 환경은 <b>임시라는 이유로 보안이 느슨한 경우</b>가 많습니다. 기본 비밀번호, 디버그 모드, 오래된 버전이 흔합니다."},
   {t:"가상호스트(vhost) 열거가 포트스캔으로는 안 되는 이유는?",o:["포트가 닫혀서","같은 IP가 Host 헤더에 따라 다른 사이트를 주는데, 포트스캔은 IP만 보기 때문","암호화되어서","방화벽 때문"],a:1,
    e:"한 IP·한 포트라도 <code>Host</code> 헤더가 다르면 다른 사이트가 나옵니다. DNS에 없는 내부 vhost 는 <b>헤더를 바꿔 요청해야만</b> 드러납니다."},
   {t:"vhost 퍼징에서 <code>ffuf -fs 4242</code> 의 <code>-fs</code> 가 하는 일은?",o:["속도 제한","응답 크기 4242인 것을 걸러내(존재하지 않는 기본 응답 제거) 진짜만 남김","포트 지정","파일 저장"],a:1,
    e:"존재하지 않는 vhost 는 모두 같은 <b>기본 페이지(같은 크기)</b>를 줍니다. 그 크기를 <code>-fs</code> 로 필터링하면 <b>크기가 다른 진짜 vhost</b>만 남습니다."}]},

{d:14,t:"SMB 열거 — 윈도우 공유의 보물창고",g:"파일 공유 서비스에서 공유 폴더·사용자·정책을 캐낸다.",
c:"<p>포트 <b>139·445</b>(SMB)를 보면 <b>파일 공유</b>입니다. 주로 윈도우지만 리눅스의 Samba 도 씁니다. SMB 는 <b>열거의 보물창고</b>입니다 — 공유 폴더에 백업·비밀번호·설정파일이 굴러다니고, 사용자 목록·비밀번호 정책까지 나옵니다.</p><p><b>enum4linux — SMB 열거의 스위스 army knife</b><br><code>enum4linux -a 192.168.56.102</code><br><code>-a</code> 는 전부. 사용자 목록, 공유 목록, 그룹, 비밀번호 정책, OS 정보를 한 번에 뽑습니다.</p><p><b>공유 목록 보기</b><br><code>smbclient -L //192.168.56.102 -N</code><br><code>-L</code> 목록, <code>-N</code> 비밀번호 없이(익명). 익명으로 공유가 보이면 절반은 성공입니다.</p><p><b>공유 접속</b><br><code>smbclient //192.168.56.102/공유이름 -N</code><br>들어가서 <code>ls</code>, <code>get 파일</code> 로 파일을 내려받습니다. FTP 처럼 씁니다.</p><p><b>nmap 스크립트</b><br><code>nmap --script=smb-enum-shares,smb-enum-users,smb-os-discovery -p445 표적</code></p><p><b>왜 SMB 가 노른자인가:</b> 내부망에서 SMB 는 어디에나 있고, <b>익명(null 세션) 접근</b>이 허용된 경우가 많습니다. 공유 폴더의 <code>passwords.xlsx</code>, <code>backup.sql</code>, 스크립트 안의 하드코딩된 자격증명 — 이런 게 초기 침투의 열쇠가 됩니다. EternalBlue(MS17-010) 같은 SMB 취약점도 여기서 확인합니다.</p>",
term:"kali@kali:~$ smbclient -L //192.168.56.102 -N\n    Sharename       Type      Comment\n    ---------       ----      -------\n    backups         Disk      Nightly backups\n    IPC$            IPC       Remote IPC\nkali@kali:~$ smbclient //192.168.56.102/backups -N\nsmb: \\> ls\n  db_backup.sql     A    40211  Mon Jun 12\nsmb: \\> get db_backup.sql   # 백업을 그대로 획득",
lab:["<code>enum4linux -a 표적</code> 으로 전체 열거를 돌린다","<code>smbclient -L //표적 -N</code> 로 공유 목록을 익명으로 본다","익명 접근되는 공유가 있으면 <code>smbclient</code> 로 들어간다","공유 안의 파일을 <code>get</code> 으로 내려받는다","<code>nmap --script=smb-enum-shares</code> 로 교차 확인한다","<code>nmap --script=smb-os-discovery</code> 로 OS를 알아낸다","찾은 공유·사용자·파일을 전부 기록한다"],
q:[{t:"포트 445(SMB) 열거에서 얻을 수 있는 것이 아닌 것은?",o:["공유 폴더 목록","사용자 목록과 비밀번호 정책","공유 안의 파일","서버의 CPU 온도"],a:3,
  e:"SMB 열거는 <b>공유·사용자·정책·파일</b>을 드러냅니다. 익명 접근이 되면 백업·자격증명이 그대로 나오는 경우가 많습니다."},
   {t:"'null 세션(익명 SMB 접근)' 이 위험한 이유는?",o:["느려서","인증 없이 공유·사용자 정보에 접근할 수 있어 정보가 줄줄 새서","암호화가 안 돼서","포트가 열려서"],a:1,
    e:"null 세션은 <b>비밀번호 없이</b> SMB 정보를 조회하는 것입니다. 사용자 목록·공유가 노출되고, 공유 안 파일까지 읽히면 초기 침투로 직결됩니다."},
   {k:"cmd",t:"표적 <code>10.10.10.5</code> 의 SMB <b>공유 목록을 익명(비밀번호 없이)</b>으로 나열하는 명령을 입력하세요.",
    ph:"smbclient ...","a":["smbclient -L //10.10.10.5 -N"],
    "re":["^smbclient\\s+-L\\s+//10\\.10\\.10\\.5/?\\s+-N$","^smbclient\\s+-N\\s+-L\\s+//10\\.10\\.10\\.5/?$"],
    hint:"목록은 -L, 익명(비번 없음)은 -N 입니다.",
    e:"<code>smbclient -L //10.10.10.5 -N</code> — <code>-N</code>(no password)으로 익명 접근을 시도합니다. 공유가 보이면 <code>smbclient //IP/공유 -N</code> 으로 들어갑니다."}]},

{d:15,t:"기타 서비스 열거 — FTP·SSH·SNMP·SMTP",g:"웹·SMB 외의 흔한 서비스에서 각각 무엇을 캐내는지 익힌다.",
c:"<p>포트마다 열거 방법이 다릅니다. 자주 만나는 나머지 서비스들을 정리합니다.</p><p><b>FTP (21)</b><br>가장 먼저 <b>익명 로그인</b>을 시도합니다. <code>ftp 표적</code> → 아이디 <code>anonymous</code>, 비번 아무거나. 되면 파일을 뒤집니다. 버전도 확인하세요 — <code>vsftpd 2.3.4</code> 는 유명한 백도어 버전입니다.</p><p><b>SSH (22)</b><br>버전을 봅니다(<code>nc 표적 22</code> 로 배너). 약한 비밀번호 추측, 유출된 개인키가 관건. 사용자명을 알면 나중에 무차별 대입의 표적이 됩니다.</p><p><b>SNMP (161, UDP)</b><br><b>정보 유출의 왕</b>입니다. <b>community string</b>(기본값 <code>public</code>)만 알면 시스템 정보가 통째로 나옵니다 — 실행 프로세스, 사용자, 네트워크 연결, 설치 소프트웨어.<br><code>snmpwalk -v2c -c public 표적</code><br><code>onesixtyone</code> 으로 community string 을 추측합니다.</p><p><b>SMTP (25)</b><br>사용자 존재 여부를 확인할 수 있습니다. <code>VRFY 사용자</code> 명령에 서버가 있다/없다를 답하면 <b>유효한 사용자명 목록</b>을 만들 수 있습니다. <code>smtp-user-enum</code> 도구를 씁니다.</p><p><b>공통 원리:</b> 각 서비스는 <b>인증 전에도</b> 흘리는 정보가 있습니다. 배너, 버전, 익명 접근, 사용자 존재 확인. 이 조각들을 모으면 초기 침투의 재료가 됩니다. <b>어떤 포트든 열거 방법이 따로 있다</b>는 걸 기억하세요.</p>",
term:"kali@kali:~$ snmpwalk -v2c -c public 192.168.56.102 | head -4\nSNMPv2-MIB::sysDescr.0 = Linux target 3.2.0 x86_64\nHOST-RESOURCES-MIB::hrSWRunName.4 = \"mysqld\"\nHOST-RESOURCES-MIB::hrSWRunName.9 = \"apache2\"\n# 실행 중인 프로세스가 통째로 노출",
lab:["<code>ftp 표적</code> 으로 익명 로그인을 시도한다","<code>nc 표적 22</code> 로 SSH 배너(버전)를 확인한다","<code>snmpwalk -v2c -c public 표적</code> 으로 SNMP 정보를 뽑는다","<code>onesixtyone</code> 으로 community string 을 추측해본다","<code>smtp-user-enum</code> 개념(VRFY)을 이해한다","각 서비스가 인증 전에 흘리는 정보를 정리한다","서비스별 열거 치트시트를 만든다"],
q:[{t:"SNMP(161)가 '정보 유출의 왕' 이라 불리는 이유는?",o:["가장 빠른 프로토콜이라","기본 community string(public)만 알면 프로세스·사용자·네트워크 정보가 통째로 나와서","암호화가 강해서","포트가 여러 개라서"],a:1,
  e:"SNMP v1/v2c 는 <code>public</code> 이라는 기본 비밀번호로 <b>시스템 내부 정보를 대량 노출</b>합니다. snmpwalk 한 방에 실행 프로세스·사용자가 줄줄이 나옵니다."},
   {t:"FTP 서비스를 만났을 때 가장 먼저 시도할 것은?",o:["즉시 익스플로잇","익명(anonymous) 로그인과 버전 확인","포트를 닫기","비밀번호 변경"],a:1,
    e:"<b>익명 로그인</b>이 되면 파일을 바로 뒤질 수 있습니다. 그리고 <code>vsftpd 2.3.4</code> 같은 버전은 알려진 백도어가 있어 버전 확인이 필수입니다."},
   {t:"SMTP의 <code>VRFY</code> 명령이 공격자에게 유용한 이유는?",o:["메일을 보낼 수 있어서","서버가 사용자 존재 여부를 답해줘 유효한 사용자명 목록을 만들 수 있어서","비밀번호를 알려줘서","암호화를 깨서"],a:1,
    e:"<code>VRFY bob</code> 에 서버가 '있다/없다' 를 답하면, <b>유효한 사용자명</b>을 수집할 수 있습니다. 이 목록이 나중에 무차별 대입·피싱의 표적이 됩니다."}]},

{d:16,t:"취약점 찾기 — 버전에서 익스플로잇으로",g:"열거로 알아낸 버전을 알려진 취약점과 공개 익스플로잇에 연결한다.",
c:"<p>정찰과 열거로 <b>버전 번호</b>를 모았습니다. 이제 그걸 <b>알려진 취약점(CVE)</b>과 <b>공개 익스플로잇</b>에 연결합니다. 이게 정찰이 침투로 넘어가는 다리입니다.</p><p><b>searchsploit — 오프라인 익스플로잇 검색</b><br><code>searchsploit apache 2.2.8</code><br>Kali 에 내장된 Exploit-DB 사본을 검색합니다. 소프트웨어+버전으로 검색하면 해당 익스플로잇이 나옵니다.<br><code>searchsploit -m 12345</code> 로 익스플로잇 코드를 현재 폴더로 복사합니다.</p><p><b>웹 취약점 스캐너 — nikto</b><br><code>nikto -h http://표적</code><br>웹 서버의 알려진 문제를 자동 점검합니다 — 오래된 버전, 위험한 파일, 오설정. 시끄럽지만(로그에 다 남음) 빠르게 큰 그림을 줍니다.</p><p><b>버전 → CVE 검색</b><br>구글에 <code>\"소프트웨어 버전\" exploit</code> 또는 <code>\"소프트웨어 버전\" CVE</code>. Exploit-DB, GitHub, CVE 데이터베이스를 봅니다.</p><p><b>익스플로잇을 쓰기 전 반드시:</b><br>① <b>코드를 읽어보세요.</b> 인터넷의 익스플로잇에는 악성 코드가 숨어 있을 수 있습니다 — 당신을 노리는.<br>② <b>버전이 정확히 맞는지</b> 확인. 안 맞으면 표적이 죽을 수 있습니다.<br>③ 실습·허가 환경에서만.</p><p><b>이 코스의 다음 단계:</b> ACT 1 부터 실제 침투(웹 취약점, 익스플로잇)로 들어갑니다. ACT 0 은 여기까지 — <b>완벽한 정찰로 공격 표면과 약점 목록을 완성</b>하는 게 목표입니다. 잘 정찰하면 침투는 따라옵니다.</p>",
term:"kali@kali:~$ searchsploit vsftpd 2.3.4\n-------------------------------------- ----------------\n Exploit Title                         Path\n-------------------------------------- ----------------\nvsftpd 2.3.4 - Backdoor Command Exec   unix/remote/49757\n-------------------------------------- ----------------\nkali@kali:~$ searchsploit -m 49757   # 코드를 복사해 읽어본다",
lab:["<code>searchsploit</code> 로 열거에서 찾은 버전을 검색한다","나온 익스플로잇을 <code>-m</code> 으로 복사해 코드를 읽어본다","<code>nikto -h http://표적</code> 으로 웹을 자동 점검한다","버전 하나를 구글에 '<code>버전 exploit</code>' 로 검색한다","Exploit-DB(exploit-db.com)에서 같은 걸 찾아본다","익스플로잇을 쓰기 전 확인할 3가지를 적는다","정찰 결과: 공격 표면 + 약점 목록을 완성한다"],
q:[{t:"<code>searchsploit</code> 이 하는 일은?",o:["포트를 스캔한다","Kali 내장 Exploit-DB에서 소프트웨어·버전에 맞는 공개 익스플로잇을 찾는다","비밀번호를 크랙한다","웹을 크롤링한다"],a:1,
  e:"열거로 얻은 <b>버전 번호</b>를 넣으면 그에 맞는 익스플로잇을 오프라인으로 검색합니다. 정찰→침투를 잇는 핵심 도구입니다."},
   {t:"인터넷에서 받은 익스플로잇 코드를 실행 전 반드시 읽어봐야 하는 이유는?",o:["더 빨라져서","악성 코드가 숨어 당신(공격자)을 노릴 수 있고, 버전이 안 맞으면 표적을 죽일 수 있어서","법으로 정해져서","용량이 커서"],a:1,
    e:"공개 익스플로잇에 <b>백도어가 심긴</b> 경우가 실제로 있습니다 — 초보 해커를 노린. 그리고 버전이 안 맞으면 표적이 손상됩니다. <b>항상 코드를 읽고</b> 쓰세요."},
   {k:"cmd",t:"<code>searchsploit</code> 으로 <b>vsftpd 2.3.4</b> 의 알려진 익스플로잇을 검색하는 명령을 입력하세요.",
    ph:"searchsploit ...","a":["searchsploit vsftpd 2.3.4"],"re":["^searchsploit\\s+vsftpd\\s+2\\.3\\.4$"],
    hint:"도구 이름 뒤에 소프트웨어와 버전을 씁니다.",
    e:"<code>searchsploit vsftpd 2.3.4</code> — 이 버전은 유명한 <b>백도어 명령 실행</b> 취약점이 있습니다. 정찰에서 이 버전을 본 순간 게임이 끝난 셈입니다."}]},

{d:17,t:"Burp Suite 입문 — 웹 트래픽을 손에 쥐다",g:"브라우저와 서버 사이의 모든 요청을 가로채고 조작하는 도구를 익힌다.",
c:"<p>웹 공격의 필수 도구가 <b>Burp Suite</b> 입니다. 브라우저와 서버 사이에 앉아 <b>모든 HTTP 요청을 가로채고, 보고, 바꿔서</b> 다시 보낼 수 있습니다. 웹 해킹의 절반이 이 도구 위에서 일어납니다.</p><p><b>프록시 개념</b> — 브라우저 → <b>Burp</b> → 서버. Burp 가 중간에서 트래픽을 잡습니다. 브라우저가 보내는 진짜 요청, 서버가 주는 진짜 응답을 날것으로 봅니다.</p><p><b>설정</b> — 브라우저 프록시를 <code>127.0.0.1:8080</code> 으로. Kali 는 FoxyProxy 확장이나 내장 브라우저를 씁니다. HTTPS 를 보려면 Burp CA 인증서를 설치합니다.</p><p><b>핵심 기능</b><br><b>Proxy → Intercept</b> — 요청을 멈춰 세워 <b>수정 후</b> 보냅니다. 폼의 숨은 값, 가격, 권한 파라미터를 바꿔치기.<br><b>HTTP History</b> — 오간 모든 요청 기록. 앱이 뒤에서 뭘 하는지 다 보입니다.<br><b>Repeater</b> — 요청 하나를 <b>반복해서 조금씩 바꿔</b> 보냅니다. 인젝션 테스트의 핵심.<br><b>Intruder</b> — 자동화된 반복 공격(무차별 대입·퍼징). 무료판은 느립니다.</p><p><b>왜 결정적인가:</b> 브라우저는 앱이 '보여주고 싶은 것' 만 보여줍니다. Burp 는 <b>실제로 오가는 것</b>을 보여줍니다. 클라이언트 검증은 우회하고(요청을 직접 바꾸니까), 숨은 파라미터를 드러내고, 서버의 진짜 반응을 봅니다. <b>웹은 결국 요청과 응답</b>이고, Burp 는 그걸 손에 쥐여줍니다.</p><p>대안으로 <b>OWASP ZAP</b>(무료·오픈소스)이 있습니다. 기능이 비슷하고 Intruder 에 해당하는 것도 무료입니다.</p>",
term:"# Burp Repeater 에서 요청을 직접 편집\nGET /profile?user_id=1 HTTP/1.1      <- 이걸\nGET /profile?user_id=2 HTTP/1.1      <- 이렇게 바꿔 보내면?\nHost: target\n\n# 남의 프로필이 보이면 -> 접근통제 취약점(IDOR)",
lab:["Burp Suite(또는 ZAP)를 실행한다","브라우저 프록시를 127.0.0.1:8080 으로 설정한다","HTTPS를 보기 위해 Burp CA 인증서를 설치한다","HTTP History 에서 로그인 요청을 관찰한다","Intercept 로 요청을 멈춰 파라미터를 바꿔 보낸다","한 요청을 Repeater로 보내 반복 편집해본다","클라이언트 검증(자바스크립트)을 Burp로 우회할 수 있음을 확인한다"],
q:[{t:"Burp Suite 같은 프록시 도구가 웹 공격에 결정적인 이유는?",o:["웹사이트를 더 빠르게 로드해서","브라우저가 보여주는 것이 아니라 실제로 오가는 요청·응답을 보고 조작할 수 있어서","비밀번호를 자동 입력해서","바이러스를 막아서"],a:1,
  e:"브라우저는 앱이 '보여주려는 것' 만 보입니다. Burp 는 <b>실제 HTTP 요청/응답</b>을 드러내고, 요청을 직접 바꿔 클라이언트 검증을 우회하고 숨은 파라미터를 조작합니다."},
   {t:"Burp의 <b>Repeater</b> 기능은 무엇에 쓰는가?",o:["요청을 반복해서 조금씩 바꿔 보내며 서버 반응을 테스트","비밀번호를 저장","화면을 녹화","포트를 스캔"],a:0,
    e:"<b>Repeater</b> 는 요청 하나를 잡아 <b>파라미터를 바꿔가며 반복 전송</b>합니다. SQL 인젝션·파라미터 조작 테스트의 중심 도구입니다."},
   {t:"클라이언트 측 자바스크립트 입력 검증(예: '숫자만 입력')을 Burp로 우회할 수 있는 이유는?",o:["Burp가 자바스크립트를 해킹해서","검증은 브라우저에서만 돌고, Burp는 그 이후의 요청을 직접 조작하기 때문","서버가 검증을 안 해서","암호화를 깨서"],a:1,
    e:"클라이언트 검증은 <b>브라우저 안에서만</b> 동작합니다. Burp는 브라우저를 떠난 <b>요청 자체를 수정</b>하므로 그 검증을 그냥 지나칩니다. 그래서 서버 측 검증이 반드시 필요하다는 교훈이 나옵니다."}]},

{d:18,t:"정찰 자동화와 결과 정리",g:"흩어진 정찰 결과를 하나로 모으고, 반복 작업을 자동화한다.",
c:"<p>정찰은 명령을 수십 개 칩니다. 결과가 흩어지면 놓칩니다. <b>모으고 정리하는 것</b>도 실력입니다.</p><p><b>한 번에 여러 도구 — 자동화 프레임워크</b><br><b>AutoRecon</b> — 표적 하나를 주면 nmap → 서비스별 열거(gobuster·enum4linux·nikto)를 <b>알아서 순서대로</b> 돌리고 결과를 폴더로 정리합니다.<br><code>autorecon 192.168.56.102</code><br>다만 <b>자동화에 의존하지 마세요.</b> 도구가 놓치는 걸 사람이 봐야 합니다. 자동화는 시작점이지 끝이 아닙니다.</p><p><b>결과 저장 습관</b><br>표적별 폴더를 만듭니다: <code>mkdir -p 10.10.10.5/{nmap,web,smb,loot}</code><br>nmap 은 <code>-oA</code>, 다른 도구는 <code>| tee 파일</code> 로 화면과 파일에 동시 저장(Day 방어 코스에서 배운 <code>tee</code>).</p><p><b>공격 표면 지도 그리기</b><br>정찰이 끝나면 한 장으로 정리합니다:<br>· 열린 포트와 서비스·버전<br>· 웹: 발견한 경로·입력 지점·기술 스택<br>· 자격증명: 찾은 사용자명·비밀번호·키<br>· 약점 후보: 버전별 CVE·오설정<br>· <b>다음 행동</b>: 어디를 먼저 칠까</p><p><b>정찰의 목표는 '완전한 그림'입니다.</b> 이 그림이 정확할수록 침투가 빠르고, 부실할수록 헤맵니다. 좋은 공격자는 정찰 노트만 봐도 어디가 약한지 짚어냅니다.</p><p><b>스크립트로 반복 줄이기:</b> 자주 쓰는 스캔 조합을 셸 스크립트로 만들어두면(방어 코스에서 배운 셸 스크립트) 표적마다 한 줄로 정찰을 시작할 수 있습니다.</p>",
term:"kali@kali:~$ mkdir -p 10.10.10.5/{nmap,web,loot}\nkali@kali:~$ nmap -sC -sV -oA 10.10.10.5/nmap/tcp 10.10.10.5\nkali@kali:~$ gobuster dir -u http://10.10.10.5 -w common.txt \\\n  | tee 10.10.10.5/web/gobuster.txt\n# 표적별로 정리되어 나중에 다시 보기 쉽다",
lab:["표적별 폴더 구조를 만든다 (nmap·web·smb·loot)","nmap 을 <code>-oA</code> 로 세 형식 저장한다","다른 도구 출력을 <code>| tee</code> 로 파일에 함께 저장한다","AutoRecon 을 실습 표적에 돌려본다","자주 쓰는 스캔 조합을 셸 스크립트로 만든다","공격 표면 지도를 한 장으로 정리한다","'다음에 어디를 칠까' 우선순위를 매긴다"],
q:[{t:"정찰 자동화 도구(AutoRecon 등)를 쓸 때 주의할 점은?",o:["항상 완벽하다","자동화가 놓치는 것을 사람이 직접 봐야 한다 — 시작점이지 끝이 아니다","불법이다","느리다"],a:1,
  e:"자동화는 <b>표준 점검을 빠르게</b> 해주지만, 미묘한 단서는 놓칩니다. 결과를 사람이 읽고 더 파고드는 게 실력입니다. 자동화에 의존하면 남들도 찾는 것만 찾습니다."},
   {t:"정찰 결과를 표적별 폴더로 정리하는 이유로 가장 적절한 것은?",o:["디스크를 아끼려고","흩어진 결과에서 단서를 놓치지 않고, 나중 단계에서 다시 참조하기 위해","도구가 요구해서","속도를 높이려고"],a:1,
    e:"정찰은 명령이 수십 개입니다. 정리 안 하면 <b>찾은 걸 잊습니다.</b> 초기에 스친 버전·사용자명이 나중에 열쇠가 되니, 체계적 저장이 곧 실력입니다."},
   {t:"'공격 표면 지도' 에 들어가야 할 항목이 아닌 것은?",o:["열린 포트·서비스·버전","찾은 자격증명과 입력 지점","약점 후보(CVE·오설정)","표적 관리자의 취미"],a:3,
    e:"공격 표면 지도는 <b>포트·서비스·버전·경로·자격증명·약점 후보·다음 행동</b>을 담습니다. 침투 단계에서 바로 꺼내 쓸 실전 정보만 모읍니다."}]},

{d:19,t:"OPSEC — 조용히 움직이기",g:"공격이 얼마나 시끄러운지 이해하고, 탐지를 염두에 둔 정찰을 한다.",
c:"<p>방어자를 공부하셨으니 이건 유리합니다. <b>공격은 흔적을 남깁니다.</b> 당신이 SOC에서 잡아내던 그 흔적을, 이제 <b>남기지 않으려는</b> 쪽에서 봅니다. 이걸 <b>OPSEC</b>(Operational Security, 작전 보안)이라 합니다.</p><p><b>정찰은 생각보다 시끄럽습니다.</b><br><code>nmap -T5 -p-</code> 는 방화벽·IDS 에 <b>수만 개의 연결 시도</b>로 잡힙니다. 당신이 방어 코스에서 배운 '포트 스캔 탐지(S0 상태 폭증)' 가 바로 이겁니다.<br><code>--script=vuln</code> 이나 nikto 는 로그에 <b>공격 시그니처</b>를 그대로 남깁니다.<br>gobuster 는 짧은 시간에 <b>수천 개의 404</b>를 만듭니다 — 방어 코스의 '404 폭증 = 디렉터리 브루트포스' 가 이겁니다.</p><p><b>조용히 하려면</b><br>· 스캔 속도를 낮춘다(<code>-T2</code> 이하, <code>--max-rate</code>).<br>· 필요한 포트만 본다(전 포트 스캔은 시끄럽다).<br>· 능동 정찰 전에 <b>수동 정찰</b>을 최대한 한다(흔적 없음).<br>· 요청 사이 지연을 준다(<code>--scan-delay</code>).</p><p><b>중요한 균형:</b> 실습·CTF 에서는 OPSEC 이 필요 없습니다 — 빠르게 <code>-T4 -p-</code> 로 다 봅니다. 하지만 <b>탐지 대응 훈련(레드팀 vs 블루팀)</b>이나 실전 모의해킹에서는 조용함이 핵심입니다. <b>상황에 맞게 시끄러움을 조절</b>하는 게 프로입니다.</p><p><b>방어자의 눈으로 자신을 보세요.</b> '내가 방금 친 이 명령이 SOC 대시보드에 어떻게 보일까?' 이 질문을 던질 수 있는 사람이, 탐지를 피하는 공격도 탐지하는 방어도 잘합니다. 당신의 방어 경력이 여기서 무기가 됩니다.</p>",
term:"# 같은 정찰, 다른 소음\nnmap -T5 -p- 표적      # 빠름. SOC 대시보드에 빨간불\nnmap -T2 -p80,443 표적  # 느림. 정상 트래픽에 섞임\n\n# 방어 코스에서 잡던 그 지표를 이제 안 만들려 한다\n# 404 폭증, S0 폭증, 공격 시그니처 = 나의 흔적",
lab:["<code>-T5</code> 와 <code>-T2</code> 스캔이 로그에 어떻게 다른지 생각해 적는다","gobuster 가 만드는 404 폭증을 방어자 시점에서 설명한다","수동 정찰이 왜 흔적이 없는지 정리한다","실습/CTF 와 실전에서 OPSEC 필요성의 차이를 구분한다","<code>--scan-delay</code> 로 느린 스캔을 시험한다","'내 명령이 SOC에 어떻게 보일까' 를 nmap·gobuster 각각에 대해 적는다","방어 경력이 공격에 어떻게 유리한지 3줄로 정리한다"],
q:[{t:"gobuster 디렉터리 브루트포스가 방어자에게 잘 탐지되는 이유는?",o:["느려서","짧은 시간에 수천 개의 404 응답을 만들어 로그에서 튀기 때문","암호화를 안 해서","IP를 숨겨서"],a:1,
  e:"존재하지 않는 경로를 대량 요청하니 <b>404가 폭증</b>합니다. 방어 코스에서 배운 그 지표입니다 — 공격자가 되어보니 왜 그게 신호인지 명확해집니다."},
   {t:"OPSEC(작전 보안)을 특히 신경 써야 하는 상황은?",o:["혼자 하는 CTF","실전 모의해킹이나 레드팀 대 블루팀 훈련","picoCTF 연습","로컬 실습실"],a:1,
    e:"CTF·실습은 시끄러워도 됩니다. 하지만 <b>탐지팀이 있는 실전·훈련</b>에서는 조용함이 성패를 가릅니다. 상황에 맞게 소음을 조절하는 게 프로입니다."},
   {t:"방어(블루팀) 경력이 공격에 유리한 이유로 가장 적절한 것은?",o:["도구를 더 잘 알아서","자기 공격이 방어자에게 어떻게 보이는지 알기 때문에 탐지를 피하고 우회할 수 있어서","비밀번호를 알아서","더 빨라서"],a:1,
    e:"'내 흔적이 SOC에 어떻게 보일까' 를 아는 사람이 <b>탐지를 피하는 공격</b>을 설계합니다. 방어를 아는 공격자가 가장 위험하고, 공격을 아는 방어자가 가장 강합니다."}]},

{d:20,t:"[정찰 종합] 표적 하나를 완전히 열거하라",g:"배운 정찰 기법을 전부 이어 붙여, 표적 하나의 공격 표면을 완성한다.",boss:true,
c:"<p><b>ACT 0 을 마쳤습니다.</b> 오늘은 배운 것을 전부 이어, 표적 하나를 <b>처음부터 끝까지</b> 정찰합니다. 실제 CTF 를 푸는 순서 그대로입니다.</p><p><b>표준 공략 순서 — 이걸 몸에 익히세요:</b></p><p><b>1. 호스트 발견</b> — <code>nmap -sn</code> 으로 살아있는지.<br><b>2. 전 포트 스캔</b> — <code>nmap -p- 표적</code> 으로 열린 포트 전부.<br><b>3. 깊은 스캔</b> — <code>nmap -sC -sV -p&lt;찾은포트&gt;</code> 으로 버전·기본 스크립트.<br><b>4. 서비스별 열거</b> — 웹이면 <code>whatweb</code>+<code>gobuster</code>, SMB면 <code>enum4linux</code>, FTP면 익명 로그인…<br><b>5. 약점 찾기</b> — 버전마다 <code>searchsploit</code>, 웹은 <code>nikto</code>.<br><b>6. 정리</b> — 공격 표면 지도 완성, 다음 행동 결정.</p><p><b>막히면? Enumerate more.</b> 답은 항상 아직 안 본 곳에 있습니다 — 안 본 포트, 안 판 디렉터리, 안 읽은 버전, 안 뒤진 공유.</p><p><b>이 순서가 ACT 0 의 전부입니다.</b> 다음 ACT 부터는 이 정찰 위에서 <b>실제 침투</b>(웹 취약점, 익스플로잇, 권한 상승)를 합니다. 잘 정찰된 표적은 이미 절반 뚫린 겁니다.</p><p>축하합니다. 이제 표적을 보면 <b>어디서 시작할지</b> 압니다. 그게 공격자의 첫 번째 실력입니다.</p>",
term:"# 표적 하나, 완전 정찰 — 이 순서를 외운다\n$ nmap -sn 10.10.10.5              # 살아있나\n$ nmap -p- --min-rate 1000 10.10.10.5   # 포트 전부\n$ nmap -sC -sV -p22,80,445 10.10.10.5   # 깊게\n$ whatweb http://10.10.10.5       # 웹 정체\n$ gobuster dir -u http://10.10.10.5 -w common.txt\n$ enum4linux -a 10.10.10.5        # SMB\n$ searchsploit <찾은 버전>        # 약점\n# -> 공격 표면 지도 완성",
lab:["실습 표적 하나를 골라 <code>nmap -sn</code> 으로 살아있는지 확인한다","<code>nmap -p-</code> 로 열린 포트를 전부 찾는다","찾은 포트에 <code>nmap -sC -sV</code> 로 깊은 스캔을 건다","웹이 있으면 <code>whatweb</code>+<code>gobuster</code> 로 열거한다","SMB가 있으면 <code>enum4linux -a</code> 로 열거한다","찾은 모든 버전을 <code>searchsploit</code> 으로 검색한다","공격 표면 지도를 한 장으로 완성한다","막힐 때마다 'Enumerate more' 를 실천한다","ACT 0 명령 20개를 자기만의 정찰 치트시트로 정리한다"],
q:[{t:"표적 하나를 처음 받았을 때 올바른 첫 단계는?",o:["바로 익스플로잇을 던진다","호스트 발견과 전 포트 스캔으로 공격 표면을 먼저 파악한다","비밀번호를 무차별 대입한다","웹을 바로 해킹한다"],a:1,
  e:"<b>정찰부터.</b> 뭐가 열려 있는지 모르고 공격할 수 없습니다. <code>nmap -sn</code> → <code>-p-</code> → <code>-sC -sV</code> → 서비스별 열거 순서가 정석입니다."},
   {t:"CTF나 침투에서 '풀 게 없다' 며 막혔을 때 가장 옳은 대응은?",o:["표적을 바꾼다","포기한다","Enumerate more — 아직 안 본 포트·디렉터리·버전·공유를 더 판다","무작정 익스플로잇을 다 던진다"],a:2,
    e:"<b>답은 거의 항상 아직 안 본 곳에 있습니다.</b> 전 포트를 봤나? 모든 웹 경로를 팠나? 모든 서비스를 열거했나? 막힘의 90%는 열거 부족입니다."},
   {k:"cmd",t:"공략의 첫 명령 — 표적 <code>10.10.10.5</code> 의 <b>모든 포트</b>를 스캔하는 nmap 명령을 입력하세요.",
    ph:"nmap ...","a":["nmap -p- 10.10.10.5"],"re":["^nmap\\s+-p-\\s+(--min-rate\\s*\\d+\\s+)?10\\.10\\.10\\.5$"],
    hint:"전 포트 옵션 하나면 됩니다.",
    e:"<code>nmap -p- 10.10.10.5</code> — 여기서 나온 포트를 <code>-sC -sV</code> 로 깊게 파고, 서비스별로 열거하면 정찰 완성입니다. <b>ACT 1 에서 이 정찰 위에 실제 침투를 올립니다.</b> 수고하셨습니다."}]}

]}
];
