# -*- coding: utf-8 -*-
"""기존 1~120일차에 실습과 직접입력형 문제를 덧붙이는 패치.

build_data.py 가 이 파일을 읽어 각 일차에 병합한다.
원본 커리큘럼(content/act1~5.js)은 건드리지 않는다 — 그래서 되돌리기 쉽다.

  EXTRA_LABS[일차] = ["실습 항목", ...]      -> 뒤에 추가
  EXTRA_Q[일차]    = [{...문제...}, ...]     -> 뒤에 추가
  DAY_FILES[일차]  = [{n,p,d}, ...]          -> 첨부 파일
  DAY_FLAGS[일차]  = {"lab_mode":True, "mins":45}
"""

# ─────────────────────────────────────────────────────────────
# ACT 1 · 관제실 입문 (1~20)
# ─────────────────────────────────────────────────────────────
EXTRA_LABS = {
21: ["블루팀 관련 한국어 커뮤니티나 뉴스레터를 하나 구독한다",
    "MITRE ATT&CK 사이트에 들어가 매트릭스를 한 번 훑는다 (지금은 이해 못 해도 됨)",
    "이 코스를 언제 할지 하루 30분 시간대를 정해 달력에 넣는다"],
22: ["<code>sudo du -sh /var/log/*</code> 로 어떤 로그가 용량을 많이 쓰는지 본다",
    "<code>zgrep 'Failed' /var/log/auth.log.*.gz 2>/dev/null | head</code> 로 압축 로그를 검색해본다",
    "<code>sudo cat /etc/rsyslog.conf | grep -v '^#' | grep .</code> 로 로그 전송 설정을 확인한다",
    "자기 서버의 로그 보관 기간이 며칠인지 확정해 적어둔다"],
23: ["<code>grep -n 'sshd' /var/log/auth.log | head</code> 로 줄 번호와 함께 출력해본다",
    "<code>grep -w 'root' /var/log/auth.log | head</code> 와 <code>grep 'root'</code> 결과를 비교한다",
    "자주 쓸 grep 옵션 6개를 치트시트 파일에 정리한다"],
24: ["<code>awk -F: '{print $1, $3}' /etc/passwd | head</code> 로 구분자 지정을 연습한다",
    "<code>awk 'NR>=10 && NR<=20' /var/log/syslog</code> 로 줄 범위를 잘라본다",
    "<code>awk '{print NF}' /var/log/auth.log | sort -u | head</code> 로 줄마다 필드 수가 다른지 확인한다"],
25: ["<code>ps aux | awk '{print $1}' | sort | uniq -c | sort -rn</code> 로 사용자별 프로세스 수를 센다",
    "<code>uniq -d</code> 와 <code>uniq -u</code> 의 차이를 직접 실행해 확인한다",
    "<code>sort -k2 -rn</code> 처럼 특정 열 기준 정렬을 연습한다"],
26: ["<code>grep 'Failed' /var/log/auth.log | tail -100 | awk '{print $1,$2}' | uniq -c</code> 로 날짜별 집계",
    "<code>cut -c1-15</code> 로 문자 위치 기준 자르기를 해본다",
    "파이프라인 결과를 <code>&gt; result.txt</code> 로 저장하고 <code>tee</code> 와 비교해본다"],
27: ["<code>journalctl --since today --until now -p warning</code> 로 오늘 경고 이상만 본다",
    "<code>journalctl -o json-pretty -n 1</code> 로 저널의 실제 필드 구조를 본다",
    "<code>journalctl _UID=0 --since '1 hour ago'</code> 처럼 필드 필터를 써본다",
    "<code>journalctl --vacuum-time=30d</code> 가 무엇을 하는지 문서로 확인한다 (실행은 신중히)"],
28: ["<code>grep 'Failed password' /var/log/auth.log | awk '{print $1,$2,$3}' | cut -c1-14 | uniq -c</code> 로 시간대별 분포를 본다",
    "<code>lastb | head -20</code> 로 실패한 로그인 기록을 본다 (btmp)",
    "<code>last -20</code> 로 성공한 로그인 세션을 본다",
    "fail2ban 이 설치돼 있는지 확인하고 없다면 역할을 조사한다"],
29: ["<code>getent group sudo</code> 또는 <code>getent group wheel</code> 로 sudo 그룹원을 확인한다",
    "<code>sudo -l</code> 로 내가 실행 가능한 sudo 명령을 확인한다",
    "<code>find / -perm -2000 -type f 2>/dev/null | head</code> 로 SGID 파일도 찾아본다",
    "SUID 목록을 <code>suid-baseline.txt</code> 로 저장해 기준선을 만든다"],
30: ["<code>ss -s</code> 로 소켓 요약 통계를 본다",
     "<code>ps -eo pid,ppid,user,etime,cmd --sort=start_time | tail -20</code> 로 최근 시작된 프로세스를 본다",
     "<code>lsof -i -P -n | head -20</code> 으로 네트워크를 쓰는 프로세스를 나열한다",
     "정상 상태를 <code>ps auxf > baseline-ps.txt</code> 로 저장해둔다"],
31: ["<code>ls -la /etc/cron.hourly/ /etc/cron.weekly/ /etc/cron.monthly/</code> 도 확인한다",
     "<code>systemctl list-unit-files --state=enabled | head -30</code> 으로 활성 서비스를 본다",
     "<code>cat /etc/rc.local 2>/dev/null</code> 와 <code>ls /etc/profile.d/</code> 를 확인한다",
     "<code>for u in $(cut -d: -f1 /etc/passwd); do sudo crontab -l -u $u 2>/dev/null; done</code> 로 전 사용자 크론을 훑는다"],
32: ["<code>md5sum</code>, <code>sha1sum</code>, <code>sha256sum</code> 을 같은 파일에 실행해 길이를 비교한다",
     "<code>find /usr/bin -newermt '30 days ago' -type f 2>/dev/null | head</code> 로 최근 변경된 바이너리를 찾는다",
     "<code>debsums -c 2>/dev/null | head</code> 또는 <code>rpm -Va | head</code> 로 패키지 무결성을 검사한다",
     "중요 파일의 해시 목록을 만들어 기준선으로 저장한다"],
33: ["<code>ss -tan state time-wait | wc -l</code> 로 TIME-WAIT 소켓 수를 센다",
     "<code>cat /proc/net/tcp | head</code> 를 열어 커널이 보는 원본 형태를 확인한다",
     "TCP 플래그 6종을 카드로 만들어 외운다"],
34: ["<code>sudo iptables -L -n -v --line-numbers</code> 로 규칙 번호까지 확인한다",
     "<code>sudo nft list ruleset > fw-baseline.txt</code> 로 현재 정책을 저장한다",
     "아웃바운드 정책이 기본 허용인지 기본 거부인지 확인하고 의미를 적는다",
     "'인바운드만 막고 아웃바운드는 다 열어둔' 구성의 위험을 3줄로 쓴다"],
35: ["<code>dig +short A github.com</code> 와 <code>dig +short AAAA github.com</code> 을 비교한다",
     "<code>dig @1.1.1.1 example.com</code> 처럼 리졸버를 지정해본다",
     "<code>cat /etc/resolv.conf</code> 로 내 서버가 어느 DNS를 쓰는지 확인한다",
     "<code>dig +short TXT _dmarc.naver.com</code> 로 실제 TXT 레코드를 본다"],
36: ["<code>curl -I https://example.com</code> 로 응답 헤더만 받아본다",
     "<code>curl -A 'sqlmap/1.7' https://example.com -o /dev/null -s -w '%{http_code}\\n'</code> 로 UA를 바꿔본다",
     "<code>awk '{print $12}' access.log | sort | uniq -c | sort -rn | head</code> 로 User-Agent 순위를 낸다",
     "상태코드 4xx·5xx만 골라내는 파이프라인을 만든다"],
37: ["<code>openssl s_client -connect example.com:443 -servername example.com </dev/null 2>/dev/null | grep -E 'subject|issuer'</code> 실행",
     "<code>curl -vI https://expired.badssl.com 2>&1 | grep -i 'certificate'</code> 로 만료 인증서 반응을 본다",
     "자체 서명 인증서를 하나 만들어보고 브라우저 경고를 확인한다"],
38: ["<code>date +%s</code> 로 유닉스 타임을 얻고 <code>date -d @&lt;숫자&gt;</code> 로 되돌려본다",
     "<code>TZ=UTC date</code> 와 <code>TZ=Asia/Seoul date</code> 를 비교한다",
     "<code>chronyc tracking</code> 또는 <code>timedatectl show-timesync</code> 로 NTP 동기 상태를 본다",
     "로그 3종의 시각 포맷을 ISO 8601 로 변환하는 스크립트를 짜본다"],
39: ["regex101.com 에서 IPv4·SHA256·Base64 패턴을 각각 테스트한다",
     "<code>grep -oP '(?&lt;=user )\\w+' /var/log/auth.log | sort -u | head</code> 로 lookbehind 를 써본다",
     "<code>.*</code> 를 남발한 패턴과 좁힌 패턴의 실행 시간을 <code>time</code> 으로 비교한다"],
40: ["첨부된 <code>lab-auth.log</code> 와 <code>lab-access.log</code> 를 내려받는다",
     "실패 로그인 상위 IP를 뽑고, 그 IP가 성공 목록에도 있는지 대조한다",
     "성공 시각 이후의 sudo·useradd 기록을 전부 추출한다",
     "웹 로그에서 404를 가장 많이 낸 IP를 찾고 auth.log 의 IP와 같은지 확인한다",
     "200 응답을 받은 <code>.php</code> 경로를 찾아 웹셸을 특정한다",
     "발견한 사실을 UTC 타임라인 표로 정리한다",
     "IOC 목록(IP·계정·파일 경로)을 만든다"],
}

# ─────────────────────────────────────────────────────────────
# ACT 2 · 패킷의 눈 (21~40)
# ─────────────────────────────────────────────────────────────
EXTRA_LABS.update({
41: ["<code>sudo tcpdump -i any -n -c 5 -A</code> 로 페이로드를 ASCII 로 함께 본다",
     "<code>sudo tcpdump -i any -n -w /tmp/rot.pcap -C 1 -W 3</code> 로 순환 저장을 실습한다",
     "<code>capinfos /tmp/cap.pcap</code> 로 캡처 파일 요약 정보를 본다"],
42: ["<code>sudo tcpdump -i any -n 'host 8.8.8.8'</code> 를 켜둔 채 다른 창에서 ping 을 날려본다",
     "<code>sudo tcpdump -i any -n 'net 10.0.0.0/8'</code> 로 대역 필터를 써본다",
     "잘못된 BPF 문법을 일부러 넣어 에러 메시지를 확인한다"],
43: ["Wireshark 에서 <code>ip.addr == 8.8.8.8 && dns</code> 복합 필터를 걸어본다",
     "Statistics → IO Graph 로 시간에 따른 트래픽 추이를 본다",
     "자주 쓸 디스플레이 필터 10개를 북마크(즐겨찾기)에 등록한다",
     "<code>frame contains \"password\"</code> 로 평문 문자열을 검색해본다"],
44: ["<code>tshark -r cap.pcap -qz conv,tcp</code> 로 대화 통계를 CLI 로 뽑는다",
     "<code>tshark -r cap.pcap --export-objects http,/tmp/out</code> 로 파일을 추출한다",
     "추출한 파일에 <code>.malware</code> 확장자를 붙이는 습관을 연습한다"],
45: ["<code>tcp.analysis.flags</code> 필터로 Wireshark 가 표시한 이상을 전부 본다",
     "<code>tcp.window_size == 0</code> 로 Zero Window 를 찾아본다",
     "'성능 이상'과 '보안 이상'을 구분하는 판단 기준 3가지를 적는다"],
46: ["<code>nmap -sT</code> 와 <code>nmap -sS</code> 를 각각 캡처해 패킷 수 차이를 비교한다 (본인 VM 한정)",
     "<code>nmap -sU -p 53,123,161</code> 로 UDP 스캔을 돌려보고 느린 이유를 확인한다",
     "각 스캔 유형별 Suricata 탐지 여부를 확인한다"],
47: ["<code>ip -s neigh</code> 로 ARP 엔트리 상태를 본다",
     "<code>arping -c 3 &lt;게이트웨이IP&gt;</code> 로 응답이 몇 개 오는지 확인한다",
     "게이트웨이 MAC 을 정적 ARP 로 고정하는 방법을 조사한다"],
48: ["<code>ping -c 3 -p 41424344 8.8.8.8</code> 로 페이로드 패턴을 지정해 보낸다",
     "<code>tcpdump -i any -n 'icmp and greater 200'</code> 로 큰 ICMP 만 잡는다",
     "네트워크의 DHCP 서버 IP를 확인하고 인가된 것인지 대조한다"],
49: ["<code>tshark -r cap.pcap -Y 'dns' -T fields -e dns.qry.name | awk '{print length($0), $0}' | sort -rn | head</code>",
     "도메인별 고유 서브도메인 수를 세는 파이프라인을 완성한다",
     "정상 도메인과 터널링 도메인의 질의 길이 분포를 비교해본다"],
50: ["<code>tshark -r cap.pcap -Y 'dns.flags.rcode == 3' -T fields -e dns.qry.name | head -30</code>",
     "호스트별 NXDOMAIN 개수를 세는 명령을 만든다",
     "문자열 엔트로피를 계산하는 파이썬 함수를 짜서 DGA 후보에 적용한다"],
51: ["특정 목적지의 연결 시각을 뽑아 간격을 계산하는 스크립트를 짠다",
     "간격의 표준편차와 평균을 구해 변동계수(CV)를 계산한다",
     "자기 PC 의 정상 웹 트래픽 CV 와 비교해본다",
     "jitter 20% 를 넣어도 CV 로 구분되는지 직접 계산해본다"],
52: ["<code>tshark -r cap.pcap -Y 'tls.handshake.type==1' -T fields -e tls.handshake.ja3</code> 로 JA3 를 뽑는다",
     "브라우저·curl·python 으로 각각 접속해 JA3 가 다른지 확인한다",
     "환경 내 JA3 희귀도 분석 파이프라인을 만들어본다"],
53: ["<code>tshark -r cap.pcap -Y 'smb2' -T fields -e smb2.filename | sort -u | head</code>",
     "워크스테이션 간 445 통신을 차단하는 방화벽 규칙을 작성해본다",
     "RDP(3389) 접속을 시간대별로 집계하는 쿼리를 만든다"],
54: ["<code>cat conn.log | zeek-cut -d ts id.orig_h id.resp_h duration | head</code> 로 사람이 읽는 시각으로 본다",
     "<code>conn_state</code> 값 12종의 의미를 표로 정리한다",
     "uid 하나를 골라 여러 로그에서 <code>grep</code> 해 사건을 재구성한다"],
55: ["<code>cat ssl.log | zeek-cut server_name validation_status | sort | uniq -c | sort -n | head</code>",
     "<code>cat files.log | zeek-cut sha256 | sort -u | wc -l</code> 로 오간 고유 파일 수를 센다",
     "files.log 의 해시 하나를 골라 VirusTotal 에 <b>해시로만</b> 조회해본다"],
56: ["<code>cat notice.log | zeek-cut note | sort | uniq -c | sort -rn</code> 로 notice 유형 분포를 본다",
     "Zeek Intel Framework 용 IOC 파일을 형식에 맞게 하나 만들어본다",
     "긴 DNS 질의를 탐지하는 Zeek 스크립트를 작성해 실행해본다"],
57: ["Emerging Threats 룰셋을 받아 <code>wc -l</code> 로 규모를 확인한다",
     "<code>suricata -T -c /etc/suricata/suricata.yaml</code> 로 설정 검증을 해본다",
     "<code>cat out/eve.json | jq -r 'select(.event_type==\"alert\") | .alert.signature'</code> 로 알럿을 본다"],
58: ["작성한 룰을 <code>suricata -T</code> 로 문법 검증한다",
     "정상 트래픽 pcap 을 하나 준비해 오탐 테스트를 돌린다",
     "오탐이 난 조건을 좁혀 재검증하고 변경 이력을 기록한다",
     "완성한 룰 3개를 Git 저장소에 커밋한다"],
59: ["<code>ls -lh cap.pcap conn.log</code> 로 pcap 과 Zeek 로그의 용량 차이를 직접 본다",
     "하루치 트래픽 기준으로 각 방식의 1년 저장 비용을 계산해본다",
     "자기 환경의 보존 정책을 문서 한 장으로 작성한다"],
60: ["첨부된 <code>lab-conn.log</code> 와 <code>lab-dns.log</code> 를 내려받는다",
     "<code>conn_state</code> 가 S0 인 연결의 출발지를 세어 스캐너를 특정한다",
     "그 스캐너가 몇 개 포트를 훑었는지 센다",
     "443 목적지별 연결 간격의 변동계수를 계산해 비컨을 찾는다",
     "orig_bytes 가 가장 큰 연결을 찾아 유출 규모를 MB 로 환산한다",
     "NXDOMAIN 응답 수를 세고 DGA 여부를 판단한다",
     "등록도메인별 고유 서브도메인 수를 세어 터널링 도메인을 찾는다",
     "발견 사실을 타임라인과 IOC 목록으로 정리한다"],
})
