# -*- coding: utf-8 -*-
"""ACT 3~5 (41~100일) 실습 추가 패치. patches.py 의 이어지는 부분."""

MORE_LABS = {
# ── ACT 3 · 엔드포인트 감시 (41~60) ──
41: ["ATT&CK Navigator 를 열어 빈 레이어를 하나 만들어본다",
     "자기 산업을 노리는 위협 그룹을 하나 골라 사용 기법을 확인한다",
     "Tactic 14개를 순서대로 외워 적어본다"],
42: ["<code>Get-Process | Group-Object Name | Sort-Object Count -Desc | Select -First 15</code> 실행",
     "<code>Get-CimInstance Win32_Process | Select ProcessId,ParentProcessId,Name</code> 로 부모-자식을 뽑는다",
     "정상 프로세스 트리를 캡처해 baseline 폴더에 저장한다"],
43: ["<code>Get-WinEvent -ListLog Security | Select MaximumSizeInBytes,LogMode</code> 로 보존 설정을 본다",
     "Security 로그 최대 크기를 1GB 이상으로 늘린다",
     "<code>wevtutil epl Security C:\\temp\\sec.evtx</code> 로 로그를 내보내본다"],
44: ["Logon Type 별 개수를 세는 PowerShell 한 줄을 완성한다",
     "4625 이벤트에서 Sub Status 코드를 추출해 분포를 본다",
     "Logon Type 11종 치트시트를 만들어 저장한다"],
45: ["그룹 정책에서 프로세스 생성 감사와 커맨드라인 기록을 켠다",
     "<code>Where-Object</code> 방식과 <code>-FilterHashtable</code> 방식의 실행 시간을 <code>Measure-Command</code> 로 비교한다",
     "의심스러운 부모-자식 조합 10개 목록을 만든다"],
46: ["Sysmon 채널 최대 크기를 1GB 로 늘린다",
     "<code>sysmon64 -c</code> 로 현재 적용된 설정을 확인한다",
     "sysmon-modular 저장소를 열어 ATT&CK 태깅 방식을 확인한다"],
47: ["ID 별 발생 건수를 세어 가장 시끄러운 이벤트를 찾는다",
     "ID 1 이벤트에서 Hashes 필드를 추출해본다",
     "ID 3 과 방화벽 로그의 차이를 실제 데이터로 비교한다"],
48: ["<code>[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes('whoami'))</code> 로 인코딩해본다",
     "그것을 <code>powershell -enc</code> 로 실행하고 4104 에 원본이 남는지 확인한다",
     "난독화 기법 4가지를 직접 만들어보고 4104 로그를 비교한다"],
49: ["LOLBAS 에서 Execute 기능이 있는 바이너리 10개를 목록으로 만든다",
     "각각에 대한 의심 인자 조합을 정리한다",
     "자기 PC 에서 이 바이너리들의 최근 실행 이력을 확인한다"],
50: ["Autoruns 결과를 baseline 파일로 저장한다",
     "<code>Get-ScheduledTask | Where State -ne Disabled | Select TaskName,TaskPath</code> 실행",
     "<code>Get-WmiObject -Namespace root\\subscription -Class __EventFilter</code> 로 WMI 구독을 확인한다"],
51: ["Sysmon ID 10 에서 lsass 대상 이벤트만 필터링한다",
     "정상적으로 lsass 에 접근하는 프로세스 화이트리스트를 만든다",
     "<code>Get-CimInstance Win32_DeviceGuard</code> 로 Credential Guard 상태를 확인한다"],
52: ["<code>whoami /all</code> 로 그룹과 권한을 전부 본다",
     "UAC 우회 기법이 건드리는 레지스트리 키를 조사해 적는다",
     "정찰 명령 연쇄를 탐지하는 룰 조건을 작성한다"],
53: ["각 내부 이동 기법의 흔적을 이벤트 ID 표로 정리한다",
     "이벤트 4648(명시적 자격증명 사용)을 조회해본다",
     "'계정×호스트 신규 조합' 탐지 쿼리를 작성한다"],
54: ["AD 환경이 있다면 SPN 이 설정된 계정을 나열해본다",
     "BloodHound 를 설치하고 샘플 데이터로 공격 경로를 시각화한다",
     "AD 용어 15개 사전을 만든다"],
55: ["4769 이벤트에서 암호화 타입 분포를 집계한다",
     "짧은 시간 내 다수 SPN 요청을 찾는 쿼리를 작성한다",
     "gMSA 로 서비스 계정을 전환하는 방법을 정리한다"],
56: ["시간대별 이벤트 발생량을 세어 공백 구간을 찾는 스크립트를 짠다",
     "System 로그의 104(로그 삭제) 이벤트도 확인한다",
     "4104 에서 amsi 관련 문자열을 검색한다"],
57: ["비밀번호 걸린 압축 생성을 탐지하는 커맨드라인 조건을 작성한다",
     "Sysmon ID 11 에서 대용량 파일 생성을 찾는 방법을 정리한다",
     "허용·차단할 클라우드 스토리지 도메인 목록을 만든다"],
58: ["vssadmin·wbadmin·bcdedit 탐지를 하나의 룰로 합쳐 작성한다",
     "랜섬웨어 킬체인 9단계를 ATT&CK Tactic 에 매핑한다",
     "각 단계별로 자기 환경의 가시성 유무를 표시한다"],
59: ["Eric Zimmerman 도구 모음을 한 폴더에 정리한다",
     "<code>PECmd.exe -d C:\\Windows\\Prefetch --csv .</code> 로 Prefetch 를 파싱한다",
     "각 아티팩트가 무엇을 증명하는지 요약표를 만든다"],
60: ["첨부된 <code>day60-sysmon.csv</code> 를 내려받는다",
     "WINWORD 를 부모로 가진 프로세스를 찾아 최초 실행을 특정한다",
     "EventID 22·3 에서 C2 도메인과 IP를 추출한다",
     "EventID 13 에서 지속성 레지스트리 값을 찾는다",
     "EventID 10 에서 lsass 에 접근한 프로세스를 찾는다",
     "WmiPrvSE 를 부모로 가진 프로세스로 내부 이동을 확인한다",
     "vssadmin 실행 시각을 찾아 랜섬웨어 직전 단계를 특정한다",
     "전체를 ATT&CK 기법으로 태깅한 타임라인으로 정리한다"],

# ── ACT 4 · 탐지 엔지니어링 (61~80) ──
61: ["자기 환경의 로그 소스별 일일 볼륨을 추정해 표로 만든다",
     "같은 의미인데 이름이 다른 필드 사례 5쌍을 찾는다",
     "'로그 창고'가 되지 않으려면 무엇이 필요한지 3줄로 쓴다"],
62: ["Docker 로 Elasticsearch 와 Kibana 를 띄운다",
     "Elastic detection-rules 저장소를 클론해 룰 개수를 센다",
     "각 구성요소의 역할을 한 줄씩 정리한다"],
63: ["Kibana Discover 에서 필드 목록을 열어 타입을 확인한다",
     "<code>GET /_cat/indices?v</code> 로 인덱스 목록과 용량을 본다",
     "keyword 와 text 필드에 같은 검색어를 넣어 결과 차이를 확인한다"],
64: ["KQL 쿼리 10개를 작성해 실행한다",
     "필드 값을 클릭해 필터를 추가하는 방식을 익힌다",
     "ACT 3 에서 배운 탐지 아이디어 5개를 KQL 로 옮긴다"],
65: ["'Failed Logon by Source IP' 표 시각화를 만든다",
     "시간별 이벤트 추이 막대 차트를 만든다",
     "대시보드 각 패널에 '어떤 결정을 위한 것인지' 설명을 단다"],
66: ["Splunk Free 를 설치하거나 BOTS 데이터셋 실습 환경에 접속한다",
     "<code>index=* | stats count by sourcetype</code> 로 데이터 현황을 파악한다",
     "리눅스 파이프라인과 SPL 을 나란히 놓은 대조표를 만든다"],
67: ["임계치를 정하기 전에 분포를 측정하는 쿼리를 먼저 작성한다",
     "percentile 함수로 상위 1% 기준값을 구해본다",
     "각 탐지 쿼리에서 오탐이 날 정상 시나리오를 3개씩 적는다"],
68: ["ECS 필드 레퍼런스에서 process·user·source 카테고리를 읽는다",
     "자기 로그 필드를 ECS 이름으로 매핑하는 표를 만든다",
     "OCSF 와 ECS 의 차이를 3줄로 요약한다"],
69: ["SigmaHQ 저장소를 클론한다",
     "windows/process_creation 폴더의 룰 10개를 읽는다",
     "각 룰의 falsepositives 섹션에서 공통 패턴을 정리한다"],
70: ["작성한 룰에 ATT&CK tags 와 falsepositives 를 반드시 채운다",
     "Day 48·49 의 탐지 아이디어를 Sigma 로 옮긴다",
     "룰을 Git 에 커밋하고 메시지에 작성 근거를 적는다"],
71: ["sigma-cli 를 설치하고 플러그인을 추가한다",
     "자기 룰을 splunk 와 lucene 두 형식으로 변환한다",
     "변환된 쿼리의 필드명이 자기 환경과 맞는지 확인하고 매핑을 조정한다"],
72: ["자기 룰을 30일치 데이터에 돌려 알럿 수를 센다",
     "알럿 20건을 검토해 TP/FP 를 분류하고 precision 을 계산한다",
     "튜닝 전후 precision 을 기록해 비교한다"],
73: ["트리아지 체크리스트를 자기 버전으로 만든다",
     "'좋은 종결 사유'와 '나쁜 종결 사유' 예시를 3개씩 적는다",
     "알럿에서 룰 개선으로 이어지는 피드백 루프를 그림으로 그린다"],
74: ["detection-rules 저장소를 만들고 지금까지의 룰을 전부 커밋한다",
     "README 에 룰 작성 규칙과 리뷰 절차를 적는다",
     "GitHub Actions 로 Sigma 문법 검증 워크플로를 만든다"],
75: ["테스트 VM 을 준비하고 스냅샷을 뜬다",
     "<code>Invoke-AtomicTest T1059.001 -ShowDetails</code> 로 내용을 먼저 확인한다",
     "실행 후 '로그 없음 / 룰 없음 / 룰 오류' 중 무엇인지 판별해 기록한다"],
76: ["Pyramid of Pain 을 그리고 자기 룰을 각 층에 배치한다",
     "IOC 층 룰과 TTP 층 룰의 비율을 계산한다",
     "TTP 층으로 올릴 수 있는 룰을 골라 개선안을 쓴다"],
77: ["MISP 데모 인스턴스를 둘러본다",
     "STIX 형식 IOC 샘플을 열어 구조를 확인한다",
     "TLP 4단계와 각각의 사용 상황을 정리한다"],
78: ["ATT&CK Navigator 에서 자기 룰이 커버하는 기법을 색칠한다",
     "가장 큰 사각지대 Tactic 3개를 찾아 우선순위를 정한다",
     "DeTT&CT 의 데이터 소스 품질 평가 항목을 확인한다"],
79: ["TheHive·Cortex 문서를 읽고 케이스 구조를 파악한다",
     "트리아지 절차에서 자동화 가능한 단계를 표시한다",
     "'자동화하면 위험한 조치' 3가지와 이유를 정리한다"],
80: ["선택한 위협의 ATT&CK 페이지와 실제 사고 리포트를 읽는다",
     "탐지 가설을 한 문장으로 적는다",
     "필요한 로그가 실제로 수집되는지 먼저 확인한다",
     "Sigma 룰을 작성하고 자기 SIEM 쿼리로 변환한다",
     "Atomic Red Team 으로 정탐을 검증한다",
     "최근 30일 정상 데이터로 오탐을 검증하고 튜닝한다",
     "L1 이 볼 트리아지 가이드를 '확인할 것 5가지'로 작성한다",
     "룰과 문서를 Git 에 커밋한다"],

# ── ACT 5 · 침해대응과 포렌식 (81~100) ──
81: ["NIST SP 800-61 의 4단계 그림을 직접 그려본다",
     "초동 대응 금지사항 3가지를 카드로 만들어 눈에 띄는 곳에 둔다",
     "'준비 단계 체크리스트' 10개 항목을 작성한다"],
82: ["Order of Volatility 7단계를 순서대로 외워 적는다",
     "증거 수집 기록 양식(누가·언제·무엇을·해시)을 만든다",
     "Write Blocker 의 원리를 조사해 3줄로 정리한다"],
83: ["KAPE 를 내려받아 테스트 VM 에서 !SANS_Triage 를 실행한다",
     "수집 결과의 폴더 구조를 살펴본다",
     "WinPmem 으로 메모리를 덤프해 다음 실습용으로 준비한다"],
84: ["FTK Imager 로 USB 하나를 이미징한다",
     "이미징 전후 해시를 비교해 무결성을 검증한다",
     "BitLocker 환경의 포렌식 대응 방법을 조사해 정리한다"],
85: ["MFTECmd 로 $MFT 를 파싱한다",
     "SI 와 FN 타임스탬프를 비교해 불일치 파일을 찾아본다",
     "USN 저널을 파싱해 최근 파일 활동을 확인한다"],
86: ["SIFT Workstation 또는 Plaso 를 설치한다",
     "log2timeline 으로 타임라인을 만들고 CSV 로 출력한다",
     "Timeline Explorer 로 특정 시각 전후 5분을 필터링해본다"],
87: ["Registry Explorer 로 NTUSER.DAT 를 연다",
     "UserAssist·USBSTOR·RunMRU·TypedPaths 를 각각 확인한다",
     "각 키가 무엇을 증명하는지 요약표를 만든다"],
88: ["<code>sqlite3</code> 로 Chrome History 의 downloads 테이블을 조회한다",
     "LECmd 로 LNK 파일을 파싱해 원본 경로를 확인한다",
     "휴지통의 $I 파일을 파싱해본다"],
89: ["Volatility 3 를 설치한다",
     "<code>windows.pstree</code> 로 프로세스 계보를 확인한다",
     "pslist 와 psscan 결과를 비교해 차집합이 있는지 본다",
     "<code>windows.netscan</code> 으로 네트워크 연결을 확인한다"],
90: ["<code>windows.malfind</code> 를 실행해 의심 메모리 영역을 찾는다",
     "출력에서 MZ 헤더가 보이는 영역을 확인한다",
     "<code>windows.ldrmodules</code> 로 숨겨진 DLL 을 찾아본다"],
91: ["EICAR 테스트 파일로 <code>strings</code> 를 실행해본다",
     "PEStudio 또는 Detect It Easy 로 PE 구조를 살펴본다",
     "섹션 엔트로피를 확인해 패킹 여부를 판단한다"],
92: ["분석용 VM 을 만들고 스냅샷을 뜬다 (네트워크는 Host-only)",
     "Process Monitor 필터 설정을 익힌다",
     "INetSim 또는 FakeNet-NG 의 동작 원리를 정리한다",
     "Anti-VM 기법 5가지를 조사해 적는다"],
93: ["<code>ls -l /proc/*/exe 2>/dev/null | grep deleted</code> 를 실행해본다",
     "<code>docker diff</code> 로 컨테이너 변경 파일을 확인한다",
     "<code>docker inspect</code> 에서 Mounts 와 Privileged 를 점검한다",
     "컨테이너 탈출로 이어지는 위험 설정 4가지를 정리한다"],
94: ["CloudTrail 이벤트 JSON 샘플의 필드를 전부 확인한다",
     "'CloudTrail 비활성화 시도' 탐지 조건을 작성한다",
     "책임 공유 모델 그림을 그려본다"],
95: ["자기 메일 원본 헤더를 열어 Received 체인을 아래에서 위로 읽는다",
     "Authentication-Results 헤더에서 SPF·DKIM·DMARC 결과를 찾는다",
     "<code>dig TXT _dmarc.도메인</code> 으로 실제 DMARC 정책을 조회한다",
     "유사 도메인 예시를 5개 만들어본다"],
96: ["봉쇄·근절·복구 각 단계의 체크리스트를 만든다",
     "'언제 격리할 것인가' 판단 기준 3가지를 정한다",
     "krbtgt 를 두 번 재설정해야 하는 이유를 조사해 정리한다"],
97: ["가상 사건 하나로 전체 보고서를 작성한다",
     "Executive Summary 를 기술 용어 없이 반 페이지로 쓴다",
     "권고사항 5개를 '누가·무엇을·언제까지' 형식으로 작성한다"],
98: ["MTTD·MTTR 의 정의를 자기 말로 정리한다",
     "'짝을 이뤄야 하는 지표' 조합 3쌍을 만든다",
     "위협 헌팅 가설 3개를 직접 세워본다"],
99: ["6개월 학습 계획을 자격증·플랫폼·포트폴리오 3축으로 작성한다",
     "GitHub 포트폴리오 저장소를 만들고 README 를 쓴다",
     "채용 공고 5개를 다시 읽고 Day 1 에 적은 키워드와 비교한다"],
100:["CyberDefenders 또는 BTLO 에서 랜섬웨어 시나리오를 하나 고른다",
     "초동 대응부터 사후 보고까지 전 과정을 순서대로 수행한다",
     "완전한 침해 사고 보고서를 작성한다",
     "이 사고에서 도출한 신규 탐지 룰 3개를 Sigma 로 작성하고 검증한다",
     "전 과정을 write-up 으로 정리해 공개한다",
     "Day 1 에 적었던 '6개월 뒤 되고 싶은 모습'을 다시 읽어본다"],
}
