# -*- coding: utf-8 -*-
"""CTF·DEF CON 스타일 문항 2부 — ACT 5~7 (포렌식·클라우드·헌팅).

포렌식은 CTF 에서 가장 비중이 큰 분야라 여기에 문항을 집중했다.
파일 카빙 · 스테가노그래피 · 메모리 · 문서형 멀웨어가 핵심이다.
"""
C = "cmd"
I = "input"

CTF_Q2 = {

# ═══════════ ACT 5 · 포렌식 (CTF 최대 분야) ═══════════
83:[{"k":C,"t":"파일 안에 숨겨진 다른 파일이 있는지 검사하고 <b>자동으로 추출</b>까지 하는 명령을 입력하세요. (파일 <code>cat.jpg</code>)",
     "ph":"binwalk ...","a":["binwalk -e cat.jpg"],
     "re":[r"^binwalk\s+(-e|--extract)\s+\S*cat\.jpg$"],
     "hint":"추출(extract) 옵션 한 글자입니다.",
     "e":"<code>binwalk -e cat.jpg</code> — CTF 스테가노그래피의 <b>1번 시도</b>입니다. 이미지 뒤에 ZIP 을 붙여둔 문제가 정말 많고, 이 한 줄이면 끝납니다."},
    {"k":I,"t":"이미지·문서의 촬영기기·GPS·작성자 같은 메타데이터를 읽는 CTF 필수 도구 이름은?",
     "ph":"도구 이름","a":["exiftool","ExifTool"],"re":["^exif\\s*tool$"],
     "hint":"EXIF + tool",
     "e":"<b>exiftool</b> — <code>exiftool photo.jpg</code>. Comment·Artist·GPS 필드에 플래그가 그냥 들어 있는 문제가 흔합니다. 실무에서는 <b>유출 문서의 작성자 추적</b>에 씁니다."}],
84:[{"k":I,"t":"파일시스템이 손상된 디스크 이미지에서 시그니처 기반으로 파일을 되살리는 것을 무엇이라 하나요? (한글)",
     "ph":"한글 용어","a":["카빙","파일 카빙","carving","file carving"],
     "re":["카빙|carving"],
     "hint":"'조각하다' 라는 뜻의 영어를 그대로 씁니다.",
     "e":"<b>파일 카빙</b>입니다. 매직 바이트로 시작과 끝을 찾아 잘라냅니다. 도구는 <code>foremost</code>, <code>scalpel</code>, <code>photorec</code>, <code>binwalk</code>."},
    {"k":C,"t":"디스크 이미지 <code>disk.img</code> 에서 파일을 카빙해 <code>out</code> 폴더에 저장하는 foremost 명령을 입력하세요.",
     "ph":"foremost ...","a":["foremost -i disk.img -o out"],
     "re":[r"^foremost\s+.*-i\s+\S*disk\.img.*-o\s+\S*out|^foremost\s+.*-o\s+\S*out.*-i\s+\S*disk\.img"],
     "hint":"입력(-i)과 출력(-o) 옵션을 씁니다.",
     "e":"<code>foremost -i disk.img -o out</code> — 결과가 타입별 폴더로 정리되어 나옵니다. <b>출력 폴더가 이미 있으면 실행을 거부</b>하니 비어 있어야 합니다."}],
85:[{"k":I,"t":"이미지의 각 픽셀 값 <b>가장 낮은 비트</b>에 데이터를 숨기는 스테가노그래피 기법의 약자는? (영문 3글자)",
     "ph":"영문 3글자","a":["LSB","lsb"],"re":["^lsb$"],
     "hint":"Least Significant Bit",
     "e":"<b>LSB</b> 입니다. 최하위 비트만 바꾸면 사람 눈에는 차이가 없습니다. PNG·BMP 에서 <code>zsteg</code>, <code>stegsolve</code> 로 풉니다."},
    {"k":I,"t":"PNG·BMP 파일의 LSB 스테가노그래피를 자동으로 훑어주는 루비 도구 이름은?",
     "ph":"도구 이름","a":["zsteg","Zsteg"],"re":["^zsteg$"],
     "hint":"steg 앞에 알파벳 한 글자가 붙습니다.",
     "e":"<b>zsteg</b> — <code>zsteg -a image.png</code> 로 모든 채널·비트 조합을 자동 시도합니다. JPG 는 구조가 달라 <code>steghide</code> 나 <code>stegseek</code> 를 씁니다."}],
86:[{"k":I,"t":"비밀번호로 보호된 steghide 파일을 워드리스트로 무차별 대입해 푸는 고속 도구 이름은?",
     "ph":"도구 이름","a":["stegseek","StegSeek"],"re":["^steg\\s*seek$"],
     "hint":"steghide 를 '찾아내는(seek)' 도구입니다.",
     "e":"<b>stegseek</b> — <code>stegseek file.jpg rockyou.txt</code>. 초당 수백만 개를 시도해서, 예전에는 몇 시간 걸리던 문제가 몇 초에 풀립니다."},
    {"k":I,"t":"CTF 에서 가장 널리 쓰이는 비밀번호 워드리스트 파일의 이름은? (확장자 포함)",
     "ph":"파일명","a":["rockyou.txt","rockyou"],"re":["^rockyou(\\.txt)?$"],
     "hint":"2009년 유출된 소셜 게임 사이트 이름입니다.",
     "e":"<b>rockyou.txt</b> — 2009년 RockYou 유출에서 나온 약 1,400만 개 비밀번호입니다. Kali 에 기본 포함되고, <b>실무 비밀번호 정책을 정할 때 근거 자료</b>로도 쓰입니다."}],
89:[{"k":I,"t":"Volatility 로 메모리 덤프에서 <b>레지스트리 하이브 목록</b>을 보는 플러그인 이름은? (Volatility 3 기준)",
     "ph":"플러그인","a":["windows.registry.hivelist","hivelist","registry.hivelist"],
     "re":["hive\\s*list"],
     "hint":"hive + list",
     "e":"<b>windows.registry.hivelist</b> 입니다. 여기서 하이브 주소를 얻어 <code>printkey</code> 나 <code>hashdump</code> 로 이어갑니다."},
    {"k":I,"t":"메모리 덤프에서 공격자가 cmd 창에 입력한 명령 이력을 복원하는 Volatility 플러그인은? (Volatility 3 기준, 이름만)",
     "ph":"플러그인 이름","a":["cmdline","consoles","windows.cmdline"],
     "re":["cmdline|consoles|cmdscan"],
     "hint":"명령줄(command line) 을 뜻하는 짧은 이름입니다.",
     "e":"<b>cmdline</b>(프로세스별 인자) 과 <b>consoles</b>(콘솔 히스토리 · vol2 의 cmdscan) 입니다. <b>공격자가 실제로 친 명령이 그대로 나와</b> CTF 에서 플래그가 여기 있는 경우가 많습니다."}],
90:[{"k":I,"t":"메모리에서 유저 계정 해시를 덤프하는 Volatility 플러그인 이름은?",
     "ph":"플러그인 이름","a":["hashdump","windows.hashdump"],"re":["hash\\s*dump"],
     "hint":"hash + dump",
     "e":"<b>hashdump</b> 입니다. SAM+SYSTEM 하이브를 메모리에서 찾아 NTLM 해시를 뽑습니다. 뽑은 해시는 hashcat <code>-m 1000</code> 으로 넘깁니다."},
    {"k":I,"t":"메모리 덤프에서 특정 프로세스의 실행 파일을 디스크로 꺼내는 Volatility 3 플러그인은?",
     "ph":"플러그인 이름","a":["windows.dumpfiles","dumpfiles","windows.pslist --dump"],
     "re":["dump\\s*files|pslist.*dump"],
     "hint":"파일을 덤프한다는 뜻 그대로입니다.",
     "e":"<b>windows.dumpfiles</b> 입니다. 꺼낸 뒤 <code>strings</code>·YARA·VirusTotal 해시 조회로 이어갑니다. <b>파일리스 멀웨어를 파일로 만드는</b> 유일한 방법이기도 합니다."}],
91:[{"k":I,"t":"실행 파일이 UPX 로 패킹되었는지 확인하려면 PE 의 무엇을 보나요? (한글)",
     "ph":"한글","a":["섹션 이름","섹션명","섹션","section name"],
     "re":["섹션|section"],
     "hint":"UPX0, UPX1 이라는 이름이 그대로 남습니다.",
     "e":"<b>섹션 이름</b>입니다. UPX 는 <code>UPX0</code>·<code>UPX1</code> 을 남깁니다. 해제는 <code>upx -d file.exe</code> 한 줄. <b>다만 공격자가 섹션명을 바꿔두면</b> 엔트로피로 판단해야 합니다."},
    {"k":C,"t":"UPX 로 패킹된 파일 <code>sample.exe</code> 의 패킹을 해제하는 명령을 입력하세요.",
     "ph":"upx ...","a":["upx -d sample.exe"],
     "re":[r"^upx\s+(-d|--decompress)\s+\S*sample\.exe$"],
     "hint":"decompress 옵션 한 글자입니다.",
     "e":"<code>upx -d sample.exe</code> — 표준 UPX 라면 이걸로 풀립니다. 안 풀리면 <b>공격자가 UPX 헤더를 손봤다</b>는 뜻이고, 그 자체가 악성 신호입니다."}],
92:[{"k":I,"t":"악성 매크로가 들어 있는 오피스 문서를 분석하는 파이썬 도구 모음(oletools) 중, VBA 매크로를 추출하는 명령 이름은?",
     "ph":"명령 이름","a":["olevba","olevba.py"],"re":["^olevba(\\.py)?$"],
     "hint":"ole + vba",
     "e":"<b>olevba</b> — <code>olevba doc.docm</code> 로 매크로 소스와 함께 <b>자동실행·난독화·쉘 실행 같은 의심 지표를 표로</b> 정리해줍니다. 피싱 첨부 분석의 표준입니다."},
    {"k":I,"t":"악성 PDF 를 분석할 때 <code>/JavaScript</code>, <code>/OpenAction</code> 같은 위험 키워드 개수를 빠르게 세는 도구 이름은?",
     "ph":"도구 이름","a":["pdfid","pdfid.py","PDFiD"],"re":["^pdfid(\\.py)?$"],
     "hint":"Didier Stevens 가 만들었고 PDF + ID 입니다.",
     "e":"<b>pdfid</b> 입니다. 개수만 세는 1차 판별이고, 실제 내용은 <code>pdf-parser.py</code> 로 파고듭니다. <code>/OpenAction</code> 이 있으면 <b>열자마자 실행</b>이라는 뜻입니다."}],
93:[{"k":I,"t":"리눅스 CTF 포렌식에서 사용자가 친 명령을 확인하는 대표 파일은? (경로)",
     "ph":"경로","a":["~/.bash_history",".bash_history","/home/user/.bash_history"],
     "re":["bash_history"],
     "hint":"홈 디렉터리의 숨김 파일입니다.",
     "e":"<b>~/.bash_history</b> 입니다. 다만 <b>세션 종료 시에 기록</b>되고 쉽게 지워집니다. <code>HISTFILE=/dev/null</code> 로 아예 안 남기기도 하고, <b>파일이 비어 있다는 것 자체가 신호</b>입니다."},
    {"k":I,"t":"ELF 바이너리의 헤더와 섹션 정보를 보는 리눅스 표준 명령은?",
     "ph":"명령 이름","a":["readelf"],"re":["^readelf$"],
     "hint":"read + ELF",
     "e":"<b>readelf</b> 입니다. <code>readelf -h</code> 헤더, <code>-S</code> 섹션, <code>-d</code> 동적 링크. 윈도우의 PEStudio 에 해당하는 자리입니다."}],
95:[{"k":I,"t":"이메일 헤더 분석 CTF 에서, 발신 서버의 진짜 IP 를 찾기 위해 봐야 하는 헤더 이름은?",
     "ph":"헤더 이름","a":["Received","received"],"re":["^received$"],
     "hint":"중계 서버가 하나씩 추가하는 헤더입니다.",
     "e":"<b>Received</b> 입니다. 아래에서 위로 읽고, <b>우리 인프라가 추가한 위쪽만 신뢰</b>할 수 있습니다. 아래쪽은 공격자가 위조할 수 있습니다."},
    {"k":I,"t":"피싱 메일 분석에서 첨부 파일의 진짜 형식을 확인하는 리눅스 명령은? (확장자를 믿지 않기 위해)",
     "ph":"명령 이름","a":["file"],"re":["^file$"],
     "hint":"이름 그대로 한 단어입니다.",
     "e":"<b>file</b> — <code>file invoice.pdf.exe</code>. 매직 바이트로 판단하므로 확장자 위장에 속지 않습니다. CTF 든 실무든 <b>모든 파일 분석의 첫 명령</b>입니다."}],
97:[{"k":I,"t":"침해사고 보고서에서 공격자의 도구·기법·행동 패턴을 묶어 부르는 약자는? (영문 3글자)",
     "ph":"영문","a":["TTP","TTPs"],"re":["^ttps?$"],
     "hint":"Tactics, Techniques, Procedures",
     "e":"<b>TTP</b> 입니다. IOC 가 '무엇' 이라면 TTP 는 '어떻게' 입니다. 보고서에서 TTP 를 정리해두면 <b>다음 사건에서 같은 공격자를 알아볼 수 있습니다.</b>"}],
98:[{"k":I,"t":"위협 그룹에 붙는 이름은 벤더마다 다릅니다. Mandiant 가 APT29 라 부르는 그룹을 CrowdStrike 는 무엇이라 부르나요? (영문, 곰 이름)",
     "ph":"영문","a":["Cozy Bear","cozy bear","COZY BEAR"],
     "re":["cozy\\s*bear"],
     "hint":"러시아 그룹에는 Bear, 중국은 Panda, 이란은 Kitten 을 붙입니다.",
     "e":"<b>Cozy Bear</b> 입니다. CrowdStrike 는 국가별 동물을 붙입니다 — 러시아 Bear, 중국 Panda, 이란 Kitten, 북한 Chollima. <b>같은 그룹의 이름이 5개씩 되니</b> 보고서를 읽을 때 매핑표가 필요합니다."}],
100:[{"k":I,"t":"침해사고 대응에서 공격자가 최초로 시스템에 발을 들인 경로를 무엇이라 하나요? (영문)",
      "ph":"영문","a":["Initial Access","initial access","최초 침투 벡터"],
      "re":["initial\\s*access|최초\\s*침투"],
      "hint":"ATT&CK 의 첫 번째 Tactic 이름입니다.",
      "e":"<b>Initial Access</b> 입니다. 이걸 못 찾으면 아무리 정리해도 <b>같은 문으로 다시 들어옵니다.</b> 사고 대응에서 가장 먼저 확정해야 할 항목입니다."}],

# ═══════════ ACT 6 · 클라우드 ═══════════
102:[{"k":I,"t":"AWS 액세스 키 ID 가 시작하는 4글자 접두어는? (IAM 사용자 기준, 영문 대문자)",
      "ph":"영문 4글자","a":["AKIA"],"re":["^akia$"],
      "hint":"임시 자격증명은 ASIA 로 시작합니다.",
      "e":"<b>AKIA</b> 입니다. 임시(STS)는 <b>ASIA</b>. 깃허브 시크릿 스캐너가 정확히 이 패턴을 찾습니다 — 그래서 이 코스의 실습용 가짜 키는 일부러 패턴을 벗어나게 만들었습니다."}],
104:[{"k":I,"t":"AWS 침해 조사에서 공격자가 권한을 탐색할 때 CloudTrail 에 쏟아지는 오류 코드는?",
      "ph":"영문","a":["AccessDenied","access denied"],"re":["access\\s*denied"],
      "hint":"권한이 없을 때 나오는 그것입니다.",
      "e":"<b>AccessDenied</b> 입니다. <b>실패 로그가 성공보다 의도를 잘 드러냅니다.</b> 공격자는 자기가 뭘 할 수 있는지 모르니 이것저것 찔러봅니다."}],
106:[{"k":I,"t":"클라우드 침투 테스트·공격 시뮬레이션에 쓰이는 대표 오픈소스 프레임워크 이름은? (AWS 대상, 영문)",
      "ph":"영문","a":["Pacu","pacu"],"re":["^pacu$"],
      "hint":"Rhino Security Labs 가 만들었고 4글자입니다.",
      "e":"<b>Pacu</b> 입니다. Metasploit 의 클라우드 판이라 불립니다. 방어자도 이걸 돌려보고 <b>우리 CloudTrail 이 무엇을 잡는지</b> 확인합니다."}],
109:[{"k":I,"t":"EC2 인스턴스 안에서 역할 자격증명을 꺼낼 수 있는 메타데이터 서비스의 IP 주소는?",
      "ph":"IP 주소","a":["169.254.169.254"],"re":["^169\\.254\\.169\\.254$"],
      "hint":"링크로컬 대역이고 169.254 로 시작합니다.",
      "e":"<b>169.254.169.254</b> — 클라우드 CTF·SSRF 문제의 <b>단골 정답</b>입니다. SSRF 로 이 주소를 부르게 만들면 임시 자격증명이 그대로 나옵니다. IMDSv2 강제가 방어책입니다."}],
111:[{"k":I,"t":"컨테이너 탈출 CTF 에서 마운트되어 있으면 사실상 끝난 것으로 보는 파일 경로는?",
      "ph":"경로","a":["/var/run/docker.sock","docker.sock"],
      "re":["docker\\.sock"],
      "hint":"도커 데몬과 통신하는 유닉스 소켓입니다.",
      "e":"<b>/var/run/docker.sock</b> — 이게 있으면 컨테이너 안에서 <b>새 특권 컨테이너를 만들어 호스트 루트를 마운트</b>할 수 있습니다. CI 도구에서 흔히 발견됩니다."}],
113:[{"k":I,"t":"쿠버네티스 파드 안에서 서비스 어카운트 토큰이 마운트되는 경로는?",
      "ph":"경로","a":["/var/run/secrets/kubernetes.io/serviceaccount/token",
                 "/var/run/secrets/kubernetes.io/serviceaccount"],
      "re":["/var/run/secrets/kubernetes\\.io/serviceaccount"],
      "hint":"/var/run/secrets/ 아래입니다.",
      "e":"<b>/var/run/secrets/kubernetes.io/serviceaccount/token</b> — K8s CTF 에서 파드를 잡은 뒤 <b>가장 먼저 확인하는 경로</b>입니다. 여기 토큰의 RBAC 권한이 다음 단계를 결정합니다."}],
117:[{"k":I,"t":"컨테이너 안에 있는지 판별하는 CTF 단골 방법 — 어떤 파일을 읽나요? (경로)",
      "ph":"경로","a":["/proc/1/cgroup","/.dockerenv","/proc/self/cgroup"],
      "re":["/proc/(1|self)/cgroup|dockerenv"],
      "hint":"cgroup 정보나 도커가 남기는 숨김 파일입니다.",
      "e":"<b>/proc/1/cgroup</b> 또는 <b>/.dockerenv</b> 입니다. 공격자가 '내가 어디 있나' 를 확인하는 행동이라, <b>이 파일 읽기를 탐지 규칙으로</b> 만들면 정찰 단계에서 잡힙니다."}],

# ═══════════ ACT 7 · 헌팅 · 고급 ═══════════
121:[{"k":I,"t":"매년 12월 SANS 가 여는, 스토리와 함께 진행되는 유명한 무료 보안 CTF 이름은? (영문)",
      "ph":"영문","a":["Holiday Hack Challenge","holiday hack","SANS Holiday Hack Challenge"],
      "re":["holiday\\s*hack"],
      "hint":"연말 분위기의 이름입니다.",
      "e":"<b>SANS Holiday Hack Challenge</b> 입니다. 무료이고 난이도 폭이 넓어 <b>입문자가 처음 참가하기에 가장 좋은 CTF</b> 로 꼽힙니다. 지난 회차도 계속 열려 있습니다."},
     {"k":I,"t":"입문자용으로 가장 널리 추천되며 카네기멜런대가 운영하는 무료 CTF 플랫폼 이름은? (영문)",
      "ph":"영문","a":["picoCTF","pico CTF","picoctf"],"re":["^pico\\s*ctf$"],
      "hint":"'아주 작은' 을 뜻하는 접두어 + CTF",
      "e":"<b>picoCTF</b> 입니다. 상시 열려 있고 한글 자료도 많습니다. <b>포렌식·인코딩 카테고리만 골라 풀어도</b> 이 코스의 좋은 보조가 됩니다."}],
123:[{"k":I,"t":"위협 헌팅에서 '흔치 않은 것을 찾는' 기법을 영어로 무엇이라 하나요? (약자 또는 문구)",
      "ph":"영문","a":["least frequency of occurrence","LFO","stack counting","long tail analysis"],
      "re":["least\\s*frequen|^lfo$|stack\\s*count|long\\s*tail"],
      "hint":"'가장 적게 나타나는 것' 이라는 뜻입니다.",
      "e":"<b>Least Frequency of Occurrence</b>(스택 카운팅·롱테일 분석)입니다. SANS FOR508 의 핵심 기법이고, 이 코스에서 <code>sort -n</code> 으로 계속 써온 그것입니다."}],
126:[{"k":I,"t":"Elastic 이 만든, 이벤트의 <b>순서</b>를 표현할 수 있는 쿼리 언어의 약자는? (영문 3글자)",
      "ph":"영문 3글자","a":["EQL","eql"],"re":["^eql$"],
      "hint":"Event Query Language",
      "e":"<b>EQL</b> 입니다. <code>sequence by host.id with maxspan=5m [...] [...]</code> 처럼 <b>A 다음 B</b> 를 표현합니다. 단일 이벤트로는 못 잡는 공격 체인을 잡습니다."}],
131:[{"k":I,"t":"위협 인텔 공유 시 정보의 배포 범위를 표시하는 색상 기반 규약의 이름은? (영문 약자)",
      "ph":"영문 약자","a":["TLP","tlp"],"re":["^tlp$"],
      "hint":"Traffic Light Protocol",
      "e":"<b>TLP</b> 입니다. RED(수령자만) · AMBER(조직 내부) · GREEN(커뮤니티) · CLEAR(제한 없음). <b>위반하면 인텔 공급이 끊깁니다.</b>"}],
132:[{"k":I,"t":"공격 기법을 재현해 탐지를 검증하는 오픈소스 도구 중, Red Canary 가 만든 ATT&CK 기반 테스트 모음의 이름은?",
      "ph":"영문","a":["Atomic Red Team","atomic red team"],
      "re":["atomic\\s*red\\s*team"],
      "hint":"'원자 단위' 테스트라는 뜻입니다.",
      "e":"<b>Atomic Red Team</b> 입니다. 기법 하나를 <b>가장 작은 단위</b>로 재현해서, 어느 지점이 안 잡히는지 정확히 짚어냅니다."},
     {"k":I,"t":"공격 시뮬레이션과 탐지 검증을 자동화하는 상용/오픈소스 분야를 무엇이라 하나요? (영문 약자 4글자)",
      "ph":"영문 약자","a":["BAS","bas","Breach and Attack Simulation"],
      "re":["^bas$|breach\\s*and\\s*attack"],
      "hint":"Breach and Attack Simulation",
      "e":"<b>BAS</b>(Breach and Attack Simulation)입니다. 퍼플팀 활동을 제품화한 것이고, MITRE 의 <b>CALDERA</b> 가 대표적인 무료 도구입니다."}],
135:[{"k":I,"t":"2020년 발생한, 정상 업데이트에 백도어가 삽입되어 전 세계에 퍼진 대표적 공급망 공격 사건의 회사 이름은?",
      "ph":"회사 이름","a":["SolarWinds","solarwinds","솔라윈즈"],
      "re":["solar\\s*winds|솔라윈즈"],
      "hint":"네트워크 관리 소프트웨어 회사입니다.",
      "e":"<b>SolarWinds</b> 입니다. 백도어 이름은 SUNBURST. <b>소스는 깨끗하고 빌드 산출물만 감염</b>되어 코드 리뷰로는 못 잡았고, 정상 서명까지 붙어 배포됐습니다."},
     {"k":I,"t":"2024년 발견된, 압축 라이브러리에 몇 년에 걸쳐 백도어를 심으려 한 공급망 사건의 패키지 이름은?",
      "ph":"패키지 이름","a":["xz","xz-utils","liblzma"],
      "re":["^xz(-utils)?$|liblzma"],
      "hint":"두 글자짜리 압축 유틸리티입니다.",
      "e":"<b>xz-utils</b>(CVE-2024-3094)입니다. 공격자가 <b>2년간 정상 기여자로 활동</b>하며 신뢰를 쌓은 뒤 백도어를 넣었습니다. 성능 이상을 눈치챈 개발자 한 명이 우연히 발견했습니다."}],
136:[{"k":I,"t":"LLM 애플리케이션의 대표적 보안 위험을 정리한 OWASP 문서의 이름은? (영문)",
      "ph":"영문","a":["OWASP Top 10 for LLM","OWASP LLM Top 10","LLM Top 10"],
      "re":["owasp.*llm|llm.*top\\s*10"],
      "hint":"OWASP + LLM + Top 10",
      "e":"<b>OWASP Top 10 for LLM Applications</b> 입니다. 1위가 <b>Prompt Injection</b>. 로그를 LLM 으로 요약하는 파이프라인이 있다면 로그 자체가 공격 벡터가 됩니다."}],
139:[{"k":I,"t":"해외 취업·이직 시 블루팀 실무 역량을 증명하는 실기 시험 중, 24시간 IR 시나리오를 수행하는 것으로 유려한 자격증은? (영문 약자)",
      "ph":"영문 약자","a":["BTL1","btl1","Blue Team Level 1"],
      "re":["^btl\\s*1$|blue\\s*team\\s*level\\s*1"],
      "hint":"Blue Team Level 1",
      "e":"<b>BTL1</b> 입니다. 이론이 아니라 <b>실제 분석 과제를 수행</b>하는 시험이라, 신입 지원자의 실무 역량 증거로 평가가 좋습니다. 가격도 GIAC 대비 훨씬 저렴합니다."}],
140:[{"k":I,"t":"CTF 문제를 푼 뒤 풀이 과정을 정리해 공개하는 글을 무엇이라 하나요? (영문)",
      "ph":"영문","a":["write-up","writeup","라이트업"],
      "re":["write\\s*-?\\s*up|라이트업"],
      "hint":"'적어 올린다' 는 뜻입니다.",
      "e":"<b>Write-up</b> 입니다. 문제를 푸는 것보다 <b>정리하는 과정에서 더 많이 배웁니다.</b> 그리고 그게 그대로 포트폴리오가 됩니다 — 이 코스가 계속 권해온 그것입니다."}],
}
