# -*- coding: utf-8 -*-
"""추가 문항 3부 — 보충분. 도구 사용과 실무 판단에 초점."""
C = "cmd"
I = "input"

MORE_Q3 = {
3: [{"k":C,"t":"현재 디렉터리 아래 <b>모든 파일</b>에서 'password' 를 대소문자 무시하고 찾되, 파일 이름만 출력하는 명령을 입력하세요.",
     "ph":"grep ...","a":["grep -ril 'password' ."],
     "re":[r"^grep\s+-[ril]{3}\s+['\"]?password['\"]?\s+\.$",
           r"^grep\s+(-[ril]\s+){2,3}['\"]?password['\"]?\s+\.$"],
     "hint":"재귀(r) · 대소문자무시(i) · 파일명만(l) 세 옵션을 묶습니다.",
     "e":"<code>grep -ril 'password' .</code> — <code>-l</code> 은 매칭된 <b>파일 이름만</b> 냅니다. 설정 파일에 하드코딩된 비밀번호를 훑을 때 씁니다."}],
6: [{"t":"파이프라인 중간 결과를 확인하려 할 때 <code>head</code> 를 붙이는 이유는?",
     "o":["속도가 빨라져서","출력이 수만 줄일 때 앞부분만 보고 형태를 확인하기 위해","정렬되어서","오류를 막아서"],"a":1,
     "e":"단계마다 <code>| head</code> 로 <b>모양만 확인</b>하고 다음을 붙이는 것이 파이프라인을 조립하는 가장 빠른 방법입니다."}],
10:[{"k":C,"t":"특정 PID(예: 1234)가 열고 있는 파일과 소켓을 모두 보는 명령을 입력하세요.",
     "ph":"lsof ...","a":["lsof -p 1234"],
     "re":[r"^lsof\s+-p\s+1234$"],
     "hint":"프로세스를 지정하는 옵션 하나면 됩니다.",
     "e":"<code>lsof -p &lt;PID&gt;</code> — 의심 프로세스가 <b>어떤 파일을 열고 어디로 연결했는지</b> 한 번에 나옵니다."}],
12:[{"k":C,"t":"<code>/var/www</code> 아래에서 <b>최근 1일 이내에 수정된</b> 파일을 찾는 명령을 입력하세요.",
     "ph":"find ...","a":["find /var/www -type f -newermt '1 day ago'"],
     "re":[r"^find\s+/var/www\s+.*(-newermt\s+['\"]?1 day ago['\"]?|-mtime\s+-1)"],
     "hint":"수정 시각 기준 옵션은 <code>-newermt</code> 또는 <code>-mtime</code> 입니다.",
     "e":"<code>find /var/www -type f -newermt '1 day ago'</code> — 웹셸 업로드를 찾는 가장 빠른 방법입니다. <code>-mtime -1</code> 로도 됩니다."}],
16:[{"k":C,"t":"웹 로그에서 <b>상태코드 500 이상</b>인 요청만 골라내는 awk 명령을 입력하세요. (파일명 access.log, 상태코드는 9번째 필드)",
     "ph":"awk ...","a":["awk '$9 >= 500' access.log"],
     "re":[r"^awk\s+['\"]?\$9\s*>=?\s*500['\"]?\s+\S*access\.log$"],
     "hint":"필드 비교 조건만 쓰면 그 줄 전체가 출력됩니다.",
     "e":"<code>awk '$9 >= 500' access.log</code> — 5xx 는 <b>인젝션 시도가 애플리케이션을 깨뜨린 흔적</b>일 수 있어 눈여겨봐야 합니다."}],
23:[{"t":"Wireshark 에서 특정 패킷을 우클릭해 'Apply as Filter' 를 쓰는 것의 실무적 이점은?",
     "o":["더 정확해서","필터 문법을 외우지 않아도 정확한 필드 표현이 자동 생성되기 때문","속도 때문","저장되기 때문"],"a":1,
     "e":"디스플레이 필터 문법은 필드가 수천 개입니다. <b>클릭으로 만들고 거기서 수정</b>하는 것이 실무에서 훨씬 빠릅니다."}],
30:[{"k":C,"t":"tshark 로 pcap 에서 <b>DNS 질의 이름만</b> 뽑아내는 명령을 입력하세요. (파일 cap.pcap)",
     "ph":"tshark ...","a":["tshark -r cap.pcap -Y dns -T fields -e dns.qry.name"],
     "re":[r"^tshark\s+-r\s+\S*cap\.pcap\s+.*-e\s+dns\.qry\.name"],
     "hint":"읽기(-r), 표시필터(-Y), 필드출력(-T fields -e) 을 조합합니다.",
     "e":"<code>tshark -r cap.pcap -Y dns -T fields -e dns.qry.name</code> — 여기에 <code>| sort | uniq -c | sort -n</code> 을 붙이면 바로 희귀도 분석이 됩니다."}],
35:[{"t":"Zeek 로그를 awk 필드 번호 대신 <code>zeek-cut</code> 으로 다루는 것이 안전한 이유는?",
     "o":["더 빠르다","로그 버전이나 설정에 따라 필드 순서가 달라져도 이름으로 찾으므로 깨지지 않는다","압축을 풀어서","권한 때문"],"a":1,
     "e":"필드 번호는 <b>환경이 바뀌면 어긋납니다.</b> 조용히 엉뚱한 열을 읽는 것이 최악입니다."}],
44:[{"k":C,"t":"PowerShell 로 Security 로그에서 <b>이벤트 ID 4625</b> 를 최근 50건 가져오는 명령을 입력하세요.",
     "ph":"Get-WinEvent ...","a":["Get-WinEvent -FilterHashtable @{LogName='Security'; ID=4625} -MaxEvents 50"],
     "re":[r"get-winevent\s+-filterhashtable\s+@\{\s*logname\s*=\s*'?\"?security'?\"?\s*;\s*id\s*=\s*4625\s*\}\s+-maxevents\s+50"],
     "hint":"해시테이블 필터와 최대 건수 옵션을 씁니다.",
     "e":"<code>Get-WinEvent -FilterHashtable @{LogName='Security'; ID=4625} -MaxEvents 50</code> — <code>Where-Object</code> 로 거르면 수십 배 느립니다."}],
47:[{"k":I,"t":"Sysmon 에서 <b>네트워크 연결</b>을 기록하는 이벤트 ID 번호를 입력하세요.",
     "ph":"숫자","a":["3"],"re":[r"^3$"],
     "hint":"한 자리 숫자입니다.",
     "e":"<b>ID 3</b> 입니다. 1=프로세스 생성, 3=네트워크, 10=프로세스 접근, 11=파일 생성, 13=레지스트리, 22=DNS. 이 여섯 개는 외워두세요."}],
59:[{"k":I,"t":"윈도우에서 프로그램 <b>실행 증거</b>로 쓰이며 <code>C:\\Windows\\Prefetch</code> 에 <code>.pf</code> 로 저장되는 아티팩트 이름은?",
     "ph":"영문","a":["Prefetch","prefetch"],"re":[r"^prefetch$"],
     "hint":"폴더 이름 그대로입니다.",
     "e":"<b>Prefetch</b> — 실행 횟수와 마지막 8회 실행 시각까지 담깁니다. 다만 <b>서버에서는 기본 비활성</b>인 경우가 많습니다."}],
66:[{"t":"SPL 에서 <code>| sort -count</code> 의 마이너스 기호가 의미하는 것은?",
     "o":["필드 제외","내림차순 정렬","음수만 필터","계산 오류"],"a":1,
     "e":"<code>-</code> 가 내림차순입니다. 리눅스의 <code>sort -rn</code> 과 같은 역할이고, 많이 나온 것부터 보려면 필요합니다."}],
71:[{"k":C,"t":"sigma-cli 로 룰 파일 <code>myrule.yml</code> 을 Splunk 쿼리로 변환하는 명령을 입력하세요.",
     "ph":"sigma ...","a":["sigma convert -t splunk myrule.yml"],
     "re":[r"^sigma\s+convert\s+-t\s+splunk\s+\S*myrule\.yml$"],
     "hint":"convert 하위 명령에 대상(-t)을 지정합니다.",
     "e":"<code>sigma convert -t splunk myrule.yml</code> — Elastic 은 <code>-t lucene</code> 또는 <code>-t eql</code>, Sentinel 은 <code>-t kusto</code> 입니다."}],
89:[{"k":C,"t":"Volatility 3 로 메모리 이미지 <code>mem.raw</code> 의 <b>네트워크 연결</b>을 보는 명령을 입력하세요.",
     "ph":"vol.py ...","a":["vol.py -f mem.raw windows.netscan"],
     "re":[r"^(vol(\.py)?|volatility3?)\s+-f\s+\S*mem\.raw\s+windows\.netscan"],
     "hint":"플러그인 이름은 network + scan 입니다.",
     "e":"<code>windows.netscan</code> — <b>이미 끊긴 연결도</b> 메모리에 남아 있어 나옵니다. 라이브 <code>netstat</code> 로는 못 보는 정보입니다."}],
93:[{"k":C,"t":"실행 중인 컨테이너 <code>web</code> 의 <b>이미지 대비 변경된 파일</b>을 보는 명령을 입력하세요.",
     "ph":"docker ...","a":["docker diff web"],
     "re":[r"^docker\s+diff\s+web$"],
     "hint":"이미지와의 '차이' 를 보는 하위 명령입니다.",
     "e":"<code>docker diff web</code> — <code>A</code>추가 <code>C</code>변경 <code>D</code>삭제로 표시됩니다. 원본 이미지라는 <b>완벽한 기준선</b>이 있어 침해 흔적이 바로 드러납니다."}],
110:[{"k":C,"t":"Trivy 로 이미지 <code>myapp:latest</code> 의 취약점을 스캔하는 명령을 입력하세요.",
     "ph":"trivy ...","a":["trivy image myapp:latest"],
     "re":[r"^trivy\s+image\s+myapp:latest$"],
     "hint":"스캔 대상 종류를 먼저 적고 이미지 이름을 씁니다.",
     "e":"<code>trivy image myapp:latest</code> — <code>--severity HIGH,CRITICAL</code> 로 좁히고 <code>--exit-code 1</code> 을 붙이면 CI 에서 빌드를 막을 수 있습니다."}],
114:[{"k":C,"t":"쿠버네티스에서 <b>내가 할 수 있는 작업 목록</b>을 전부 확인하는 명령을 입력하세요.",
     "ph":"kubectl ...","a":["kubectl auth can-i --list"],
     "re":[r"^kubectl\s+auth\s+can-i\s+--list$"],
     "hint":"권한 확인 하위 명령에 전체 나열 옵션을 붙입니다.",
     "e":"<code>kubectl auth can-i --list</code> — 파드를 침해한 공격자가 <b>가장 먼저 치는 명령</b>이기도 합니다. 방어자도 같은 명령으로 과도한 권한을 찾습니다."}],
123:[{"k":C,"t":"프로세스 목록에서 <b>가장 드물게 나타난</b> 실행 경로 20개를 보는 파이프라인을 입력하세요. (앞 명령은 생략, 파이프부터)",
     "ph":"sort | ...","a":["sort | uniq -c | sort -n | head -20"],
     "re":[r"^sort\s*\|\s*uniq\s+-c\s*\|\s*sort\s+-n\s*\|\s*head\s+(-n\s*)?-?\s*20$"],
     "hint":"많은 순이 아니라 <b>적은 순</b>입니다. <code>-rn</code> 이 아닙니다.",
     "e":"<code>sort | uniq -c | sort -n | head -20</code> — <code>-rn</code> 이 아니라 <b><code>-n</code></b> 입니다. 흔한 것은 정상이고, 바닥에 있는 것이 조사 가치가 높습니다."}],
131:[{"t":"IOC 피드에 <code>8.8.8.8</code> 이 섞여 들어온 것을 검증 없이 차단하면?",
     "o":["별 문제 없다","구글 공용 DNS 가 막혀 사내 이름 해석이 전부 실패한다","성능만 저하","로그만 늘어난다"],"a":1,
     "e":"실제로 일어나는 사고입니다. <b>자사 인프라·공용 서비스 화이트리스트</b> 대조가 파이프라인에 반드시 있어야 합니다."}],
134:[{"k":I,"t":"건드리는 순간 100% 악성으로 판정할 수 있도록 심어두는 가짜 자격증명·파일을 무엇이라 하나요? (한글)",
     "ph":"한글 용어","a":["허니토큰","하니토큰","honeytoken"],
     "re":["허니\\s*토큰|honeytoken"],
     "hint":"'꿀' 로 시작하는 영어 단어의 한글 표기입니다.",
     "e":"<b>허니토큰</b>입니다. 정상 사용자가 접근할 이유가 없는 대상이라 <b>오탐이 구조적으로 0</b> 에 가깝고, 만드는 데 몇 분이면 됩니다."}],
}
